#!/usr/bin/env python3
from pathlib import Path
import re,sys
if len(sys.argv)!=3: raise SystemExit('usage: integrate-SOT-turn01-r10-operating-ui.py <r9.html> <r10.html>')
src=Path(sys.argv[1]).read_text()
for x in ["const BUILD='SOT-turn01-base-r9-database-master-detail'",'function dashboard(){','function detailHTML(p){','function settings(){','async function load(render=true){']:
    if src.count(x)!=1: raise SystemExit(f'R9 contract failed {x}: {src.count(x)}')
def span(text,name):
    m=list(re.finditer(r'(?m)(?:async\s+)?function\s+'+re.escape(name)+r'\s*\(',text))
    if len(m)!=1: raise SystemExit(f'function {name} ambiguous {len(m)}')
    a=m[0].start(); b=text.find('{',m[0].end()); d=0;q=None;e=False
    for i in range(b,len(text)):
        c=text[i]
        if q:
            if e:e=False
            elif c=='\\':e=True
            elif c==q:q=None
        else:
            if c in "'\"`":q=c
            elif c=='{':d+=1
            elif c=='}':
                d-=1
                if d==0:return a,i+1
    raise SystemExit('unbalanced '+name)
def repl(text,name,val):
    a,b=span(text,name); return text[:a]+val.rstrip()+text[b:]
src=src.replace("const BUILD='SOT-turn01-base-r9-database-master-detail'","const BUILD='SOT-turn01-base-r10-operating-intelligence'",1)
src=src.replace("db:null,query:'',deep:null}","db:null,query:'',deep:null,intel:null,projectIntel:{},setup:{}}",1)
css=r'''
.intelGrid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:9px}.intelCard{border:1px solid var(--line);border-radius:10px;background:#0b1b28;padding:11px}.intelCard b{display:block;font-size:20px;margin-top:3px}.recommend{border-left:4px solid var(--amber);padding:9px 11px;background:#211b0d;margin:8px 0;border-radius:7px}.setupGrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px}.setupCard{border:1px solid var(--line);border-radius:9px;padding:10px;background:#0b1b28}.setupCard .mono{font-size:11px;max-height:72px;overflow:auto}.dup{border:1px solid var(--line);border-radius:8px;margin:7px 0;padding:9px}.dup summary{cursor:pointer;font-weight:800}.dangerNum{color:#efb95c}.pickerGrid{display:grid;grid-template-columns:180px 1fr 1fr;gap:0;border:1px solid var(--line);border-radius:8px;overflow:hidden;min-height:380px}.pickerPane{border-right:1px solid var(--line);min-width:0}.pickerPane:last-child{border-right:0}.pickRow{display:block;width:100%;border:0;border-bottom:1px solid var(--line);background:#0d1b27;color:var(--txt);padding:9px;text-align:left}.pickRow:hover{background:#173047}.pathbar{padding:8px;color:var(--mut);border-bottom:1px solid var(--line);word-break:break-all}.aiGrid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.field{display:grid;gap:5px;margin:8px 0}.field input,.field select{background:#0d1b27;color:var(--txt);border:1px solid var(--line);border-radius:7px;padding:8px}@media(max-width:800px){.intelGrid,.setupGrid,.aiGrid{grid-template-columns:1fr}.pickerGrid{grid-template-columns:1fr;max-height:70vh;overflow:auto}.pickerPane{border-right:0;border-bottom:1px solid var(--line)}}
'''
src=src.replace('</style>',css+'</style>',1)
src=repl(src,'load',r'''async function load(render=true){let [s,p,a,i]=await Promise.all([api('/turn01/ssot'),api('/turn01/projects'),api('/activity?limit=80').catch(()=>({events:[]})),api('/turn01/intelligence?limit=100').catch(()=>null)]);state.ssot=s;state.projects=p.projects||p||[];state.activity=a.events||a.activity||a||[];state.intel=i;merge();if(!state.selected&&state.ssot.projects[0])state.selected=state.ssot.projects[0].project_token;if(state.selected){state.projectIntel[state.selected]=await api('/turn01/intelligence?project_token='+encodeURIComponent(state.selected)+'&limit=100').catch(()=>null)}if(render)draw()}''')
helpers=r'''
function intelSummary(i){if(!i)return'<div class="empty">Storage intelligence unavailable.</div>';let s=i.summary||{};return`<div class="intelGrid"><div class="intelCard"><span class="mut">Duplicate groups</span><b class="dangerNum">${Number(s.duplicate_groups||0).toLocaleString()}</b></div><div class="intelCard"><span class="mut">Redundant source bytes</span><b class="dangerNum">${bytes(s.duplicate_waste_bytes)}</b></div><div class="intelCard"><span class="mut">Shared across projects</span><b>${bytes(s.shared_bytes)}</b></div><div class="intelCard"><span class="mut">Unprotected shown</span><b>${Number((i.risky_content||[]).length).toLocaleString()}</b></div></div>${(i.recommendations||[]).map(r=>`<div class="recommend"><b>${esc(r.title)}</b><div class="mut">${esc(r.detail)}</div></div>`).join('')}`}
function duplicateHTML(i){let gs=i?.duplicate_groups||[];if(!gs.length)return'<div class="empty">No duplicate source groups found in this view.</div>';return gs.map(g=>`<details class="dup"><summary>${esc(g.filename||g.content_sha256)} · ${Number(g.copies)} source locations · ${bytes(g.reclaimable_bytes)} redundant</summary><div class="mono">Fingerprint: ${esc(g.content_sha256)}</div><div>${String(g.locations||'').split(',').map(x=>`<div class="mono">${esc(x)}</div>`).join('')}</div><div class="mut">Projects: ${esc(g.project_names||'')}</div></details>`).join('')}
async function selectP(t){state.selected=t;localStorage.setItem('sot.r9.selected',t);state.projectIntel[t]=await api('/turn01/intelligence?project_token='+encodeURIComponent(t)+'&limit=100').catch(()=>null);draw()}
async function openSetup(token){let [p,s]=await Promise.all([api('/turn01/projects/'+encodeURIComponent(token)),api('/turn01/projects/'+encodeURIComponent(token)+'/storage')]);state.setup={token,sources:(p.sources||[]).map(x=>x.normalized_path),target:s.target_root||'',backup:s.backup_root||''};renderSetup()}
function renderSetup(){let x=state.setup;$('#deepTitle').textContent='Project storage setup';$('#deepBody').innerHTML=`<div class="setupGrid"><div class="setupCard"><b>Sources</b><div class="mono">${x.sources.map(esc).join('<br>')||'Not assigned'}</div><button class="btn" onclick="pickStorage('source')">Assign sources</button></div><div class="setupCard"><b>Target / Copy A</b><div class="mono">${esc(x.target||'Not assigned')}</div><button class="btn" onclick="pickStorage('target')">Choose Target</button></div><div class="setupCard"><b>Backup / Copy B</b><div class="mono">${esc(x.backup||'Not assigned')}</div><button class="btn" onclick="pickStorage('backup')">Choose Backup</button></div></div><p class="mut">Sources define project membership. Target and Backup are independent safe-copy destinations; fingerprints remain SSOT identity regardless of storage role.</p>`;$('#deep').showModal()}
async function pickStorage(role){let v=await api('/turn01/volumes'),vols=v.volumes||[],cur=role==='source'?(state.setup.sources[0]||vols[0]?.path):(state.setup[role]||vols[0]?.path);await browseStorage(role,cur,vols)}
async function browseStorage(role,path,vols){let d=await api('/turn01/fs?path='+encodeURIComponent(path));let selected=role==='source'?state.setup.sources:[state.setup[role]].filter(Boolean);$('#deepTitle').textContent='Choose '+(role==='source'?'Sources':role==='target'?'Target / Copy A':'Backup / Copy B');$('#deepBody').innerHTML=`<div class="pickerGrid"><div class="pickerPane"><div class="pathbar"><b>Volumes</b></div>${vols.map(v=>`<button class="pickRow" onclick='browseStorage(${JSON.stringify(role)},${JSON.stringify(v.path)},${JSON.stringify(vols)})'><b>${esc(v.name||v.path)}</b><br><span class="mut">${bytes(v.free_bytes)} free</span></button>`).join('')}</div><div class="pickerPane"><div class="pathbar">${esc(d.path)}</div>${d.parent?`<button class="pickRow" onclick='browseStorage(${JSON.stringify(role)},${JSON.stringify(d.parent)},${JSON.stringify(vols)})'>..</button>`:''}<button class="pickRow" onclick='chooseStorage(${JSON.stringify(role)},${JSON.stringify(d.path)})'><b>Use this folder</b></button>${(d.folders||[]).map(f=>`<button class="pickRow" onclick='browseStorage(${JSON.stringify(role)},${JSON.stringify(f.path)},${JSON.stringify(vols)})'>${esc(f.name||f.path)}</button>`).join('')}</div><div class="pickerPane"><div class="pathbar"><b>Selected</b></div>${selected.map(x=>`<div class="pathbar">${esc(x)}</div>`).join('')||'<div class="empty">Nothing selected</div>'}<div style="padding:9px"><input id="newFolder" placeholder="New folder name"><button class="btn" onclick='createStorageFolder(${JSON.stringify(role)},${JSON.stringify(d.path)},${JSON.stringify(vols)})'>Create folder</button><button class="btn" onclick="renderSetup()">Back</button></div></div></div>`}
async function createStorageFolder(role,parent,vols){let name=$('#newFolder').value.trim();if(!name)return;let made=await api('/turn01/fs/folder',{method:'POST',body:JSON.stringify({parent,name})});await browseStorage(role,made.path,vols)}
async function chooseStorage(role,path){let t=state.setup.token;if(role==='source'){let a=[...state.setup.sources];if(!a.includes(path))a.push(path);await api('/turn01/projects/'+encodeURIComponent(t)+'/sources',{method:'PUT',body:JSON.stringify({sources:a})});state.setup.sources=a}else{await api('/turn01/projects/'+encodeURIComponent(t)+'/storage',{method:'PUT',body:JSON.stringify({[role+'_root']:path})});state.setup[role]=path}await load(false);renderSetup()}
function saveAI(){let provider=$('#aiProvider').value,model=$('#aiModel').value.trim(),key=$('#aiKey').value;localStorage.setItem('sot.ai.provider',provider);localStorage.setItem('sot.ai.model',model);localStorage.setItem('sot.ai.key.'+provider,key);draw()}
function aiProviderChange(){let p=$('#aiProvider').value;$('#aiModel').value=localStorage.getItem('sot.ai.model')||'';$('#aiKey').value=localStorage.getItem('sot.ai.key.'+p)||''}
'''
insert=src.index('function dashboard(){'); src=src[:insert]+helpers+'\n'+src[insert:]
src=repl(src,'detailHTML',r'''function detailHTML(p){let total=Number(p.logical_bytes||0),a=Math.max(0,total-Number(p.missing_copy_a_bytes||0)),b=Math.max(0,total-Number(p.missing_copy_b_bytes||0));let [s]=condition(p),i=state.projectIntel[p.project_token];return`<div class="detail"><div class="projectTop"><div><div class="ey">Selected project</div><h1>${esc(p.project_name)}</h1><b>${s}</b> · ${bytes(p.project_only_bytes)} unique here · ${bytes(p.shared_bytes)} shared</div><div class="actions">${!live(p)&&p.condition==='needs_scan'?`<button class="btn primary" onclick="scan('${p.project_token}')">Scan now</button>`:''}<button class="btn" onclick="openSetup('${p.project_token}')">Sources / Target / Backup</button><button class="btn" onclick="deep('${p.project_token}')">Deep dive</button></div></div><div class="bars">${smallBar('Source content',total,total)}${smallBar('Verified copy A',a,total)}${smallBar('Verified copy B',b,total)}${smallBar('Fully protected',p.protected_bytes,total)}</div>${live(p)?activeHTML(p):''}<h3>What SOT found</h3>${intelSummary(i)}<h3>Duplicate groups</h3>${duplicateHTML(i)}</div>`}''')
src=repl(src,'dashboard',r'''function dashboard(){let s=state.ssot,g=s.global,total=Number(g.unique_bytes||0),a=Math.max(0,total-Number(g.missing_copy_a_bytes||0)),b=Math.max(0,total-Number(g.missing_copy_b_bytes||0)),active=s.projects.filter(live),q=state.query.toLowerCase(),ps=s.projects.filter(p=>!q||p.project_name.toLowerCase().includes(q));if(!state.selected&&ps[0])state.selected=ps[0].project_token;let sel=s.projects.find(p=>p.project_token===state.selected);return`<div class="ey">Single source of truth</div><h1>Storage dashboard</h1><section class="panel"><div class="panelHead"><h2>Storage estate</h2><span class="mut">${Number(g.unique_content||0).toLocaleString()} unique fingerprints · ${bytes(g.shared_bytes)} shared across projects</span></div><div class="inside estate">${estateRow('Unique content',total,total)}${estateRow('Verified copy A',a,total,'good')}${estateRow('Verified copy B',b,total,'good')}${estateRow('Fully protected',g.protected_bytes,total,'good')}${estateRow('Needs protection',Math.max(g.missing_copy_a_bytes||0,g.missing_copy_b_bytes||0),total,'warn')}</div></section><section class="panel"><div class="panelHead"><h2>What SOT found</h2><span class="mut">Actionable fingerprint analysis</span></div><div class="inside">${intelSummary(state.intel)}<h3>Largest duplicate groups</h3>${duplicateHTML(state.intel)}</div></section><section class="panel"><div class="panelHead"><h2>Active now</h2><b>${active.length} operation${active.length===1?'':'s'}</b></div><div class="inside">${active.length?active.map(activeHTML).join(''):'<div class="empty">No storage work is running.</div>'}</div></section><section class="panel"><div class="panelHead"><h2>Projects</h2><span class="mut">Select a project to operate on it without leaving the dashboard</span></div><div class="master"><b>Project</b><b>Content</b><b class="hideMob">Shared</b><b class="hideMob">Safe</b><b>Status</b></div>${ps.map(masterHTML).join('')}${sel?detailHTML(sel):''}</section>`}''')
src=repl(src,'settings',r'''function settings(){let p=localStorage.getItem('sot.ai.provider')||'openrouter',m=localStorage.getItem('sot.ai.model')||'',k=localStorage.getItem('sot.ai.key.'+p)||'';return`<div class="ey">Configuration</div><h1>Settings</h1><section class="panel"><div class="panelHead"><h2>AI analysis</h2><span class="mut">Keys stay in this browser</span></div><div class="inside aiGrid"><div><div class="field"><label>Provider</label><select id="aiProvider" onchange="aiProviderChange()"><option value="openrouter" ${p==='openrouter'?'selected':''}>OpenRouter</option><option value="venice" ${p==='venice'?'selected':''}>Venice</option></select></div><div class="field"><label>Model</label><input id="aiModel" value="${esc(m)}" placeholder="Provider model ID"></div><div class="field"><label>API key</label><input id="aiKey" type="password" value="${esc(k)}" autocomplete="new-password"></div><button class="btn primary" onclick="saveAI()">Save AI configuration</button></div><div><b>AI role</b><p class="mut">AI may interpret SSOT evidence and recommend investigation. It does not replace fingerprint truth, verified-copy state, or deterministic protection decisions.</p></div></div></section><section class="panel"><div class="panelHead"><h2>Storage configuration</h2></div><div class="inside">Source, Target and Backup assignments are configured per project from Dashboard → selected project → <b>Sources / Target / Backup</b>. The picker uses the live volume catalog and can create destination folders.</div></section>`}''')
Path(sys.argv[2]).write_text(src)
print('R10 operating intelligence UI integrated')
