#!/usr/bin/env python3
"""Build approved Turn 29 state-matrix dashboard from qualified Turn 28 Ship."""
from pathlib import Path
import hashlib,json,math
SRC=Path('market-navigator-turn28-ship.html');OUT=Path('market-navigator-turn29-pre-ship.html');DERIVED=Path('market-evidence/derived-indices-persistent-v1.json');PERSIST=Path('market-evidence/persistent-indices-v1.json');REG=Path('data/market-backend/component-registry-v1.json');EXPECTED_BLOB='544661884a412c57aac08fada4f961012a4bc496';HZS=('1D','5D','MTD','YTD','1YR','3YR','5YR')
LABELS={'qqq':'QQQ','copper':'Copper','smallCaps':'Small Caps','manufacturingProduction':'Manufacturing','wti':'WTI','unemployment':'Unemployment','payrolls':'Payrolls','vix':'VIX','move':'MOVE','hySpread':'HY Spread','hyg':'HYG','nfci':'NFCI','spy':'S&P 500','dxy':'Dollar (DXY)','tenYear':'10Y Treasury','twoYear':'2Y Treasury','curve10y2y':'10Y–2Y Curve','curve10y3m':'10Y–3M Curve','cpi':'CPI','corePce':'Core PCE','fedFunds':'Fed Funds'}
def blob(b):return hashlib.sha1(f'blob {len(b)}\0'.encode()+b).hexdigest()
def once(s,a,b,label):
 n=s.count(a)
 if n!=1:raise SystemExit(f'Turn 29 blocked: {label}: expected 1 match, found {n}')
 return s.replace(a,b,1)
def pct(v,x):return sum(z<=x for z in v)/len(v) if v else .5
def score(p):return max(1,min(5,int(math.ceil(max(.000001,min(1,p))*5))))
def arr(x,e=.02):return '↑' if x>e else '↓' if x<-e else '→'
def fs(k):return 1 if k=='growth' else -1
def dashboard(p,r,d):
 out={'schema':'mn-state-matrix-v1','forecast':False,'purpose':'DESCRIPTIVE_CURRENT','scoreDefinition':'1–5 favorability quintile of current same-horizon governed movement versus historical same-span movements; 1–2 unfavorable, 3 neutral/mixed, 4–5 favorable','arrowDefinition':'selected-horizon recent direction only; not predictive','environmentDefinition':'equal visual synthesis of RSK, GRW and MAC favorability percentiles; dashboard score only, not a fourth derived index','horizons':{}};cm={c['id']:c for c in r['components']}
 for h in HZS:
  cols={};ps=[];aa=[]
  for k in ('risk','growth','macro'):
   q=p['indices'][k];hb=d['indices'][k]['horizons'][h];n=max(1,len(hb['curve'])-1);end=len(q['values'])-1;start=max(0,end-n);sg=fs(k);cur=sg*(float(q['values'][end])-float(q['values'][start]));hist=[sg*(float(q['values'][i])-float(q['values'][i-n])) for i in range(n,len(q['values'])) if q['values'][i] is not None and q['values'][i-n] is not None];ip=pct(hist,cur);ps.append(ip);aa.append(1 if cur>.02 else -1 if cur<-.02 else 0);cr=[]
   for sid in q['components']:
    x=q['componentSignals'][sid];cc=sg*(float(x[end])-float(x[start]));hh=[sg*(float(x[i])-float(x[i-n])) for i in range(n,len(x)) if x[i] is not None and x[i-n] is not None];cp=pct(hh,cc);cr.append({'id':sid,'label':LABELS.get(sid,sid),'role':cm[sid].get('role',''),'score':score(cp),'percentile':round(cp*100,1),'arrow':arr(cc),'move':round(cc,4)})
   cols[k]={'label':{'risk':'RISK','growth':'GROWTH','macro':'MACRO'}[k],'score':score(ip),'percentile':round(ip*100,1),'arrow':arr(cur),'value':round(float(q['values'][end]),2),'components':cr}
  ep=sum(ps)/3;out['horizons'][h]={'environment':{'score':max(1,min(10,round(ep*10))),'score10':round(ep*10,1),'arrow':'↑' if sum(aa)>0 else '↓' if sum(aa)<0 else '→'},'indices':cols}
 return out
def main():
 raw=SRC.read_bytes()
 if blob(raw)!=EXPECTED_BLOB:raise SystemExit('Turn 29 blocked: Turn 28 Ship baseline blob mismatch')
 d=json.loads(DERIVED.read_text());p=json.loads(PERSIST.read_text());r=json.loads(REG.read_text());z=dashboard(p,r,d);s=raw.decode()
 css='''\n/* TURN29_STATE_MATRIX */\n.mnDash{border:1px solid var(--line);border-radius:10px;background:var(--panel);padding:10px 12px;margin:0 0 8px;overflow:auto}.mnDashHz{display:flex;justify-content:center;gap:4px;margin-bottom:8px;white-space:nowrap}.mnDashHz button{border:1px solid var(--line);background:transparent;color:var(--muted);border-radius:7px;padding:4px 8px;font-size:10px;font-weight:800}.mnDashHz button.on{color:var(--text);background:#16304a;border-color:#5c7892}.mnEnv{display:grid;grid-template-columns:minmax(105px,1fr) auto auto;gap:8px;align-items:center;padding:6px 0 10px;border-bottom:1px solid var(--line)}.mnDashLink{border:0;background:none;color:var(--text);padding:0;text-align:left;font:inherit;font-weight:900;cursor:pointer}.mnArrow{font-weight:1000;margin-left:4px}.mnBlocks,.mnDots{display:flex;gap:3px;align-items:center}.mnBlock{width:14px;height:10px;border-radius:2px;background:#33404c}.mnBlock.on{background:var(--good)}.mnEnvScore{font-size:11px;color:var(--muted);font-weight:900;min-width:42px;text-align:right}.mnMatrix{display:grid;grid-template-columns:repeat(3,minmax(150px,1fr));gap:10px;padding-top:9px}.mnCol{min-width:0}.mnIndexHead{display:grid;grid-template-columns:1fr auto;gap:5px;align-items:start;margin-bottom:8px}.mnIndexName{font-size:12px}.mnDot{width:9px;height:9px;border-radius:50%;border:1px solid #52606c;background:transparent}.mnDots.s1 .mnDot:nth-child(-n+1),.mnDots.s2 .mnDot:nth-child(-n+2){background:var(--bad);border-color:var(--bad)}.mnDots.s3 .mnDot:nth-child(-n+3){background:#d8ad38;border-color:#d8ad38}.mnDots.s4 .mnDot:nth-child(-n+4),.mnDots.s5 .mnDot:nth-child(-n+5){background:var(--good);border-color:var(--good)}.mnComp{display:grid;grid-template-columns:minmax(80px,1fr) auto;gap:6px;align-items:center;min-height:28px;border-top:1px solid rgba(255,255,255,.045)}.mnComp .mnDashLink{font-size:10px;font-weight:750;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.mnComp .mnDots{justify-content:flex-end}.mnDashLegend{font-size:9px;color:var(--muted);padding-top:8px;text-align:center}.mnDash[hidden]{display:none!important}@media(max-width:700px){.mnDash{padding:8px}.mnMatrix{grid-template-columns:repeat(3,minmax(125px,1fr));gap:8px}.mnEnv{grid-template-columns:minmax(95px,1fr) auto auto}.mnDot{width:8px;height:8px}.mnBlock{width:11px}.mnComp .mnDashLink{font-size:9px}}\n''';s=once(s,'</style></head>',css+'</style></head>','CSS')
 html='<section id="mnStateDash" class="mnDash" aria-label="Current market environment dashboard"><div id="mnDashHz" class="mnDashHz"></div><div id="mnDashBody"></div><div class="mnDashLegend">1–2 unfavorable · 3 neutral/mixed · 4–5 favorable · arrows show selected-horizon recent direction, not a forecast</div></section>';anchor='<div class="card chartCard">';s=once(s,anchor,html+anchor,'dashboard placement');dj=json.dumps(z,separators=(',',':'))
 js=f'''\n/* TURN29_STATE_MATRIX_RUNTIME */\nconst MN_STATE_MATRIX_29={dj};\nfunction mnDots29(n){{return `<span class="mnDots s${{n}}" aria-label="${{n}} of 5 favorability">${{'<i class="mnDot"></i>'.repeat(5)}}</span>`}}\nfunction mnBlocks29(n){{return `<span class="mnBlocks" aria-label="${{n}} of 10 environment favorability">${{Array.from({{length:10}},(_,i)=>`<i class="mnBlock ${{i<n?'on':''}}"></i>`).join('')}}</span>`}}\nfunction mnDashOpen29(k,c){{if(k==='environment'){{renderV1();return}};if(S.level!==1)renderV1();setTimeout(()=>{{let b=document.querySelector(`#legend [data-id="${{k}}"]`);if(b)b.click();if(c)setTimeout(()=>{{let x=document.querySelector(`#legend [data-id="${{c}}"]`);if(x)x.click()}},80)}},40)}}\nfunction mnDashSetH29(h){{S.h=h;renderNow();setTimeout(mnDashRender29,0)}}\nfunction mnDashRender29(){{let root=document.getElementById('mnStateDash');if(!root)return;root.hidden=S.level!==1;let h=MN_STATE_MATRIX_29.horizons[S.h]?S.h:'5YR',q=MN_STATE_MATRIX_29.horizons[h];document.getElementById('mnDashHz').innerHTML={json.dumps(list(HZS))}.map(x=>`<button class="${{x===h?'on':''}}" onclick="mnDashSetH29('${{x}}')">${{x}}</button>`).join('');let e=q.environment,order=['risk','growth','macro'];let env=`<div class="mnEnv"><button class="mnDashLink" onclick="mnDashOpen29('environment')">ENVIRONMENT <span class="mnArrow">${{e.arrow}}</span></button>${{mnBlocks29(e.score)}}<span class="mnEnvScore">${{e.score10.toFixed(1)}} / 10</span></div>`;let cols=order.map(k=>{{let a=q.indices[k];return `<div class="mnCol"><div class="mnIndexHead"><button class="mnDashLink mnIndexName" onclick="mnDashOpen29('${{k}}')">${{a.label}} <span class="mnArrow">${{a.arrow}}</span></button>${{mnDots29(a.score)}}</div>${{a.components.map(c=>`<div class="mnComp"><button class="mnDashLink" title="${{c.role}}" onclick="mnDashOpen29('${{k}}','${{c.id}}')">${{c.label}} <span class="mnArrow">${{c.arrow}}</span></button>${{mnDots29(c.score)}}</div>`).join('')}}</div>`}}).join('');document.getElementById('mnDashBody').innerHTML=env+`<div class="mnMatrix">${{cols}}</div>`}}\nfunction currentStateEvidence29(){{return {{schema:'mn-state-matrix-v1',purpose:'DESCRIPTIVE_CURRENT',forecast:false,uiPlacement:'NOW_DASHBOARD_ANALYSIS_HEALTH',methodology:MN_STATE_MATRIX_29}}}}\n''';s=once(s,'mnxWireWhenReady();\nboot();',js+'\nmnxWireWhenReady();\nboot();\nsetTimeout(mnDashRender29,0);','runtime')
 if 'function renderNow(){S.level===1?renderV1():renderV2()}' in s:s=s.replace('function renderNow(){S.level===1?renderV1():renderV2()}','function renderNow(){S.level===1?renderV1():renderV2();setTimeout(mnDashRender29,0)}',1)
 s=once(s,"function aiEvidenceState(state){let chart=state.chart||{};return{","function aiEvidenceState(state){let chart=state.chart||{};return{currentState:currentStateEvidence29(),",'AI evidence');s=once(s," const terms=[\n"," const terms=[\n  ['Dashboard favorability','Five-circle descriptive favorability scale for RSK, GRW, MAC and each governed component.','1–2 red/unfavorable; 3 yellow/neutral or mixed; 4–5 green/favorable.'],\n  ['Dashboard arrows','Selected-horizon recent direction beside Environment, index and component labels.','Up favorable, sideways flat/mixed, down unfavorable. Descriptive only; not predictive Trend.'],\n  ['Environment score','Equal visual synthesis of current RSK, GRW and MAC favorability percentiles.','10-point dashboard orientation only; Environment is not a fourth governed derived index.'],\n",'Glossary');s=once(s,'</body>','<div id="turn29BuildMarker" class="hidden" data-build="2026.09.30.turn29-state-matrix"></div></body>','marker');s=s.replace('Market Navigator · Turn 28 Corrective Candidate','Market Navigator · Turn 29 State Matrix Candidate');OUT.write_text(s);Path('market-evidence/current-state-v1.json').write_text(json.dumps(z,indent=2)+'\n');print(json.dumps({'5YR':z['horizons']['5YR']},indent=2));print('built',OUT)
if __name__=='__main__':main()
