from pathlib import Path
p=Path('market-navigator-turn33-pre-ship.html');o=Path('market-navigator-turn34-pre-ship.html');s=p.read_text();assert 'TURN33_IN_PLACE_ANALYZE' in s;assert s.count('id="chartSurface33"')==1
needle='.turn33Analysis #chartSurface33{position:fixed!important;inset:8px!important;width:auto!important;height:auto!important;z-index:70!important;border-radius:9px!important}';assert s.count(needle)==1
css='''.turn33Analysis #nowPicker,.turn33Analysis .nowMoreMenu,.turn33Analysis #nowSeriesAbout{z-index:86!important}.turn33Analysis #nowPicker{position:fixed!important;top:58px!important;right:16px!important;bottom:16px!important}.turn33Analysis .nowMoreMenu{position:fixed!important;top:58px!important;right:16px!important}.turn33Analysis #nowSeriesAbout{position:fixed!important;top:58px!important;right:16px!important;max-height:calc(100vh - 74px)!important;overflow:auto!important}.turn33Analysis #nowTip{z-index:84!important}.turn33Analysis #nowMoreBtn{margin-right:44px!important}.turn33Analysis #turn33Close{width:36px!important;height:36px!important;top:12px!important;right:12px!important}''';s=s.replace(needle,needle+css,1)
launch="async function openStandaloneAnalysis26(id){if(S.turn33Analysis)return;let surface=$('chartSurface33');";assert s.count(launch)==1
# Preserve ordinary NOW removal exactly. Analyze uses its comparison list even when the comparison is also a native component of the parent index.
remove_fix="""const removeNowSeries25Base34=removeNowSeries25;removeNowSeries25=function(id){if(!S.turn33Analysis)return removeNowSeries25Base34(id);if(id===S.analysisRoot)return;S.nowComparisons=(S.nowComparisons||[]).filter(x=>x!==id);S.nowVisible=(S.nowVisible||[]).filter(x=>x!==id);if(S.nowActive===id){S.nowActive=S.analysisRoot;S.nowFocus=S.analysisRoot}renderV2()};\n"""
s=s.replace(launch,remove_fix+"async function openStandaloneAnalysis26(id){if(S.turn33Analysis)return;$('nowSeriesAbout')?.classList.add('hidden');$('nowPicker')?.classList.add('hidden');$('nowMoreMenu')?.classList.add('hidden');let surface=$('chartSurface33');",1)
old="await renderV2();if(surface.parentNode!==S.turn33Analysis.parent)throw new Error('TURN33_SURFACE_REPARENTED');let ids=visibleIds25();if(ids.length!==1||ids[0]!==id)throw new Error('TURN33_ANALYZE_ROOT_NOT_ISOLATED')}";assert s.count(old)==1;s=s.replace(old,"await renderV2();if(surface.parentNode!==S.turn33Analysis.parent)throw new Error('TURN33_SURFACE_REPARENTED');let ids=visibleIds25();if(ids.length!==1||ids[0]!==id)throw new Error('TURN33_ANALYZE_ROOT_NOT_ISOLATED');S.turn33Analysis.openH=S.h;S.turn33Analysis.openDisplay=S.indexDisplay||'fixed';document.body.dataset.turn34Analyze='live'}",1)
oldclose="document.body.classList.remove('turn33Analysis');$('turn33Close')?.remove();restoreNow33(a.frozen);S.turn33Analysis=null;";assert s.count(oldclose)==1;s=s.replace(oldclose,"document.body.classList.remove('turn33Analysis');delete document.body.dataset.turn34Analyze;$('turn33Close')?.remove();restoreNow33(a.frozen);S.turn33Analysis=null;",1)
s=s.replace('</body>','<div id="turn34Marker" class="hidden" data-contract="interactive-in-place-analyze"></div></body>',1);o.write_text(s);print('PASS Turn34 build',o.stat().st_size)
