from pathlib import Path

plan=Path('MARKET-NAVIGATOR-MASTER-PLAN.md')
grave=Path('MARKET-NAVIGATOR-GRAVEYARD.md')

section='''\n\n## 34. Turn 34 — Analyze interaction recovery (owner authorized 2026-10-01)\n\n### Baseline and scope\n- Turn 33 remains a rejected/recovery candidate until this section passes all gates.\n- Preserve the accepted Turn 28 main chart behavior and Turn 33 selected-root isolation.\n- No Dashboard, index mathematics, source, Health, glossary, AI commentary, or unrelated UI changes.\n\n### Required behavior\n1. Analyze opens full-workspace with exactly the selected component/index as the initial series.\n2. The Analyze presentation uses the existing NOW chart surface in place; no cloned chart/legend/renderer.\n3. `+ Add` must open the existing shared Add-Series picker above the Analyze surface; adding a valid series must immediately render it.\n4. Horizon buttons must be live in Analyze and change the chart horizon/data without changing the frozen underlying NOW state.\n5. The Fixed/Horizon display selector must be live where applicable and must re-render immediately.\n6. Existing representation/axis behavior is retained: Indexed 100 and native Y1/Y2 rules remain governed by measurement families; two families may use Y1+Y2 and invalid combinations must not silently render.\n7. More/actions, picker/about overlays, crosshair/tooltip, legend selection/removal and X close must remain interactive above the full-workspace surface.\n8. Closing Analyze restores the exact frozen NOW state.\n\n### Release-blocking qualification\n- Browser test must open Analyze from a real component, prove one initial series, click a different horizon and observe state/render change, use `+ Add` and prove a second series is rendered, exercise Fixed/Horizon when enabled, exercise legend removal, and close/reopen without state leakage.\n- Browser test must fail on page errors/console errors.\n- Static gates must prove one NOW canvas, one NOW legend, no Turn 30/31/32 donor architecture, no chart reparenting, and unchanged persistent-index mathematics/data sources.\n- A static-only PASS is prohibited.\n'''
if '## 34. Turn 34 — Analyze interaction recovery' not in plan.read_text():
    plan.write_text(plan.read_text()+section)

g='''\n\n### Turn 33 interaction-inert Analyze candidate — REJECTED 2026-10-01\n- Rejected because the full-workspace presentation placed the existing chart above auxiliary controls/overlays and qualification did not exercise real user interactions.\n- Observed failures: `+ Add` inert/hidden, horizon interaction ineffective, Fixed/Horizon ineffective; sophisticated Analyze behavior therefore unqualified.\n- Prohibition: do not accept static architecture gates as proof that Analyze works. Every Analyze release must execute browser interaction gates for Add, horizon, display mode, series removal, close/restore and runtime errors.\n- Salvageable only: selected-root isolation and frozen NOW-state concept, subject to browser qualification.\n'''
if '### Turn 33 interaction-inert Analyze candidate' not in grave.read_text():
    grave.write_text(grave.read_text()+g)
print('PASS Turn34 governance')
