#!/usr/bin/env python3
from pathlib import Path

SRC=Path('market-navigator-turn22-pre-ship.html')
OUT=Path('market-navigator-turn24-pre-ship.html')
s=SRC.read_text()

def one(old,new,label):
    global s
    n=s.count(old)
    if n!=1: raise SystemExit(f'{label}: expected 1 anchor, found {n}')
    s=s.replace(old,new,1)

def allr(old,new,label,min_count=1):
    global s
    n=s.count(old)
    if n<min_count: raise SystemExit(f'{label}: expected >= {min_count}, found {n}')
    s=s.replace(old,new)

# Identity. The application source remains a clean derivative of exact Turn 22.
one('<title>Market Navigator · Turn 22</title>','<title>Market Navigator · Turn 24</title>','title')
allr('TURN 22 PRE-SHIP','TURN 24 PRE-SHIP','build label')
allr('Market Navigator · Turn 22','Market Navigator · Turn 24','about label')

# CONFIG -> Sources is part of the canonical Config surface.
one('<button class="cfgTab" data-cfgtab="about">About</button>','<button class="cfgTab" data-cfgtab="sources">Sources</button><button class="cfgTab" data-cfgtab="about">About</button>','sources tab')
source_panel='''<div class="cfgPanel card" id="cfgSources" style="padding:14px"><h2>Sources</h2><p class="rowMeta">Register canonical instruments through the governed repository evidence pipeline. A request is not chartable until canonical evidence and Health exist.</p><div class="sourceRegisterGrid"><div class="field"><label for="sourceQuery">Ticker / name</label><input id="sourceQuery" autocomplete="off" spellcheck="false" placeholder="Dow, GAAMHX, V, NVDA, VRT, VOO, T…"></div><div class="field"><label for="sourceClass">Instrument class</label><select id="sourceClass"><option value="">Choose class…</option><option value="index">Market index</option><option value="equity">Equity</option><option value="etf">ETF</option><option value="fund_cit">Fund / CIT / NAV</option></select></div><div class="actions left"><button class="btn" id="sourceRegister">Request registration</button><button class="btn" id="sourceRefresh">Refresh</button></div><div class="cfgNote" id="sourceStatus">Identity is resolved server-side before evidence is admitted. Ambiguous symbols are never silently proxied.</div></div><div class="sourceListHead"><strong>Registered sources</strong><span>canonical evidence only</span></div><div id="sourceList" class="sourceList"></div></div>'''
one('<div class="cfgPanel card" id="cfgAbout" style="padding:14px">',source_panel+'<div class="cfgPanel card" id="cfgAbout" style="padding:14px">','sources panel')

# Credential editor. Persisted keys are never materialized into ordinary password inputs.
inputs={
'<input id="veniceKey" type="password" autocomplete="new-password" spellcheck="false" autocapitalize="off">':'<div class="secretEdit"><input id="veniceKey" type="text" autocomplete="off" spellcheck="false" autocapitalize="off" data-lpignore="true" data-1p-ignore="true" class="secretInput"><button class="btn secretReplace hidden" type="button" data-replace-key="venice">Replace key</button></div>',
'<input id="openrouterKey" type="password" autocomplete="new-password" spellcheck="false" autocapitalize="off" placeholder="sk-or-…">':'<div class="secretEdit"><input id="openrouterKey" type="text" autocomplete="off" spellcheck="false" autocapitalize="off" data-lpignore="true" data-1p-ignore="true" class="secretInput"><button class="btn secretReplace hidden" type="button" data-replace-key="openrouter">Replace key</button></div>',
'<input id="anthropicKey" type="password" autocomplete="new-password" spellcheck="false" autocapitalize="off" placeholder="sk-ant-…">':'<div class="secretEdit"><input id="anthropicKey" type="text" autocomplete="off" spellcheck="false" autocapitalize="off" data-lpignore="true" data-1p-ignore="true" class="secretInput"><button class="btn secretReplace hidden" type="button" data-replace-key="anthropic">Replace key</button></div>'}
for old,new in inputs.items(): one(old,new,'credential input')

css='''
/* TURN24_RECOVERY: geometry-only resize + credential-safe Config + canonical Sources */
.shell.nowMode .main,.shell.nowMode #view-now,.shell.nowMode .pad.now,.shell.nowMode .chartCard{height:100%!important;min-height:0!important}
.shell.nowMode .pad.now{display:grid!important;grid-template-rows:minmax(0,1fr)!important;align-items:stretch!important;padding-top:0!important;padding-bottom:0!important}
.shell.nowMode .chartCard{align-self:stretch!important;margin-top:0!important;margin-bottom:0!important;border-radius:0 0 10px 10px}
.secretEdit{display:flex;align-items:center;gap:6px;min-width:0}.secretInput{min-width:0;flex:1;-webkit-text-security:disc}.secretReplace{white-space:nowrap}
.sourceRegisterGrid{border:1px solid var(--line);border-radius:9px;background:#081522;padding:10px}.sourceListHead{display:flex;align-items:center;justify-content:space-between;gap:8px;margin:14px 0 5px}.sourceListHead span{font-size:9px;color:var(--muted)}.sourceList{border:1px solid var(--line);border-radius:9px;overflow:hidden}.sourceRow{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;padding:9px;border-bottom:1px solid var(--grid)}.sourceRow:last-child{border-bottom:0}.sourceRow strong,.sourceRow small{display:block}.sourceRow small{color:var(--muted);margin-top:2px}.sourceState{align-self:center;font-size:9px;font-weight:900}.sourceState.good{color:var(--good)}.sourceState.bad{color:var(--bad)}
@media(max-width:700px){.shell.nowMode .pad.now{padding-left:5px!important;padding-right:5px!important}.sourceRow{grid-template-columns:1fr}.secretEdit{flex-wrap:wrap}.secretReplace{margin-left:auto}}
'''
one('</style></head>',css+'</style></head>','turn24 css')

# Recovery instrumentation/state. These counters are also qualification observability.
one('nowRepresentation:null,nowPickerToken:0};','nowRepresentation:null,nowPickerToken:0,nowPaintModel:null,analyticGeneration:0,geometryPaints:0,evidenceFetches:0};','state fields')

# Count only actual evidence starts; cached geometry paints never enter this path.
one("if(!S.seriesPromises[id])S.seriesPromises[id]=j(`market-evidence/series/${id}.json`).then", "if(!S.seriesPromises[id]){S.evidenceFetches++;S.seriesPromises[id]=j(`market-evidence/series/${id}.json`).then", 'evidence fetch begin')
one("e=>{delete S.seriesPromises[id];throw e});return S.seriesPromises[id]}", "e=>{delete S.seriesPromises[id];throw e})}return S.seriesPromises[id]}", 'evidence fetch close')

# Custom-source horizons are capabilities of canonical evidence, not an invitation to synthesize 1D.
one("async function seriesAvailability(id,h=S.h,k=S.index||'risk'){try{let src=await getSeries(id),inside=obsRange(src,horizonWindow(h,k)).length", "async function seriesAvailability(id,h=S.h,k=S.index||'risk'){try{let supported=cat(id).supported_horizons;if(Array.isArray(supported)&&supported.length&&!supported.includes(h))return{available:false,reason:'unsupported-horizon',count:0};let src=await getSeries(id),inside=obsRange(src,horizonWindow(h,k)).length", 'supported horizons')

# Analytical renders publish an immutable paint model. Geometry events reuse it and do no data/state work.
one('function renderV1(){S.level=1;', 'function renderV1(){S.analyticGeneration++;S.level=1;', 'renderV1 generation')
one("captureNowState(sets,w,'indexed');draw('now',sets,w,'indexed')}", "captureNowState(sets,w,'indexed');S.nowPaintModel={sets,w:{...w},mode:'indexed'};draw('now',sets,w,'indexed')}", 'renderV1 paint model')
one('async function renderV2(){let renderSeq=++S.v2RenderSeq', 'async function renderV2(){S.analyticGeneration++;let renderSeq=++S.v2RenderSeq', 'renderV2 generation')
one("captureNowState(sets,w,mode);draw('now',sets,w,mode)}", "captureNowState(sets,w,mode);S.nowPaintModel={sets,w:{...w},mode};draw('now',sets,w,mode)}", 'renderV2 paint model')

old_toggle="$('toggle').onclick=()=>$('rail').classList.toggle('closed');function makeHz"
new_toggle="""$('toggle').onclick=()=>$('rail').classList.toggle('closed');let NOW_RESIZE_OBSERVER24=null,NOW_RESIZE_RAF24=0;function repaintNowGeometry24(){let m=S.nowPaintModel;if(S.view!=='now'||!m)return;S.geometryPaints++;$('nowTip').style.display='none';draw('now',m.sets,m.w,m.mode)}function scheduleNowGeometry24(){if(NOW_RESIZE_RAF24)cancelAnimationFrame(NOW_RESIZE_RAF24);NOW_RESIZE_RAF24=requestAnimationFrame(()=>{NOW_RESIZE_RAF24=0;repaintNowGeometry24()})}function setupNowGeometry24(){let wrap=$('nowWrap');if(!wrap||typeof ResizeObserver==='undefined'||NOW_RESIZE_OBSERVER24)return;let lastW=0,lastH=0;NOW_RESIZE_OBSERVER24=new ResizeObserver(entries=>{let r=entries[0]?.contentRect,w=Math.round(r?.width||0),h=Math.round(r?.height||0);if(!w||!h||Math.abs(w-lastW)<2&&Math.abs(h-lastH)<2)return;lastW=w;lastH=h;scheduleNowGeometry24()});NOW_RESIZE_OBSERVER24.observe(wrap)}function makeHz"""
one(old_toggle,new_toggle,'geometry observer')

# Config owns Config navigation; Library owns Library presentation.
one("function openConfig(){if(S.view!=='config')S.configReturnView=S.view;S.configStyleSaved=JSON.parse(JSON.stringify(paletteState()));nav('config');setConfigTab('ai')}", "function openConfig(tab='ai'){if(S.view!=='config')S.configReturnView=S.view;S.configStyleSaved=JSON.parse(JSON.stringify(paletteState()));nav('config');setConfigTab(tab)}", 'config api')
one("function currentAnalysis(){return analyses().find(x=>x.id===S.activeAnalysis&&!x.deletedAt)}", "function openLibraryAnalysis24(id){S.activeAnalysis=id;$('libraryWorkspace').classList.add('detailOpen');nav('library');renderLibrary()}function currentAnalysis(){return analyses().find(x=>x.id===S.activeAnalysis&&!x.deletedAt)}", 'library api')
one("if(!c.verified||!c.key||!c.model){$('settingsModal').classList.add('hidden');nav('config');setPStatus(p,'Register this provider before starting an Analysis',false);return}", "if(!c.verified||!c.key||!c.model){openConfig('ai');setPStatus(p,'Register this provider before starting an Analysis',false);return}", 'AI preflight')
one("S.activeAnalysis=analysisId;$('libraryWorkspace').classList.add('detailOpen');nav('library');renderLibrary();try{", "openLibraryAnalysis24(analysisId);try{", 'AI library navigation')

# Credential handling is transactional: failed replacement never destroys a working registration.
old_render="function renderAIConfig(){let r=aiRegistry(),ps=r.providers||{};$('defaultProvider').value=r.defaultProvider||'venice';for(let p of ['venice','openrouter','anthropic']){let q=ps[p]||{};$(p+'Key').value=q.key||'';if(p==='anthropic')$('anthropicModel').value=q.model||'';else fillModelSelect(p+'Model',q.models||([q.model].filter(Boolean)),q.model);setPStatus(p,q.verified?`registered · ${q.model}`:(q.key?'saved · validation required':'not registered'),q.verified?true:null)}$('cfgSummary').textContent=`Default: ${providerName($('defaultProvider').value)}. Keys stay in this browser's local storage.`}"
new_render="""function providerKeyForAction24(p){let q=providerRec(p),el=$(p+'Key'),btn=document.querySelector('[data-replace-key="'+p+'"]');return btn?.dataset.active==='true'?(el?.value.trim()||''):(q.key||el?.value.trim()||'')}function toggleProviderKey24(p){let el=$(p+'Key'),btn=document.querySelector('[data-replace-key="'+p+'"]'),q=providerRec(p);if(!el||!btn)return;let active=btn.dataset.active==='true';if(active){el.value='';btn.dataset.active='false';btn.textContent='Replace key';el.classList.toggle('hidden',!!q.key);setPStatus(p,q.verified?`registered · ${q.model}`:(q.key?'saved · validation required':'not registered'),q.verified?true:null);return}el.value='';el.classList.remove('hidden');btn.classList.remove('hidden');btn.dataset.active='true';btn.textContent='Cancel';setPStatus(p,'replacement draft · validate to save',null);el.focus()}function renderAIConfig(){let r=aiRegistry(),ps=r.providers||{};$('defaultProvider').value=r.defaultProvider||'venice';for(let p of ['venice','openrouter','anthropic']){let q=ps[p]||{},el=$(p+'Key'),btn=document.querySelector('[data-replace-key="'+p+'"]');el.value='';el.classList.toggle('hidden',!!q.key);if(btn){btn.classList.toggle('hidden',!q.key);btn.dataset.active='false';btn.textContent='Replace key'}if(p==='anthropic')$('anthropicModel').value=q.model||'';else fillModelSelect(p+'Model',q.models||([q.model].filter(Boolean)),q.model);setPStatus(p,q.verified?`registered · ${q.model}`:(q.key?'saved · validation required':'not registered'),q.verified?true:null)}$('cfgSummary').textContent=`Default: ${providerName($('defaultProvider').value)}. Registered keys remain in browser storage and are exposed only through explicit replacement.`}"""
one(old_render,new_render,'credential render')

old_load="async function loadProviderModels(p){let key=$(p+'Key').value.trim();if(!key){setPStatus(p,'enter key first',false);return}setPStatus(p,'loading models…');try{let ep=providerEndpoints(p),r=await fetch(ep.models,{cache:'no-store',headers:{Authorization:`Bearer ${key}`}}),x=await r.json();if(!r.ok)throw Error(x.error?.message||`HTTP ${r.status}`);let ids=(x.data||x.models||[]).map(m=>typeof m==='string'?m:(m.id||m.model)).filter(Boolean).sort();if(!ids.length)throw Error('no models returned');fillModelSelect(p+'Model',ids,providerRec(p).model);let reg=aiRegistry(),providers=reg.providers||{};providers[p]={...(providers[p]||{}),key,models:ids,verified:false};saveAIRegistry({...reg,providers});setPStatus(p,`${ids.length} models loaded · choose one`,null)}catch(e){setPStatus(p,e.message,false)}}"
new_load="""async function loadProviderModels(p){let key=providerKeyForAction24(p);if(!key){setPStatus(p,'enter key first',false);return}setPStatus(p,'loading models…');try{let ep=providerEndpoints(p),r=await fetch(ep.models,{cache:'no-store',headers:{Authorization:`Bearer ${key}`}}),x=await r.json();if(!r.ok)throw Error(x.error?.message||`HTTP ${r.status}`);let ids=(x.data||x.models||[]).map(m=>typeof m==='string'?m:(m.id||m.model)).filter(Boolean).sort();if(!ids.length)throw Error('no models returned');fillModelSelect(p+'Model',ids,providerRec(p).model);let reg=aiRegistry(),providers=reg.providers||{},prev=providers[p]||{};providers[p]={...prev,models:ids};saveAIRegistry({...reg,providers});setPStatus(p,`${ids.length} models loaded · choose one`,null)}catch(e){setPStatus(p,e.message,false)}}"""
one(old_load,new_load,'credential model load')

old_validate="async function validateProvider(p){let key=$(p+'Key').value.trim(),model=p==='anthropic'?$('anthropicModel').value.trim():$(p+'Model').value;if(!key){setPStatus(p,'enter key first',false);return}if(!model){setPStatus(p,p==='anthropic'?'enter model first':'load models and choose one first',false);return}setPStatus(p,`validating ${model}…`);try{let ep=providerEndpoints(p),headers={'Content-Type':'application/json'},body;if(p==='anthropic'){headers['x-api-key']=key;headers['anthropic-version']='2023-06-01';body={model,max_tokens:8,messages:[{role:'user',content:'Reply OK'}]}}else{headers.Authorization=`Bearer ${key}`;body={model,messages:[{role:'user',content:'Reply OK'}],max_tokens:8}}let r=await fetch(ep.chat,{method:'POST',headers,body:JSON.stringify(body)}),x=await r.json();if(!r.ok)throw Error(x.error?.message||`HTTP ${r.status}`);let reg=aiRegistry(),providers=reg.providers||{},prev=providers[p]||{};providers[p]={...prev,key,model,verified:true,verifiedAt:new Date().toISOString()};reg={...reg,providers,defaultProvider:reg.defaultProvider||p};saveAIRegistry(reg);setPStatus(p,`registered · ${model}`,true);renderAIConfig()}catch(e){let reg=aiRegistry(),providers=reg.providers||{};providers[p]={...(providers[p]||{}),key,model,verified:false};saveAIRegistry({...reg,providers});setPStatus(p,e.message,false)}}"
new_validate="""async function validateProvider(p){let key=providerKeyForAction24(p),model=p==='anthropic'?$('anthropicModel').value.trim():$(p+'Model').value;if(!key){setPStatus(p,'enter key first',false);return}if(!model){setPStatus(p,p==='anthropic'?'enter model first':'load models and choose one first',false);return}setPStatus(p,`validating ${model}…`);try{let ep=providerEndpoints(p),headers={'Content-Type':'application/json'},body;if(p==='anthropic'){headers['x-api-key']=key;headers['anthropic-version']='2023-06-01';body={model,max_tokens:8,messages:[{role:'user',content:'Reply OK'}]}}else{headers.Authorization=`Bearer ${key}`;body={model,messages:[{role:'user',content:'Reply OK'}],max_tokens:8}}let r=await fetch(ep.chat,{method:'POST',headers,body:JSON.stringify(body)}),x=await r.json();if(!r.ok)throw Error(x.error?.message||`HTTP ${r.status}`);let reg=aiRegistry(),providers=reg.providers||{},prev=providers[p]||{};providers[p]={...prev,key,model,verified:true,verifiedAt:new Date().toISOString()};reg={...reg,providers,defaultProvider:reg.defaultProvider||p};saveAIRegistry(reg);renderAIConfig();setPStatus(p,`registered · ${model}`,true)}catch(e){setPStatus(p,e.message,false)}}"""
one(old_validate,new_validate,'credential validation')

old_inputs="for(let p of ['venice','openrouter','anthropic']){$(p+'Key').addEventListener('input',()=>{let r=aiRegistry(),providers=r.providers||{},q=providers[p]||{};if(q.verified){providers[p]={...q,verified:false};saveAIRegistry({...r,providers});setPStatus(p,'changed · validate again',null)}})}$('anthropicModel').addEventListener('input',()=>{let r=aiRegistry(),providers=r.providers||{},q=providers.anthropic||{};if(q.verified){providers.anthropic={...q,verified:false};saveAIRegistry({...r,providers});setPStatus('anthropic','changed · validate again',null)}});"
new_inputs="""document.querySelectorAll('[data-replace-key]').forEach(b=>b.onclick=()=>toggleProviderKey24(b.dataset.replaceKey));for(let p of ['venice','openrouter','anthropic']){$(p+'Key').addEventListener('input',()=>setPStatus(p,'draft · validate to save',null))}$('anthropicModel').addEventListener('input',()=>setPStatus('anthropic','model draft · validate to save',null));"""
one(old_inputs,new_inputs,'credential input behavior')

# Sources runtime. Registration is an authenticated GitHub issue handoff consumed by the canonical pipeline.
source_runtime=r'''const SOURCE_REGISTRY_PATH24='data/market-backend/source-registry.json';function sourceClassName24(v){return v==='index'?'Market index':v==='equity'?'Equity':v==='etf'?'ETF':v==='fund_cit'?'Fund / CIT / NAV':v||'—'}function sourceIssueUrl24(q,cls){let title='[Market Navigator Source] '+q,body='Query: '+q+'\nClass: '+cls+'\n';return'https://github.com/acmeproducts/stuff/issues/new?'+new URLSearchParams({title,body}).toString()}async function renderSourcesConfig24(){let status=$('sourceStatus'),list=$('sourceList');if(!status||!list)return;status.textContent='Refreshing canonical source registry…';try{let cb='?cb='+Date.now(),[registry,catalog,healthEnvelope]=await Promise.all([j(SOURCE_REGISTRY_PATH24+cb),j('data/market-backend/data-catalog.json'+cb),j('market-evidence/health-envelope.json'+cb)]);S.catalog=catalog;S.catMap=Object.fromEntries((catalog.series||[]).map(x=>[x.id,x]));S.health=healthEnvelope;let regs=registry.registrations||[];list.innerHTML=regs.length?regs.map(r=>{let c=S.catMap[r.id]||{},h=healthEnvelope.series?.[r.id]||{},state=h.classification||r.status||'pending',good=['current','healthy'].includes(state),bad=['failed','missing','unresolved'].includes(state),providers=(r.providerChain||c.provider_chain||[]).map(x=>x.provider).join(' → '),horizons=c.supported_horizons||r.supportedHorizons||[];return`<div class="sourceRow" data-source-id="${esc(r.id)}"><div><strong>${esc(r.canonicalSymbol||r.query)} · ${esc(r.canonicalName||'')}</strong><small>${esc(sourceClassName24(r.instrumentClass))} · ${esc(r.measure||c.canonical_measure||'')} · ${esc(providers||'provider pending')}</small><small>${esc(c.native_cadence||'cadence pending')} · ${esc(horizons.join(' · ')||'horizons pending')}</small></div><span class="sourceState ${good?'good':bad?'bad':''}">${esc(state)}</span></div>`}).join(''):'<div class="sourceRow"><div><strong>No user-registered sources yet.</strong><small>Requests become available only after canonical collection and Health succeed.</small></div></div>';status.textContent='Canonical registry refreshed. Pending/unresolved requests are not treated as chart evidence.';renderHealth()}catch(e){status.textContent='Source registry unavailable: '+e.message;list.innerHTML=''}}$('sourceRegister').onclick=()=>{let q=$('sourceQuery').value.trim(),cls=$('sourceClass').value,status=$('sourceStatus');if(!q){status.textContent='Enter a ticker or instrument name.';return}if(!cls){status.textContent='Choose the intended instrument class. This prevents silent symbol/proxy substitution.';return}status.textContent='Opening the governed registration request. Submit it on GitHub; Refresh after collection completes.';window.open(sourceIssueUrl24(q,cls),'_blank','noopener')};$('sourceRefresh').onclick=()=>renderSourcesConfig24();'''
one('function setConfigTab(tab){',source_runtime+'function setConfigTab(tab){','sources runtime')
one("for(let [k,id] of [['ai','cfgAi'],['chart','cfgChart'],['about','cfgAbout']])$(id).classList.toggle('on',k===tab);if(tab==='chart')renderPaletteSettings()", "for(let [k,id] of [['ai','cfgAi'],['chart','cfgChart'],['sources','cfgSources'],['about','cfgAbout']])$(id).classList.toggle('on',k===tab);if(tab==='chart')renderPaletteSettings();if(tab==='sources')renderSourcesConfig24()", 'sources config tab')

# Boot geometry observer after first analytical model exists; viewport changes repaint only.
one("await initPersistence();renderV1();renderHealth();", "await initPersistence();renderV1();setupNowGeometry24();renderHealth();", 'geometry boot')
one("boot();window.addEventListener('resize',()=>{if(S.view==='now')renderNow();if(S.view==='library'&&S.activeAnalysis)", "boot();window.addEventListener('resize',()=>{if(S.view==='now')scheduleNowGeometry24();if(S.view==='library'&&S.activeAnalysis)", 'window resize old variant') if "boot();window.addEventListener('resize',()=>{if(S.view==='now')renderNow();if(S.view==='library'&&S.activeAnalysis)" in s else None
if "boot();window.addEventListener('resize',()=>{if(S.view==='now')renderNow();if(S.view==='library'){" in s:
    one("boot();window.addEventListener('resize',()=>{if(S.view==='now')renderNow();if(S.view==='library'){", "boot();window.addEventListener('resize',()=>{if(S.view==='now')scheduleNowGeometry24();if(S.view==='library'){", 'window resize')

# Build markers and invariants.
s=s.replace('/* TURN22_OWNER_CORRECTIONS:', '/* TURN24_RECOVERY: exact Turn 22 baseline + governed recovery only. */\n/* TURN22_OWNER_CORRECTIONS:',1)
assert 'settingsModal' not in s
assert 'data-cfgtab="sources"' in s and 'id="cfgSources"' in s
assert 'ResizeObserver' in s and 'repaintNowGeometry24' in s
assert 'providerKeyForAction24' in s and 'Replace key' in s
assert 'type="password"' not in s
assert 'TURN 24 PRE-SHIP' in s
OUT.write_text(s)
print('TURN24 BUILD PASS',len(s))
