from pathlib import Path

PLAN=Path('MARKET-NAVIGATOR-MASTER-PLAN.md')
GRAVE=Path('MARKET-NAVIGATOR-GRAVEYARD.md')

p=PLAN.read_text()
p=p.replace('Next release scope: Turn 22','Next release scope: Turn 23',1)
p=p.replace('**AI | Chart Config | About**','**AI | Chart Config | Sources | About**',1)
needle='''Chart Config:\n\n- Normal · Bright · Colorblind presets;\n- ten identity-bound slots;\n- color;\n- 1–12 pt width;\n- line · dash · dash-dot · dot · dot-dash;\n- live preview;\n- Save persistence;\n- unsaved close restores persisted state;\n- import/export.\n'''
insert=needle+'''\n### 19.1 Sources\nSources is the canonical instrument-registration control plane, not a local watchlist and not an ad-hoc browser quote fetcher.\n\nTurn 23 supports the v1 instrument universe:\n\n- market indices;\n- common equities;\n- ETFs;\n- fund / CIT / NAV vehicles.\n\nExamples that define the intended resolver scope include Dow Jones Industrial Average, GAAMHX, V, NVDA, VRT, VOO, and T. The entered text is never accepted blindly as provider identity. Registration resolves the requested instrument to one canonical identity and records provider-specific aliases. Ambiguous requests such as `DOW` must distinguish the Dow Jones Industrial Average from Dow Inc.; no proxy or similarly named security may be silently substituted.\n\nCanonical measure semantics are explicit by instrument class:\n\n- market index → published index level;\n- exchange-traded equity / ETF → market price;\n- fund / CIT → published NAV or unit value.\n\nTotal-return treatment is not silently substituted for price / index / NAV. A future total-return representation, if added, is a separate explicit transform.\n\nProvider resolution is an ordered compatible cascade owned by the evidence pipeline. Provider changes do not change the economic identity of the series. A provider fallback is recorded in Health/provenance. If no acceptable provider can resolve or collect an instrument, the request remains explicitly unresolved rather than fabricating evidence or substituting a proxy.\n\nHorizon capability is derived from persisted canonical evidence, not from a provider chosen per horizon. Genuine intraday evidence is required for an intraday 1D view. Daily/EOD or NAV evidence may support 5D through 5YR when sufficient history exists. Unsupported horizons are disabled rather than synthesized.\n\nA healthy registered source becomes available through NOW → Add and thereafter uses the same chart, inspection, Data, AI POV, Library freeze, export, and Health machinery as built-in sources.\n\nBecause Market Navigator is served from static GitHub Pages, the browser must never receive a repository write token. Turn 23 registration therefore uses an authenticated control-plane handoff owned by the repository; canonical registration and collection occur server-side in GitHub Actions, not by storing a second-class local series in localStorage.\n'''
if needle not in p: raise SystemExit('CONFIG marker missing')
p=p.replace(needle,insert,1)
turn23='''\n---\n\n## 25. Turn 23 — responsive frame, credential UX, and Sources control plane\n### Phase A — governance freeze\n1. Freeze this contract before application mutation.\n2. Graveyard the rail-dependent chart sizing hack, password-manager-triggering key-field behavior, local-only custom ticker stores, and provider-per-horizon source switching.\n\n### Phase B — responsive NOW frame\n1. NOW chart card remains pinned to the available workspace when the rail opens/closes.\n2. Observe actual chart-container geometry and redraw on size changes.\n3. Rail transition, device rotation, split-screen/browser viewport changes, and responsive-width changes must not create top/bottom gaps or stale canvas dimensions.\n\n### Phase C — AI credential UX\n1. Registered API keys are not repopulated into editable password inputs.\n2. Config shows provider registration/model state and an explicit Replace key action.\n3. A replacement key field exists only while replacement is active and uses password-manager/autofill suppression.\n4. Existing local provider registry compatibility is retained.\n\n### Phase D — Sources tab / registration control plane\n1. Add CONFIG → Sources.\n2. Accept ticker/name requests and instrument class intent.\n3. Resolve to canonical identity before registration; no silent proxy substitution.\n4. Store provider aliases/cascade and explicit measure semantics.\n5. Server-side registration updates canonical catalog/evidence/Health and makes healthy sources discoverable in Add.\n6. No GitHub or provider write credential is exposed to the Pages client.\n\n### Phase E — regression preservation\nPreserve the complete Turn 22 unified NOW architecture, Turn 21 source-relative indexing, exact frozen AI evidence, long-horizon display density, WTI/GDP truthfulness, Data/correlation, Library/TTS, and canonical six-command menu.\n\n### Phase F — mandatory Turn 23 qualification\nDesktop/tablet/phone must prove:\n- rail open/close changes width only; chart top/bottom stay pinned and canvas redraws to the new container;\n- no password-manager-compatible populated API-key field exists after loading registered provider state;\n- Replace key is explicit and reversible;\n- Sources tab exists and no local-only evidence series is created;\n- resolver/request flow distinguishes index/equity/ETF/fund-CIT intent;\n- canonical registered-source fixture appears through Add only when backed by persisted evidence and Health metadata;\n- unsupported/unresolved source state is explicit;\n- every Turn 22 release-blocking regression gate still passes.\n\nOnly after these gates pass may Turn 23 be merged to main and published.\n'''
if '## 25. Turn 23 — responsive frame' not in p:
    p=p.rstrip()+turn23+'\n'
PLAN.write_text(p)

g=GRAVE.read_text()
addition='''\n## Turn 23 retired patterns\n- rail-toggle handlers that guess canvas size or rely on fixed delays instead of observing the actual chart container\n- NOW layouts that vertically recenter or leave dead top/bottom space when the left rail changes width\n- repopulating saved provider secrets into ordinary `type=password` fields on Config render\n- browser password-manager ownership of Market Navigator provider keys\n- localStorage-only custom tickers that bypass canonical evidence, Health, revisions, and Library reproducibility\n- selecting a different economic source merely because the user changed chart horizon\n- silent symbol/proxy substitution, including treating ambiguous `DOW` as either Dow Inc. or the Dow Jones Industrial Average without explicit identity resolution\n- treating price, adjusted total return, index level, and NAV as interchangeable measurements\n- fabricated intraday points for daily/NAV-only sources\n'''
if '## Turn 23 retired patterns' not in g:
    g=g.rstrip()+'\n'+addition+'\n'
GRAVE.write_text(g)
