'use strict';
(() => {
  const VERSION='3.9.13', DAY=864e5;
  const RANGES=['1d','5d','1mo','3mo','6mo','ytd','1y','5y','max'];
  const LABEL={1d:'1D',5d:'5D',1mo:'1M',3mo:'3M',6mo:'6M',ytd:'YTD',1y:'1Y',5y:'5Y',max:'All'};
  const SCALE={spy:8,vix:20,dxy:8,qqq:10,tenYear:6,cpi:5,fedFunds:10,twoYear:8,wti:12};
  const ADVERSE=new Set(['vix','dxy','tenYear','cpi','fedFunds','twoYear','wti']);
  const CATEGORY_KEYS=['risk','growth','macro'];

  const css=document.createElement('style');
  css.textContent=`
    .brand small{opacity:.9}.flow393{display:none!important}
    .globalRange button:disabled,.mnRange3913 button:disabled{opacity:.26!important;cursor:not-allowed!important;background:#0b1422!important;border-color:var(--line)!important;color:var(--muted)!important}
    .mnHome3913{height:100%;display:grid;grid-template-rows:minmax(0,1.18fr) minmax(0,.82fr);gap:10px;overflow:hidden}
    .mnParent3913{display:grid;grid-template-rows:auto minmax(0,1fr);gap:5px;min-height:0;cursor:pointer}.mnParent3913:hover,.mnChild3913:hover{border-color:var(--accent)}
    .mnHead3913{display:flex;justify-content:space-between;gap:8px;align-items:flex-start}.mnMetric3913{display:flex;align-items:baseline;gap:7px;flex-wrap:wrap}.mnMetric3913 strong{font-size:27px}.mnMetric3913 .change{font-size:12px;font-weight:850}
    .mnChildren3913{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;min-height:0}.mnChild3913{display:grid;grid-template-rows:auto auto minmax(0,1fr);gap:3px;min-height:0;cursor:pointer}.mnChild3913 canvas{width:100%;height:100%;min-height:0}
    .mnModal3913{position:fixed;z-index:1500;inset:0;background:#02060de8;display:none;align-items:center;justify-content:center;padding:12px}.mnModal3913.open{display:flex}
    .mnPanel3913{width:min(1080px,100%);height:min(94vh,840px);background:#101b2d;border:1px solid var(--line);border-radius:16px;padding:13px;display:grid;grid-template-rows:auto auto minmax(0,1fr);gap:8px;overflow:hidden}
    .mnTitle3913{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.mnTitle3913 h2{margin:2px 0;font-size:24px}.mnClose3913{width:42px;height:42px;border:1px solid var(--line);border-radius:10px;background:#17243a;color:var(--text);font-size:20px}
    .mnSummary3913{display:flex;gap:10px;align-items:baseline;flex-wrap:wrap}.mnSummary3913 .main{font-size:21px;font-weight:900}.mnSummary3913 .item{font-size:11px;color:var(--muted);white-space:nowrap}.mnSummary3913 .item b{color:var(--text)}
    .mnRange3913{display:flex;gap:6px;overflow-x:auto;scrollbar-width:none}.mnRange3913::-webkit-scrollbar{display:none}.mnRange3913 button{flex:0 0 auto;border:1px solid var(--line);background:#15223a;color:var(--muted);border-radius:999px;padding:6px 10px;font-weight:780}.mnRange3913 button.active{border-color:var(--accent);background:#203b61;color:var(--text)}
    .mnBody3913{min-height:0;display:grid;grid-template-rows:minmax(0,1fr);overflow:hidden}.mnHierarchy3913{min-height:0;display:grid;grid-template-rows:minmax(220px,1.05fr) minmax(175px,.95fr);gap:8px}
    .mnChartWrap3913{position:relative;min-height:0;border:1px solid var(--line);border-radius:12px;background:#0b1728;padding:7px}.mnChartWrap3913 canvas{width:100%;height:100%;min-height:0;touch-action:none}
    .mnSubgrid3913{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:7px;min-height:0;overflow:auto}.mnSub3913{position:relative;display:grid;grid-template-rows:auto minmax(0,1fr);min-height:135px;border:1px solid var(--line);border-radius:11px;background:#0b1728;padding:7px;cursor:pointer}.mnSub3913:hover{border-color:var(--accent)}
    .mnSubHead3913{display:flex;justify-content:space-between;gap:6px;align-items:baseline;font-size:10px}.mnSubHead3913 b{font-size:12px}.mnSubHead3913 span{color:var(--muted);white-space:nowrap}.mnSub3913 canvas{width:100%;height:100%;min-height:0}
    .mnEnd3913{position:absolute;z-index:4;font-size:9px;font-weight:850;background:#07111ee8;border:1px solid var(--line);border-radius:5px;padding:2px 4px;pointer-events:none;white-space:nowrap}
    .mnGood3913{color:var(--good)!important}.mnBad3913{color:var(--bad)!important}.mnNeutral3913{color:var(--warn)!important}
    @media(max-width:700px){.mnModal3913{padding:0}.mnPanel3913{width:100%;height:100%;max-height:none;border-radius:0;padding:10px}.mnHierarchy3913{grid-template-rows:minmax(205px,.9fr) minmax(0,1.1fr)}.mnSubgrid3913{grid-template-columns:repeat(2,minmax(0,1fr));gap:5px}.mnSub3913{min-height:125px;padding:5px}.mnChildren3913{gap:5px}.mnChild3913{padding:7px}.mnMetric3913 strong{font-size:22px}.mnSummary3913{gap:6px}.mnSummary3913 .item{font-size:9px}}
  `;
  document.head.appendChild(css);
  const brand=document.querySelector('.brand small');if(brand)brand.textContent=`Directional situational awareness · Version ${VERSION}`;

  function rangeStart(range,end){const h=H[range];if(!h||h.max)return null;if(h.ytd)return Date.UTC(new Date(end).getUTCFullYear(),0,1);if(h.intraday)return end-(range==='1d'?1:5)*DAY;return end-(h.days||90)*DAY}
  function nearest(a,t){let lo=0,hi=a.length-1,ans=null;while(lo<=hi){const m=(lo+hi)>>1;if(a[m].t<=t){ans=a[m];lo=m+1}else hi=m-1}return ans}
  function requiredComponents(){return [...new Set(CATEGORY_KEYS.flatMap(k=>CATEGORY[k]?.components||[]))]}
  function boundsFor(ids,range){if(H[range]?.intraday)return null;if(!ids.length||ids.some(id=>(state.series[id]||[]).length<2))return null;const end=Math.max(...ids.map(id=>state.series[id].at(-1).t));let start=rangeStart(range,end);if(start==null)start=Math.max(...ids.map(id=>state.series[id][0].t));for(const id of ids){const a=state.series[id]||[],b=nearest(a,start);if(!b)return null;if(range!=='max'&&a[0].t>start+3*DAY)return null}return{start,end}}
  function effect(id,pct){const scale=SCALE[id]||10,sign=ADVERSE.has(id)?-1:1;return Math.max(-1,Math.min(1,sign*pct/scale))}
  function contribution(id,pct){return 50+35*effect(id,pct)}
  function componentPath(id,range,forcedBounds){const a=state.series[id]||[],bnd=forcedBounds||boundsFor([id],range);if(!bnd||a.length<2)return null;const base=nearest(a,bnd.start);if(!base||!base.v)return null;const times=[bnd.start,...a.filter(p=>p.t>bnd.start&&p.t<=bnd.end).map(p=>p.t),bnd.end];const uniq=[...new Set(times)].sort((x,y)=>x-y),data=[];for(const t of uniq){const p=nearest(a,t);if(!p)continue;const pct=(p.v/base.v-1)*100;data.push({t,v:pct,raw:p.v,contrib:contribution(id,pct)})}return{kind:'component',key:id,range,mode:'percent',title:META[id]?.name||id,kicker:(META[id]?.role||'INDEX COMPONENT').toUpperCase(),color:META[id]?.color||'#6db7ff',bounds:bnd,base:base.v,data}}
  function categoryPath(key,range){const ids=(CATEGORY[key]?.components||[]).filter(id=>META[id]);const bnd=boundsFor(ids,range);if(!bnd)return null;const children={};for(const id of ids){const p=componentPath(id,range,bnd);if(!p)return null;children[id]=p}const times=[bnd.start,bnd.end,...ids.flatMap(id=>children[id].data.map(p=>p.t))];const uniq=[...new Set(times)].sort((a,b)=>a-b),data=[];for(const t of uniq){const vals=[];for(const id of ids){const p=nearest(children[id].data,t);if(!p){vals.length=0;break}vals.push(p.contrib)}if(vals.length===ids.length)data.push({t,v:vals.reduce((a,b)=>a+b,0)/vals.length})}if(data.length<2)return null;return{kind:'category',key,range,mode:'index',title:CATEGORY[key]?.name||key,kicker:'CATEGORY INDEX · 0–100',color:'#6db7ff',bounds:bnd,children,data}}
  function regimePath(range){const all=requiredComponents(),bnd=boundsFor(all,range);if(!bnd)return null;const cats={};for(const key of CATEGORY_KEYS){const ids=(CATEGORY[key]?.components||[]).filter(id=>META[id]),children={};for(const id of ids){const p=componentPath(id,range,bnd);if(!p)return null;children[id]=p}const times=[bnd.start,bnd.end,...ids.flatMap(id=>children[id].data.map(p=>p.t))],uniq=[...new Set(times)].sort((a,b)=>a-b),data=[];for(const t of uniq){const vals=ids.map(id=>nearest(children[id].data,t)?.contrib).filter(Number.isFinite);if(vals.length===ids.length)data.push({t,v:vals.reduce((a,b)=>a+b,0)/vals.length})}if(data.length<2)return null;cats[key]={kind:'category',key,range,mode:'index',title:CATEGORY[key]?.name||key,kicker:'CATEGORY INDEX · 0–100',color:'#6db7ff',bounds:bnd,children,data}}
    const times=[bnd.start,bnd.end,...CATEGORY_KEYS.flatMap(k=>cats[k].data.map(p=>p.t))],uniq=[...new Set(times)].sort((a,b)=>a-b),data=[];for(const t of uniq){const vals=CATEGORY_KEYS.map(k=>nearest(cats[k].data,t)?.v).filter(Number.isFinite);if(vals.length===3)data.push({t,v:vals.reduce((a,b)=>a+b,0)/3)}if(data.length<2)return null;return{kind:'regime',key:'regime',range,mode:'index',title:'Regime',kicker:'REGIME SENTIMENT INDEX · 0–100',color:'#f3b347',bounds:bnd,children:cats,data}}
  function summary(e){if(!e?.data?.length)return null;const start=e.data[0].v,current=e.data.at(-1).v,change=current-start;if(e.kind==='component'){const contrib=e.data.at(-1).contrib,signal=contrib>=58?'Positive':contrib<=42?'Negative':'Neutral',cls=contrib>=58?'good':contrib<=42?'bad':'neutral';return{start:e.base,current:e.data.at(-1).raw,change,score:contrib,signal,cls}}const pos=e.kind==='regime'?62:58,neg=e.kind==='regime'?38:42,signal=current>=pos?(e.kind==='regime'?'Optimistic':'Positive'):current<=neg?(e.kind==='regime'?'Pessimistic':'Negative'):'Neutral',cls=current>=pos?'good':current<=neg?'bad':'neutral';return{start,current,change,score:current,signal,cls}}
  function pts(v){return Number.isFinite(v)?`${v>=0?'+':''}${v.toFixed(0)} pts`:'Unavailable'}
  function pct(v){return Number.isFinite(v)?`${v>=0?'+':''}${v.toFixed(2)}%`:'Unavailable'}
  function tone(c){return c==='good'?'mnGood3913':c==='bad'?'mnBad3913':'mnNeutral3913'}
  function rawFmt(id,v){try{return fmt(id,v)}catch{return Number.isFinite(v)?v.toFixed(2):'—'}}
  function supported(kind,key,range){if(H[range]?.intraday)return false;return !!(kind==='regime'?regimePath(range):kind==='category'?categoryPath(key,range):componentPath(key,range))}
  function best(kind,key,wanted){if(supported(kind,key,wanted))return wanted;return ['1y','ytd','6mo','3mo','1mo','5y','max'].find(r=>supported(kind,key,r))||wanted}

  function setup(c){const r=c.getBoundingClientRect(),d=devicePixelRatio||1,w=Math.max(1,r.width),h=Math.max(1,r.height);c.width=w*d;c.height=h*d;const x=c.getContext('2d');x.setTransform(d,0,0,d,0,0);return{x,w,h}}
  function draw(c,e,compact=false){const{x,w,h}=setup(c),d=e?.data||[],pad=compact?{l:28,r:8,t:13,b:17}:{l:46,r:14,t:18,b:25};x.clearRect(0,0,w,h);c.parentElement.querySelectorAll('.mnEnd3913').forEach(n=>n.remove());if(d.length<2){x.fillStyle='#91a3bb';x.font='11px system-ui';x.fillText('Insufficient historical coverage',pad.l,pad.t+12);return}let lo,hi;if(e.mode==='index'){lo=0;hi=100}else{const vals=d.map(p=>p.v),abs=Math.max(1,Math.abs(Math.min(...vals)),Math.abs(Math.max(...vals)));lo=-abs*1.08;hi=abs*1.08}const t0=d[0].t,t1=d.at(-1).t;x.strokeStyle='#334965';x.lineWidth=1;x.fillStyle='#a9bad0';x.font=compact?'8px system-ui':'9px system-ui';const ticks=e.mode==='index'?[0,25,50,75,100]:[lo,0,hi];ticks.forEach(v=>{const y=pad.t+(hi-v)/(hi-lo)*(h-pad.t-pad.b);x.beginPath();x.moveTo(pad.l,y);x.lineTo(w-pad.r,y);x.stroke();if(!compact)x.fillText(e.mode==='index'?String(Math.round(v)):`${v>0?'+':''}${v.toFixed(0)}%`,3,y+3)});x.strokeStyle=e.color;x.lineWidth=compact?1.7:2.2;x.beginPath();d.forEach((p,i)=>{const px=pad.l+(p.t-t0)/Math.max(1,t1-t0)*(w-pad.l-pad.r),py=pad.t+(hi-p.v)/(hi-lo)*(h-pad.t-pad.b);i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke();const xy=p=>({x:pad.l+(p.t-t0)/Math.max(1,t1-t0)*(w-pad.l-pad.r),y:pad.t+(hi-p.v)/(hi-lo)*(h-pad.t-pad.b)}),a=xy(d[0]),b=xy(d.at(-1));x.fillStyle=e.color;[a,b].forEach(p=>{x.beginPath();x.arc(p.x,p.y,3,0,Math.PI*2);x.fill()});if(!compact){x.fillStyle='#a9bad0';const sd=new Date(t0).toLocaleDateString(undefined,{month:'short',day:'numeric'}),ed=new Date(t1).toLocaleDateString(undefined,{month:'short',day:'numeric'});x.fillText(sd,pad.l,h-6);x.fillText(ed,w-pad.r-x.measureText(ed).width,h-6)}if(e.kind==='component'){endpoint(c,a,rawFmt(e.key,d[0].raw),false);endpoint(c,b,rawFmt(e.key,d.at(-1).raw),true)}}
  function endpoint(c,p,text,right){const n=document.createElement('span');n.className='mnEnd3913';n.textContent=text;c.parentElement.appendChild(n);requestAnimationFrame(()=>{if(right)n.style.right='3px';else n.style.left=Math.max(3,p.x+4)+'px';n.style.top=Math.max(3,Math.min(c.clientHeight-20,p.y-9))+'px'})}
  function rangeButtons(kind,key,range){return RANGES.map(r=>{const ok=supported(kind,key,r);return `<button data-mnrange3913="${r}" ${ok?'':'disabled'} class="${r===range&&ok?'active':''}" title="${ok?'':`Insufficient child coverage for ${LABEL[r]}`}">${LABEL[r]}</button>`}).join('')}

  function renderHome(){let range=best('regime','regime',state.range);if(range!==state.range)state.range=range;const r=regimePath(range),rs=summary(r);const host=$('#nowSnapshot');if(!host)return;host.innerHTML=`<div class="mnHome3913"><article class="card mnParent3913" data-open3913="regime"><div class="mnHead3913"><div><div class="kicker">${r?.kicker||'REGIME SENTIMENT INDEX · 0–100'}</div><div class="mnMetric3913"><strong>${Number.isFinite(rs?.current)?rs.current.toFixed(0):'—'}</strong><span>/100</span><span class="chip ${rs?.cls||'neutral'}">${rs?.signal||'Unavailable'}</span><span class="change">${pts(rs?.change)}</span></div><div class="muted tiny">${r?new Date(r.data[0].t).toLocaleDateString()+' → '+new Date(r.data.at(-1).t).toLocaleDateString():'Insufficient child coverage'} · parent = average of Risk + Growth + Macro</div></div></div><div class="chartBox"><canvas id="mnRegime3913"></canvas></div></article><div class="mnChildren3913">${CATEGORY_KEYS.map(k=>{const e=r?.children?.[k],s=summary(e);return `<article class="card mnChild3913" data-open3913="${k}"><div class="row"><h3>${CATEGORY[k].name}</h3><span class="chip ${s?.cls||'neutral'}">${s?.signal||'Unavailable'}</span></div><div class="mnMetric3913"><strong>${Number.isFinite(s?.current)?s.current.toFixed(0):'—'}</strong><span>/100</span><span class="change">${pts(s?.change)}</span></div><canvas id="mnCat3913-${k}"></canvas></article>`}).join('')}</div></div>`;requestAnimationFrame(()=>{if(r)draw($('#mnRegime3913'),r,false);CATEGORY_KEYS.forEach(k=>{const e=r?.children?.[k],c=$(`#mnCat3913-${k}`);if(c&&e)draw(c,e,true)});$$('[data-open3913]').forEach(el=>el.onclick=()=>el.dataset.open3913==='regime'?openEntity('regime','regime',range):openEntity('category',el.dataset.open3913,range))});renderGlobalRange3913()}
  function renderGlobalRange3913(){const e=$('#globalRange');if(!e)return;e.innerHTML=rangeButtons('regime','regime',state.range).replaceAll('data-mnrange3913','data-global3913');$$('[data-global3913]').forEach(b=>b.onclick=()=>{if(b.disabled)return;state.range=b.dataset.global3913;renderHome()})}

  function modal(){let m=document.getElementById('mnModal3913');if(m)return m;m=document.createElement('div');m.id='mnModal3913';m.className='mnModal3913';m.innerHTML='<div class="mnPanel3913"><div id="mnTitle3913"></div><div id="mnRanges3913" class="mnRange3913"></div><div id="mnBody3913" class="mnBody3913"></div></div>';document.body.appendChild(m);m.onclick=e=>{if(e.target===m)m.classList.remove('open')};return m}
  function openEntity(kind,key,wanted){const range=best(kind,key,wanted),e=kind==='regime'?regimePath(range):kind==='category'?categoryPath(key,range):componentPath(key,range),s=summary(e),m=modal();if(!e)return;const current=e.kind==='component'?rawFmt(key,s.current):`${s.current.toFixed(0)}/100`,start=e.kind==='component'?rawFmt(key,s.start):`${s.start.toFixed(0)}/100`,change=e.kind==='component'?pct(s.change):pts(s.change);document.getElementById('mnTitle3913').innerHTML=`<div class="mnTitle3913"><div><div class="kicker">${e.kicker}</div><h2>${e.title}</h2><div class="mnSummary3913"><span class="main">${current}</span><span class="item">Start <b>${start}</b></span><span class="item">Signal <b class="${tone(s.cls)}">${s.signal}</b></span><span class="item">Change <b>${change}</b></span>${e.kind==='component'?`<span class="item">Contribution <b>${s.score.toFixed(0)}/100</b></span>`:''}</div></div><button id="mnClose3913" class="mnClose3913">×</button></div>`;document.getElementById('mnRanges3913').innerHTML=rangeButtons(kind,key,range);const childEntries=e.kind==='regime'?CATEGORY_KEYS.map(k=>['category',k,e.children[k]]):e.kind==='category'?Object.keys(e.children).map(id=>['component',id,e.children[id]]):[];document.getElementById('mnBody3913').innerHTML=e.kind==='component'?`<div class="mnChartWrap3913"><canvas id="mnMain3913"></canvas></div>`:`<div class="mnHierarchy3913"><div class="mnChartWrap3913"><canvas id="mnMain3913"></canvas></div><div class="mnSubgrid3913">${childEntries.map(([ck,id,ce])=>{const cs=summary(ce);return `<div class="mnSub3913" data-childkind3913="${ck}" data-childkey3913="${id}"><div class="mnSubHead3913"><b>${ce.title}</b><span>${ce.kind==='component'?pct(cs.change):pts(cs.change)}</span></div><canvas id="mnSub3913-${id}"></canvas></div>`}).join('')}</div></div>`;m.classList.add('open');document.getElementById('mnClose3913').onclick=()=>m.classList.remove('open');$$('[data-mnrange3913]').forEach(b=>b.onclick=()=>{if(!b.disabled)openEntity(kind,key,b.dataset.mnrange3913)});requestAnimationFrame(()=>{draw($('#mnMain3913'),e,false);childEntries.forEach(([ck,id,ce])=>{const c=$(`#mnSub3913-${id}`);if(c)draw(c,ce,true)});$$('[data-childkind3913]').forEach(x=>x.onclick=()=>openEntity(x.dataset.childkind3913,x.dataset.childkey3913,range))})}

  renderNow=renderHome;renderGlobalRange=renderGlobalRange3913;
  regimeSeries393=function(range=state.range){return regimePath(range)?.data||[]};
  regimeHistorySlice=regimeSeries393;
  regimeSummary=function(range=state.range){const e=regimePath(range),s=summary(e);return s?{score:s.current,label:s.signal,start:s.start,end:s.current,periodPoints:s.change,periodPct:null,basePct:s.current-50}:null};
  categoryHistory393=function(key,range=state.range){return categoryPath(key,range)?.data||[]};
  categoryIndex=function(key,range=state.range){const e=categoryPath(key,range),s=summary(e);return s?{score:s.current,label:s.signal,cls:s.cls,parts:Object.values(e.children).map(c=>({id:c.key,score:summary(c).score}))}:null};
  openRegime393=()=>openEntity('regime','regime',state.range);openCategory=key=>openEntity('category',key,state.range);openDetail=id=>openEntity('component',id,state.range);

  const oldRenderAll=renderAll;renderAll=function(){oldRenderAll();renderHome()};
  renderHome();
})();