(() => {
  "use strict";
  const FILES={index:"kanban-boards.json",switch:"kanban-switch.json"};
  const KEYS={tabs:"program_portal_tabs_v2",defs:"program_matrix_definitions_v2",config:"program_portal_config_v2",token:"github_pat"};
  const DEFAULT_COLORS=["#64748b","#ef4444","#f97316","#eab308","#22c55e","#14b8a6","#3b82f6","#8b5cf6","#ec4899"];
  const AXES=["platform","stage","lineage","statusColor","title"];
  const DISPLAY_FIELDS=["title","platform","stage","lineage","dev","live","tags","notes","files","statusColor"];
  const APP_NAMES={matrix:"Board matrix",transfer:"Card transfer",builder:"Matrix studio"};
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
  const slug=s=>String(s||"").trim().toLowerCase().replace(/[^a-z0-9_-]+/g,"-").replace(/-+/g,"-").replace(/^-|-$/g,"");
  const uid=()=>`${Date.now().toString(36)}${Math.random().toString(36).slice(2,7)}`;
  const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
  const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  let index={boards:[]}, boardData={}, repoCfg={}, tabs=[], activeTab="", drag=null, touchPick=null, saveChains={}, toastTimer;
  let config={portalName:"Program",colors:DEFAULT_COLORS,owner:"acmeproducts",repo:"stuff",branch:"main"};
  let definitions=[];

  function notify(message){const t=$("#toast");t.textContent=message;t.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove("show"),2600)}
  function setSync(message,busy=false){$("#syncState").textContent=message;$("#syncState").style.color=busy?"#c4bfff":""}
  async function fetchJson(path){const r=await fetch(path,{cache:"no-store"});if(!r.ok)throw new Error(`${r.status} loading ${path}`);return r.json()}
  function boardPath(name){return `${typeof repoCfg.pathPrefix==="string"?repoCfg.pathPrefix:""}${slug(name)}.json`}
  function getCards(board){return boardData[board]?.cards||[]}
  function getStages(board){const d=boardData[board]||{};return [...new Set([...(d.stages||[]),...getCards(board).map(c=>c.stage||"Backlog")])].filter(Boolean)}
  const availableBoards=()=>index.boards.filter(b=>!b.archived);
  function cardColor(c){return c.cardColor||({red:"#ef4444",orange:"#f97316",yellow:"#eab308",green:"#22c55e",blue:"#3b82f6",purple:"#8b5cf6",gray:"#64748b"}[c.statusColor]||config.colors[0])}
  function fieldValue(c,f){const v=c?.[f];return Array.isArray(v)?v.join(", "):String(v??"").trim()||"Unassigned"}
  function optionList(values,selected){return values.map(v=>`<option value="${esc(v)}" ${v===selected?"selected":""}>${esc(v)}</option>`).join("")}
  function boardOptions(selected){return optionList(availableBoards().map(b=>b.name),selected)}
  function axisOptions(selected){return optionList(AXES,selected)}
  function persistTabs(){write(KEYS.tabs,{tabs,activeTab})}
  function openApp(app){const tab={id:uid(),app,title:APP_NAMES[app],state:{}};if(app==="matrix")tab.state={board:availableBoards()[0]?.name||"",x:"platform",y:"stage",lanes:[]};if(app==="transfer")tab.state={left:availableBoards()[0]?.name||"",right:availableBoards()[1]?.name||availableBoards()[0]?.name||""};tabs.push(tab);activeTab=tab.id;persistTabs();renderPortal();closeSidebar()}
  function closeTab(id){const at=tabs.findIndex(t=>t.id===id);tabs=tabs.filter(t=>t.id!==id);if(activeTab===id)activeTab=tabs[Math.max(0,at-1)]?.id||tabs[0]?.id||"";if(!tabs.length){persistTabs();openApp("matrix");return}persistTabs();renderPortal()}
  function updateTab(tab){persistTabs();renderView(tab)}

  async function boot(){
    config={...config,...read(KEYS.config,{})};definitions=read(KEYS.defs,[]);
    $("#portalName").textContent=config.portalName;
    repoCfg=await fetchJson(FILES.switch).catch(()=>({}));index=await fetchJson(FILES.index);
    await Promise.all(availableBoards().map(async b=>{try{boardData[b.name]=await fetchJson(boardPath(b.name));if(!Array.isArray(boardData[b.name].cards))boardData[b.name].cards=[]}catch{boardData[b.name]={cards:[]}}}));
    const saved=read(KEYS.tabs,null);tabs=saved?.tabs?.filter(t=>APP_NAMES[t.app])||[];activeTab=saved?.activeTab||tabs[0]?.id||"";
    bindShell();if(!tabs.length){openApp("matrix");setSync(`${availableBoards().length} boards ready`);return}setSync(`${availableBoards().length} boards ready`);renderPortal();
  }
  function bindShell(){
    $$(".app-link[data-app]").forEach(b=>b.onclick=()=>openApp(b.dataset.app));
    $("#newTabBtn").onclick=()=>openApp(tabs.find(t=>t.id===activeTab)?.app||"matrix");
    $("#menuBtn").onclick=openSidebar;$("#scrim").onclick=closeSidebar;$("#configBtn").onclick=showConfig;
  }
  function openSidebar(){$("#sidebar").classList.add("open");$("#scrim").classList.add("open")}
  function closeSidebar(){$("#sidebar").classList.remove("open");$("#scrim").classList.remove("open")}
  function renderPortal(){
    const root=$("#tabs");root.innerHTML=tabs.map(t=>`<button class="tab ${t.id===activeTab?"active":""}" role="tab" data-id="${t.id}"><span>${esc(t.title)}</span><span class="tab-close" aria-label="Close tab">×</span></button>`).join("");
    $$(".tab",root).forEach(el=>{el.onclick=e=>{if(e.target.classList.contains("tab-close")){e.stopPropagation();closeTab(el.dataset.id)}else{activeTab=el.dataset.id;persistTabs();renderPortal()}}});
    const views=$("#views");views.innerHTML="";const tab=tabs.find(t=>t.id===activeTab);if(tab)renderView(tab);
  }
  function renderView(tab){const views=$("#views");views.innerHTML=`<section class="view active" data-view="${tab.id}"></section>`;const root=$(".view",views);({matrix:renderMatrixApp,transfer:renderTransfer,builder:renderStudio}[tab.app])(tab,root)}
  function cardMarkup(c,board,fields=["title","platform","stage","lineage"]){
    const title=fields.includes("title")?`<div class="card-title">${esc(c.title||c.id||"Untitled")}</div>`:"";
    const meta=fields.filter(f=>f!=="title"&&!["tags","files","notes"].includes(f)).map(f=>`${esc(f)}: ${esc(fieldValue(c,f))}`).join(" · ");
    const chips=fields.includes("tags")&&(c.tags||[]).length?`<div class="card-chips">${c.tags.map(x=>`<span class="chip">#${esc(x)}</span>`).join("")}</div>`:"";
    const notes=fields.includes("notes")&&c.notes?`<div class="card-meta">${esc(c.notes).slice(0,100)}</div>`:"";
    return `<article class="card" draggable="true" tabindex="0" data-card="${esc(c.id)}" data-board="${esc(board)}" style="--card-color:${esc(cardColor(c))}"><button class="card-edit" type="button" aria-label="Edit card" title="Edit card">✎</button>${title}<div class="card-meta">${meta}</div>${chips}${notes}</article>`;
  }
  function wireCards(root,{dblEdit=true}={}){$$(".card",root).forEach(el=>{
    el.ondragstart=()=>{drag={board:el.dataset.board,id:el.dataset.card};el.classList.add("selected")};el.ondragend=()=>{drag=null;el.classList.remove("selected")};
    el.ondblclick=()=>dblEdit&&openCardEditor(el.dataset.board,el.dataset.card);$(".card-edit",el).onclick=e=>{e.stopPropagation();openCardEditor(el.dataset.board,el.dataset.card)};el.oncontextmenu=e=>{e.preventDefault();showColorMenu(e.clientX,e.clientY,el.dataset.board,el.dataset.card)};
    el.onclick=e=>{if(e.detail>1)return;if(touchPick?.board===el.dataset.board&&touchPick?.id===el.dataset.card){touchPick=null;el.classList.remove("selected")}else{touchPick={board:el.dataset.board,id:el.dataset.card};$$(".card.selected").forEach(x=>x.classList.remove("selected"));el.classList.add("selected");notify("Card selected. Tap a destination cell or lane to move it.")}};})}
  function wireDrops(root,selector,handler){$$(selector,root).forEach(el=>{el.ondragover=e=>{e.preventDefault();el.classList.add("over")};el.ondragleave=()=>el.classList.remove("over");el.ondrop=e=>{e.preventDefault();el.classList.remove("over");if(drag)handler(el,drag)};el.onclick=e=>{if(touchPick&&!e.target.closest(".card")){handler(el,touchPick);touchPick=null}}})}

  function renderMatrixApp(tab,root){
    const s=tab.state;s.board=s.board||availableBoards()[0]?.name||"";const stages=getStages(s.board);if(!Array.isArray(s.lanes)||!s.lanes.length)s.lanes=stages.slice();
    root.innerHTML=`<div class="view-head"><div><h1>Board matrix</h1><p>Filter lanes, choose two scalar dimensions, then arrange cards.</p></div><button class="btn" data-open>Open another instance</button></div>
    <div class="panel"><div class="toolbar"><div class="control"><label>Board</label><select data-board>${boardOptions(s.board)}</select></div><div class="control"><label>X axis</label><select data-x>${axisOptions(s.x)}</select></div><div class="control"><label>Y axis</label><select data-y>${axisOptions(s.y)}</select></div><div class="control"><label>Included lanes</label><select data-lanes multiple size="3">${stages.map(x=>`<option ${s.lanes.includes(x)?"selected":""}>${esc(x)}</option>`).join("")}</select></div></div></div><div class="panel matrix-scroll" style="margin-top:12px"><div class="matrix-grid"></div></div>`;
    $("[data-open]",root).onclick=()=>openApp("matrix");$("[data-board]",root).onchange=e=>{s.board=e.target.value;s.lanes=getStages(s.board);updateTab(tab)};$("[data-x]",root).onchange=e=>{s.x=e.target.value;updateTab(tab)};$("[data-y]",root).onchange=e=>{s.y=e.target.value;updateTab(tab)};$("[data-lanes]",root).onchange=e=>{s.lanes=[...e.target.selectedOptions].map(o=>o.value);updateTab(tab)};
    drawMatrix($(".matrix-grid",root),s.board,s.x,s.y,getCards(s.board).filter(c=>s.lanes.includes(c.stage)),["title","platform","stage","lineage"],(card,x,y)=>moveWithinMatrix(s.board,card,x,y,s.x,s.y));
  }
  function matrixValues(cards,field){return [...new Set(cards.map(c=>fieldValue(c,field)))].sort((a,b)=>a.localeCompare(b))}
  function drawMatrix(root,board,xField,yField,cards,fields,onMove,zField="",zValue=""){
    if(zField&&zValue)cards=cards.filter(c=>fieldValue(c,zField)===zValue);let xs=matrixValues(cards,xField),ys=matrixValues(cards,yField);if(!xs.length||!ys.length){root.innerHTML=`<div class="empty">No cards match this matrix.</div>`;return}
    root.style.gridTemplateColumns=`140px repeat(${xs.length},minmax(180px,1fr))`;root.innerHTML=`<div class="matrix-corner">${esc(yField)} ↓ / ${esc(xField)} →</div>${xs.map(x=>`<div class="matrix-header">${esc(x)}</div>`).join("")}`;
    ys.forEach(y=>{root.insertAdjacentHTML("beforeend",`<div class="matrix-rowhead">${esc(y)}</div>`);xs.forEach(x=>{const inCell=cards.filter(c=>fieldValue(c,xField)===x&&fieldValue(c,yField)===y).sort((a,b)=>(a.matrixPos||a.pos||0)-(b.matrixPos||b.pos||0));root.insertAdjacentHTML("beforeend",`<div class="matrix-cell" data-x="${esc(x)}" data-y="${esc(y)}">${inCell.map(c=>cardMarkup(c,board,fields)).join("")}</div>`)})});wireCards(root);wireDrops(root,".matrix-cell",(el,d)=>onMove(d,el.dataset.x,el.dataset.y))
  }
  function moveWithinMatrix(board,d,x,y,xf,yf){if(d.board!==board)return notify("This matrix accepts cards from its selected board only.");const c=getCards(board).find(x=>String(x.id)===String(d.id));if(!c)return;c[xf]=x;c[yf]=y;c.matrixPos=Date.now();c.updatedAt=Date.now();saveBoards([board],`Move ${c.title||c.id} in matrix`);rerenderActive()}

  function renderTransfer(tab,root){const s=tab.state;root.innerHTML=`<div class="view-head"><div><h1>Card transfer</h1><p>Drag between boards. On touch, tap a card and then its destination lane.</p></div><button class="btn" data-open>Open another instance</button></div><div class="hint">Every move updates both board JSON files immediately through GitHub.</div><div class="transfer-grid"><section class="panel board-pane" data-side="left"></section><section class="panel board-pane" data-side="right"></section></div>`;$("[data-open]",root).onclick=()=>openApp("transfer");["left","right"].forEach(side=>drawBoardPane(tab,root,side));wireCards(root);wireDrops(root,".lane",(el,d)=>transferCard(d.board,el.dataset.board,d.id,el.dataset.stage))}
  function drawBoardPane(tab,root,side){const pane=$(`[data-side="${side}"]`,root),board=tab.state[side]||availableBoards()[0]?.name||"";tab.state[side]=board;const stages=getStages(board);pane.innerHTML=`<div class="board-pane-head"><select aria-label="${side} board">${boardOptions(board)}</select><a class="btn" href="kanban.html?board=${encodeURIComponent(board)}" target="_blank">Full board</a></div><div class="mini-board">${stages.map(st=>`<div class="lane" data-board="${esc(board)}" data-stage="${esc(st)}"><h3>${esc(st)} · ${getCards(board).filter(c=>(c.stage||"Backlog")===st).length}</h3>${getCards(board).filter(c=>(c.stage||"Backlog")===st).sort((a,b)=>(a.pos||0)-(b.pos||0)).map(c=>cardMarkup(c,board)).join("")}</div>`).join("")}</div>`;$("select",pane).onchange=e=>{tab.state[side]=e.target.value;updateTab(tab)}}
  function transferCard(from,to,id,stage){const src=getCards(from),i=src.findIndex(c=>String(c.id)===String(id));if(i<0)return;const [card]=src.splice(i,1);card.stage=stage;card.pos=Math.max(0,...getCards(to).filter(c=>c.stage===stage).map(c=>Number(c.pos)||0))+1000;card.updatedAt=Date.now();getCards(to).push(card);[from,to].forEach(name=>{const b=index.boards.find(x=>x.name===name);if(b){b.cardCount=getCards(name).length;b.lastUpdated=Date.now()}});saveBoards([...new Set([from,to])],`Move ${card.title||card.id} from ${from} to ${to}`,true);rerenderActive()}

  function renderStudio(tab,root){const activeDefs=definitions.filter(d=>!d.deletedAt);tab.state.definitionId=tab.state.definitionId||activeDefs[0]?.id||"";const def=activeDefs.find(d=>d.id===tab.state.definitionId);root.innerHTML=`<div class="view-head"><div><h1>Matrix studio</h1><p>Define reusable X, Y and Z views with safe scalar fields.</p></div><button class="btn" data-open>Open another instance</button></div><div class="definition-list">${activeDefs.map(d=>`<span class="definition">${esc(d.name)} <button data-delete="${d.id}" title="Soft delete">×</button></span>`).join("")}</div><div class="studio"><section class="panel"><h2 style="margin-top:0">Create</h2><form id="definitionForm"><div class="control"><label>Name</label><input name="name" required placeholder="Release overview"></div><div class="control"><label>Board</label><select name="board">${boardOptions(availableBoards()[0]?.name)}</select></div><div class="field-row"><div class="control"><label>X</label><select name="x">${axisOptions("platform")}</select></div><div class="control"><label>Y</label><select name="y">${axisOptions("stage")}</select></div><div class="control"><label>Z filter</label><select name="z"><option value="">None</option>${axisOptions("")}</select></div></div><span class="label">Card content</span><div class="check-grid">${DISPLAY_FIELDS.map(f=>`<label class="check"><input type="checkbox" name="fields" value="${f}" ${["title","platform","stage","lineage"].includes(f)?"checked":""}>${f}</label>`).join("")}</div><button class="btn primary" style="margin-top:12px">Save matrix</button></form></section><section class="panel" id="studioUse">${def?studioUseMarkup(def):`<div class="empty">Create or select a matrix definition.</div>`}</section></div>`;
    $("[data-open]",root).onclick=()=>openApp("builder");$("#definitionForm",root).onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target),d={id:uid(),name:fd.get("name").trim(),board:fd.get("board"),x:fd.get("x"),y:fd.get("y"),z:fd.get("z"),fields:fd.getAll("fields"),createdAt:Date.now()};definitions.push(d);write(KEYS.defs,definitions);tab.state.definitionId=d.id;updateTab(tab)};
    $$('[data-delete]',root).forEach(b=>b.onclick=()=>{const d=definitions.find(x=>x.id===b.dataset.delete);if(d)d.deletedAt=Date.now();write(KEYS.defs,definitions);tab.state.definitionId="";updateTab(tab)});if(def)wireStudioUse(tab,root,def)
  }
  function studioUseMarkup(def){const zvals=def.z?matrixValues(getCards(def.board),def.z):[];return `<div class="toolbar"><div class="control"><label>Saved matrix</label><select data-def>${definitions.filter(d=>!d.deletedAt).map(d=>`<option value="${d.id}" ${d.id===def.id?"selected":""}>${esc(d.name)}</option>`).join("")}</select></div>${def.z?`<div class="control"><label>${esc(def.z)} filter</label><select data-z>${optionList(zvals,zvals[0])}</select></div>`:""}</div><div class="matrix-scroll" style="margin-top:12px"><div class="matrix-grid"></div></div>`}
  function wireStudioUse(tab,root,def){$("[data-def]",root).onchange=e=>{tab.state.definitionId=e.target.value;updateTab(tab)};const draw=()=>drawMatrix($(".matrix-grid",root),def.board,def.x,def.y,getCards(def.board),def.fields,(d,x,y)=>moveWithinMatrix(def.board,d,x,y,def.x,def.y),def.z,$("[data-z]",root)?.value||"");$("[data-z]",root)?.addEventListener("change",draw);draw()}

  function openCardEditor(board,id){const c=getCards(board).find(x=>String(x.id)===String(id));if(!c)return;const d=$("#cardDialog"),platforms=[...new Set(getCards(board).map(x=>x.platform).filter(Boolean))],stages=getStages(board),lineages=[...new Set(getCards(board).map(x=>x.lineage).filter(Boolean))];d.innerHTML=`<form class="dialog-body" method="dialog"><div class="dialog-head"><div><h2>Edit card</h2><small>${esc(board)}</small></div><button class="icon-btn" value="cancel">×</button></div><div class="dialog-grid"><div class="control span-2"><label>Title</label><input name="title" value="${esc(c.title)}" required></div><div class="control"><label>Platform</label><input name="platform" list="platforms" value="${esc(c.platform)}"><datalist id="platforms">${platforms.map(x=>`<option>${esc(x)}</option>`)}</datalist></div><div class="control"><label>Lane</label><select name="stage">${optionList(stages,c.stage)}</select></div><div class="control"><label>Lineage</label><input name="lineage" list="lineages" value="${esc(c.lineage)}"><datalist id="lineages">${lineages.map(x=>`<option>${esc(x)}</option>`)}</datalist></div><div class="control"><label>Tags (comma separated)</label><input name="tags" value="${esc((c.tags||[]).join(", "))}"></div><div class="control span-2"><label>Development link</label><input name="dev" type="url" value="${esc(c.dev)}"></div><div class="control span-2"><label>Live link</label><input name="live" type="url" value="${esc(c.live)}"></div><div class="control span-2"><label>Notes</label><textarea name="notes">${esc(c.notes)}</textarea></div><div class="control span-2"><label>Card color</label><div class="palette">${config.colors.map(color=>`<label class="swatch" style="background:${esc(color)}"><input type="radio" name="cardColor" value="${esc(color)}" ${cardColor(c)===color?"checked":""} hidden></label>`).join("")}<input name="customColor" type="color" value="${esc(cardColor(c))}" title="Custom color"></div></div></div><div class="dialog-actions"><button class="btn" value="cancel">Cancel</button><button class="btn primary" value="save">Save card</button></div></form>`;d.onclose=()=>{if(d.returnValue!=="save")return;const fd=new FormData($("form",d));Object.assign(c,{title:fd.get("title").trim(),platform:fd.get("platform").trim(),stage:fd.get("stage"),lineage:fd.get("lineage").trim(),tags:fd.get("tags").split(",").map(x=>x.trim()).filter(Boolean),dev:fd.get("dev").trim(),live:fd.get("live").trim(),notes:fd.get("notes"),cardColor:fd.get("cardColor")||fd.get("customColor"),updatedAt:Date.now()});saveBoards([board],`Update ${c.title}`);rerenderActive()};d.showModal()}
  function showColorMenu(x,y,board,id){$(".color-menu")?.remove();const menu=document.createElement("div");menu.className="color-menu";menu.style.left=`${Math.min(x,innerWidth-205)}px`;menu.style.top=`${Math.min(y,innerHeight-70)}px`;menu.innerHTML=config.colors.map(c=>`<button class="swatch" data-color="${esc(c)}" style="background:${esc(c)}" aria-label="Set ${esc(c)}"></button>`).join("")+`<input type="color" aria-label="Custom color">`;document.body.append(menu);const apply=color=>{const card=getCards(board).find(c=>String(c.id)===String(id));if(card){card.cardColor=color;card.updatedAt=Date.now();saveBoards([board],`Set card color for ${card.title||card.id}`);rerenderActive()}menu.remove()};$$('[data-color]',menu).forEach(b=>b.onclick=()=>apply(b.dataset.color));$("input",menu).onchange=e=>apply(e.target.value);setTimeout(()=>document.addEventListener("pointerdown",e=>{if(!menu.contains(e.target))menu.remove()},{once:true}),0)}

  function showConfig(){const d=$("#configDialog");d.innerHTML=`<form class="dialog-body" method="dialog"><div class="dialog-head"><h2>Portal configuration</h2><button class="icon-btn" value="cancel">×</button></div><div class="dialog-grid"><div class="control span-2"><label>Portal name</label><input name="portalName" value="${esc(config.portalName)}"></div><div class="control"><label>GitHub owner</label><input name="owner" value="${esc(config.owner)}"></div><div class="control"><label>Repository</label><input name="repo" value="${esc(config.repo)}"></div><div class="control"><label>Branch</label><input name="branch" value="${esc(config.branch)}"></div><div class="control"><label>Personal access token</label><input name="token" type="password" value="${esc(localStorage.getItem(KEYS.token)||"")}" placeholder="Stored only in this browser"></div><div class="control span-2"><label>Preset colors (comma separated hex)</label><input name="colors" value="${esc(config.colors.join(", "))}"></div></div><div class="dialog-actions"><button class="btn" value="cancel">Cancel</button><button class="btn primary" value="save">Save configuration</button></div></form>`;d.onclose=()=>{if(d.returnValue!=="save")return;const fd=new FormData($("form",d));const colors=fd.get("colors").split(",").map(x=>x.trim()).filter(x=>/^#[0-9a-f]{6}$/i.test(x));config={...config,portalName:fd.get("portalName").trim()||"Program",owner:fd.get("owner").trim(),repo:fd.get("repo").trim(),branch:fd.get("branch").trim()||"main",colors:colors.length?colors:DEFAULT_COLORS};localStorage.setItem(KEYS.token,fd.get("token").trim());write(KEYS.config,config);$("#portalName").textContent=config.portalName;notify("Configuration saved");rerenderActive()};d.showModal()}

  async function githubFetch(url,options={}){const token=localStorage.getItem(KEYS.token)?.trim();if(!token)throw new Error("Add a GitHub token in Configuration");const r=await fetch(url,{...options,headers:{Accept:"application/vnd.github+json",Authorization:`Bearer ${token}`,...options.headers}});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.status===204?{}:r.json()}
  const b64=s=>btoa(unescape(encodeURIComponent(s)));
  async function putJson(path,data,message){const base=`https://api.github.com/repos/${encodeURIComponent(config.owner)}/${encodeURIComponent(config.repo)}/contents/${path.split("/").map(encodeURIComponent).join("/")}`,ref=`?ref=${encodeURIComponent(config.branch)}`;let sha;try{sha=(await githubFetch(base+ref)).sha}catch(e){if(!String(e.message).startsWith("404"))throw e}await githubFetch(base,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({message,content:b64(JSON.stringify(data,null,2)+"\n"),branch:config.branch,...(sha?{sha}:{})})})}
  function saveBoards(names,message,withIndex=false){const key=[...names].sort().join("|");saveChains[key]=(saveChains[key]||Promise.resolve()).then(async()=>{setSync("Saving to GitHub…",true);for(const name of names)await putJson(boardPath(name),boardData[name],message);if(withIndex)await putJson(FILES.index,index,message);setSync("Saved to GitHub");notify("Changes saved")}).catch(e=>{setSync("Save failed");notify(`Save failed: ${e.message}`)});return saveChains[key]}
  function rerenderActive(){const tab=tabs.find(t=>t.id===activeTab);if(tab)renderView(tab)}
  window.addEventListener("keydown",e=>{if(e.key==="Escape")$(".color-menu")?.remove()});
  boot().catch(e=>{setSync("Could not load boards");$("#views").innerHTML=`<div class="panel empty"><b>Program portal could not start.</b><br>${esc(e.message)}</div>`;bindShell()});
})();
