'use strict';
if(typeof WSL!=='undefined' && WSL){
 const PARALLEL_BUILD='2026.08.18.6.7-wsl-parallel';
 const WORKERS=4;
 const buildEl=document.querySelector('.build');if(buildEl)buildEl.textContent='UI v0.4.1 · '+PARALLEL_BUILD;
 let saveDraftTimer=null,lastWorkerToast='';
 const persistDraft=()=>{clearTimeout(saveDraftTimer);saveDraftTimer=setTimeout(()=>api('/setup/draft',{method:'POST',body:JSON.stringify(state.draft)}).catch(e=>toast('Draft save failed: '+e.message,true)),180)};
 const fmtMinutes=v=>Number(v||0).toFixed(Number(v||0)>=10?1:2)+' min';
 const fmtClock=v=>v?new Date(v).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'}):'—';

 rootsHtml=function(){return`<button class="locationRow ${!state.activeRoot?'active':''}" id="rootRow">⌂ Root<small>All server-visible volumes</small></button>`+state.roots.map(r=>`<button class="locationRow ${state.activeRoot?.id===r.id?'active':''}" data-root-id="${esc(r.id)}" ${r.available===false?'disabled':''}>▣ ${esc(r.label)}<small>${esc(r.path)}${r.available===false?' · unavailable':''}</small></button>`).join('')};
 sourceRowsHtml=function(){const rows=visibleRows();if(!rows.length)return'<div class="empty"><strong>No matching folders</strong>Root-level files are intentionally ignored.</div>';return rows.map(r=>`<div class="sourceRow"><input class="sourceCheck" type="checkbox" data-check-path="${esc(r.path)}" ${state.selected.has(r.path)?'checked':''}><button class="sourceOpen" data-drill="${esc(r.path)}" title="${esc(r.path)}">${esc(r.name)}</button><span class="num">—</span><span class="num">${r.last?new Date(r.last).toLocaleDateString():'—'}</span></div>`).join('')};
 stagedHtml=function(){const summary=`<div class="callout" style="margin-bottom:7px"><strong>${state.draft.sources.length.toLocaleString()} source folder${state.draft.sources.length===1?'':'s'}</strong></div>`;return summary+(state.draft.sources.length?state.draft.sources.map((s,i)=>`<div class="stageCard" data-note="${i}" title="${esc((s.root_label?s.root_label+' / ':'')+s.path)}"><div><strong>${esc(s.name)}</strong><div class="stagePath mono">${esc((s.root_label?s.root_label+' / ':'')+s.path)}</div><div class="stageNote">${s.note?esc(s.note):'Add optional note…'}</div></div><button class="stageX" data-rm="${i}">×</button></div>`).join(''):'<div class="empty"><strong>No sources added</strong>Select folders in Source(s), then Add selected.</div>')};

 const oldWireSetup67=wireSetup;
 wireSetup=function(){
  oldWireSetup67();
  const pn=$('#projectName'),note=$('#projectNote');if(pn)pn.oninput=e=>{state.draft.name=e.target.value;const h=$$('.paneHeader .grow')[2];if(h)h.textContent=e.target.value||'Project';$('#createProject').disabled=!state.draft.name.trim()||!state.draft.sources.length;persistDraft()};if(note)note.oninput=e=>{state.draft.note=e.target.value;persistDraft()};
  const add=$('#addSelected');if(add)add.onclick=()=>{for(const p of state.selected){const r=state.scope.find(x=>x.path===p);if(!r)continue;const s={id:state.activeRoot.id+'::'+p,root_id:state.activeRoot.id,root_label:state.activeRoot.label,path:p,name:r.name,note:''};if(!state.draft.sources.some(x=>x.id===s.id))state.draft.sources.push(s)}persistDraft();renderSetup()};
  $$('[data-rm]').forEach(b=>b.onclick=e=>{e.stopPropagation();state.draft.sources.splice(Number(b.dataset.rm),1);persistDraft();renderSetup()});
  $$('[data-note]').forEach(c=>c.onclick=e=>{if(e.target.closest('[data-rm]'))return;const i=Number(c.dataset.note),n=prompt('Optional source note',state.draft.sources[i].note||'');if(n!==null){state.draft.sources[i].note=n.trim();persistDraft();renderSetup()}});
 };
 loadScope=async function(force=false){if(!state.activeRoot)return;state.scope=[];state.selected.clear();renderSetup('Reading folders…');try{const base=await api('/fs?path='+encodeURIComponent(state.activePath)+(force?'&force=1':''));state.scope=base.folders||[];state.selected=new Set(state.scope.map(x=>x.path));renderSetup(`Ready · ${state.scope.length.toLocaleString()} folders · root files ignored`)}catch(e){renderReadStatus('Error · '+e.message);toast(e.message,true)}};

 async function loadDraft67(){try{const d=await api('/setup/draft');if(d&&(!state.draft.name&&!state.draft.note&&!state.draft.sources.length)){state.draft={name:d.name||'',note:d.note||'',sources:Array.isArray(d.sources)?d.sources:[]};if(state.route==='setup')renderSetup()}}catch(e){toast('Draft load failed: '+e.message,true)}}

 function folderTelemetry(live){const rows=live?.folder_rows||[];if(!rows.length)return'<tr><td colspan="7">No indexed folders yet.</td></tr>';return rows.map(r=>`<tr><td title="${esc(r.dir_path)}"><strong>${esc(r.relative_dir||r.dir_path.split('/').pop()||r.dir_path)}</strong></td><td class="mono">${esc(r.current_item||'')}</td><td>${fmtBytes(Number(r.bytes_seen||0))}</td><td>${Number(r.files_seen||0).toLocaleString()}</td><td>${fmtClock(r.started_at)}</td><td>${fmtClock(r.ended_at)}</td><td>${fmtMinutes(r.elapsed_seconds||0)}</td></tr>`).join('')}
 function projectTotals(live){const t=live?.totals||{};const mins=(live?.folder_rows||[]).reduce((a,r)=>a+Number(r.elapsed_seconds||0),0);return`<div class="callout" style="margin:10px 0"><strong>Folders:</strong> ${Number(t.folders||0).toLocaleString()} &nbsp; <strong>Files:</strong> ${Number(t.files||0).toLocaleString()} &nbsp; <strong>Size:</strong> ${fmtBytes(Number(t.bytes||0))} &nbsp; <strong>Index Minutes:</strong> ${fmtMinutes(mins)}</div>`}

 fingerprintProjectHtml=function(p){
  const live=state.fp.live||{},run=live.run||null,job=live.job||null,status=run?.status||p.status||'Pending',phase=job?.phase||run?.status||'Ready',t=live.totals||{},total=Number(run?.files_total||t.files||0),done=Number(run?.files_done||t.done||0),errors=Number(run?.error_count||t.errors||0),processed=done+errors,pct=total?Math.min(100,processed/total*100):0,has=!!live.has_checkpoint,running=['WIP','Running'].includes(status),paused=['Paused','Stopped','Error'].includes(status),canContinue=paused&&has;
  return`<div class="actions" style="margin-bottom:10px"><input class="input" id="fpProjectName" value="${esc(p.project_name)}" style="font-size:18px;font-weight:800;max-width:520px" title="Rename project; Enter or blur saves"><span class="badge ${running?'warn':'good'}">${esc(status)}</span></div>
  <div class="statusGrid"><div class="statusCell"><div class="k">Phase</div><div class="v">${esc(phase)}</div></div><div class="statusCell"><div class="k">Progress</div><div class="v">${phase==='fingerprinting'&&total?Math.round(pct)+'%':'—'}</div>${phase==='fingerprinting'&&total?`<div class="progressTrack"><div class="progressFill" style="width:${pct}%"></div></div>`:''}</div><div class="statusCell"><div class="k">Files</div><div class="v">${total?processed.toLocaleString()+' / '+total.toLocaleString():Number(t.files||0).toLocaleString()}</div></div><div class="statusCell"><div class="k">Folders</div><div class="v">${Number(t.folders_done||0).toLocaleString()} / ${Number(t.folders||0).toLocaleString()}</div></div><div class="statusCell"><div class="k">Size</div><div class="v">${fmtBytes(Number(t.bytes||0))}</div></div><div class="statusCell"><div class="k">Errors</div><div class="v">${errors.toLocaleString()}</div></div></div>
  <div class="actions" style="margin-top:10px"><button class="btn primary" id="fpStart" ${running||paused?'disabled':''}>Start</button><button class="btn" id="fpPause" ${!running?'disabled':''}>Pause</button><button class="btn primary" id="fpContinue" ${!canContinue?'disabled':''}>Continue</button><button class="btn danger" id="fpRestart" ${running?'disabled':''}>Restart</button>${paused&&!has?'<span class="callout warn">No durable checkpoint exists for this older run. Use Restart.</span>':''}</div>
  ${projectTotals(live)}
  <div class="tableWrap" style="max-height:430px"><table class="dataTable"><thead><tr><th>Folder Name</th><th>Item Name</th><th>Size Cumulative</th><th># Files Cumulative</th><th>Start</th><th>End</th><th>Cumulative Minutes</th></tr></thead><tbody>${folderTelemetry(live)}</tbody></table></div>`;
 };

 async function fpAction67(p,action){try{state.fp.running=true;lastWorkerToast='';await api('/projects/'+encodeURIComponent(p.project_token)+'/fingerprint/'+action,{method:'POST',body:'{}'});for(;;){await new Promise(r=>setTimeout(r,350));const live=await api('/projects/'+encodeURIComponent(p.project_token)+'/fingerprint/status');state.fp.live=live;state.selectedProject=live.project||p;const ph=live.job?.phase;if((ph==='indexing'||ph==='fingerprinting')&&ph!==lastWorkerToast){lastWorkerToast=ph;toast(`4 workers running for ${ph} (wait until job has completed)`)}renderFingerprinting();const st=live.run?.status||live.project?.status;if(!['WIP','Running'].includes(st))break}}catch(e){toast(e.message,true)}finally{state.fp.running=false;await refreshProjects();state.selectedProject=state.projects.find(x=>x.project_token===p.project_token)||p;renderFingerprinting()}}
 renderFingerprinting=function(){refreshProjects().then(async()=>{const p=state.selectedProject||state.projects[0]||null;if(p&&!state.selectedProject)state.selectedProject=p;if(p){try{state.fp.live=await api('/projects/'+encodeURIComponent(p.project_token)+'/fingerprint/status')}catch{state.fp.live=null}}page('Fingerprinting','Four-worker indexing establishes the inventory; four-worker fingerprinting then hashes every readable file.',`<div class="card fpLayout"><aside class="projectRail"><div class="paneHeader">Projects</div><div class="projectList">${projectRail()}</div></aside><section class="fpMain">${p?fingerprintProjectHtml(p):'<div class="empty"><strong>No project selected</strong>Create a project first.</div>'}</section></div>`);$$('[data-project]').forEach(x=>x.onclick=()=>{state.selectedProject=state.projects.find(q=>q.project_token===x.dataset.project);state.fp.live=null;renderFingerprinting()});if(!p)return;const name=$('#fpProjectName'),original=p.project_name;const saveName=async()=>{const v=name.value.trim();if(!v||v===p.project_name){name.value=p.project_name;return}try{const updated=await api('/projects/'+encodeURIComponent(p.project_token),{method:'PATCH',body:JSON.stringify({project_name:v})});p.project_name=updated.project_name;await refreshProjects();toast('Project renamed.')}catch(e){name.value=p.project_name;toast(e.message,true)}};name.onblur=saveName;name.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();name.blur()}else if(e.key==='Escape'){name.value=original;name.blur()}};$('#fpStart').onclick=()=>fpAction67(p,'start');$('#fpPause').onclick=async()=>{try{await api('/projects/'+encodeURIComponent(p.project_token)+'/fingerprint/pause',{method:'POST',body:'{}'});toast('Pause requested.')}catch(e){toast(e.message,true)}};$('#fpContinue').onclick=()=>fpAction67(p,'continue');$('#fpRestart').onclick=()=>{if(confirm('Restart from a new indexing queue?'))fpAction67(p,'restart')}})};

 renderConfiguration=function(){page('Configuration','WSL database, health, and troubleshooting log.',`<div class="card panel"><div class="grid2"><div><div class="callout good">Project database: WSL · SQLite</div><div id="cfgInfo" class="muted" style="margin-top:9px">Loading…</div></div><div><label class="label">Log search</label><input class="input" id="logSearch" placeholder="error, fingerprint, path, project…"><div class="actions" style="margin-top:7px"><select class="select" id="logLevel" style="width:auto"><option value="">All levels</option><option>error</option><option>warn</option><option>info</option></select><button class="btn" id="refreshLog">Refresh</button><button class="btn" id="copyLog">Copy visible log</button></div></div></div><div class="tableWrap" style="max-height:520px"><table class="dataTable"><thead><tr><th>Time</th><th>Level</th><th>Component</th><th>Event</th><th>Project / Run</th><th>Path / Detail</th></tr></thead><tbody id="logBody"><tr><td colspan="6">Loading…</td></tr></tbody></table></div></div>`);let visible=[];const loadInfo=async()=>{try{const i=await api('/db/info');$('#cfgInfo').innerHTML=`<strong>Integrity:</strong> ${i.integrity?.ok?'OK':'FAILED'} · <strong>Size:</strong> ${fmtBytes(i.size_bytes||0)}<br><span class="mono">DB: ${esc(i.database_path||'—')}</span><br><span class="mono">Backups: ${esc(i.database_backup_path||'—')}</span><br><span class="mono">Backend: ${esc(i.build||PARALLEL_BUILD)}</span>`}catch(e){$('#cfgInfo').textContent=e.message}};const loadLog=async()=>{try{const q=$('#logSearch').value.trim(),lvl=$('#logLevel').value;visible=await api('/logs?limit=100'+(q?'&q='+encodeURIComponent(q):'')+(lvl?'&level='+encodeURIComponent(lvl):''));$('#logBody').innerHTML=visible.length?visible.map(x=>`<tr><td>${fmtDate(x.created_at)}</td><td>${esc(x.level)}</td><td>${esc(x.component)}</td><td>${esc(x.event)}</td><td class="mono">${esc(x.project_token||'')}<br>${esc(x.run_id||'')}</td><td><div class="mono">${esc(x.path||'')}</div><div>${esc(x.detail||'')}</div></td></tr>`).join(''):'<tr><td colspan="6">No matching log entries.</td></tr>'}catch(e){$('#logBody').innerHTML=`<tr><td colspan="6">${esc(e.message)}</td></tr>`;toast(e.message,true)}};$('#refreshLog').onclick=loadLog;$('#logSearch').onkeydown=e=>{if(e.key==='Enter')loadLog()};$('#logLevel').onchange=loadLog;$('#copyLog').onclick=()=>navigator.clipboard.writeText(visible.map(x=>[x.created_at,x.level,x.component,x.event,x.project_token||'',x.run_id||'',x.path||'',x.detail||''].join('\t')).join('\n')).then(()=>toast('Visible log copied.'));loadInfo();loadLog()};

 document.querySelector('.build').textContent='UI v0.4.1 · '+PARALLEL_BUILD;
 loadDraft67();render();
}
