/* Chatlink Turn 01: bounded shell/repository adapters around the accepted lab. */
var portal=(function(){
 'use strict';
 var db=null,active=null,opened=false,busy=false,writer=false,releaseLock=null,rooms=[],draftTimer=null;
 var view='list';
 var generation=0,pendingWrites=new Set(),failures=[],pages={south:100,north:100},draftVersion=0,jobs=new Set();
 var $=function(id){return document.getElementById(id)};
 function node(tag,text,cls){var e=document.createElement(tag);if(text!=null)e.textContent=text;if(cls)e.className=cls;return e}
 function button(text,fn,cls){var b=node('button',text,cls);b.type='button';b.addEventListener('click',function(){action(fn)});return b}
 function action(fn){return Promise.resolve().then(fn).catch(showError)}
 function showError(err){$('cl-error').textContent='Could not save or open this change. '+(err.message||err)+' Your existing conversations have not been cleared.';$('cl-error').classList.add('show');$('cl-save-state').textContent='Needs attention';}
 function clearError(){$('cl-error').textContent='';$('cl-error').classList.remove('show')}
 function requireWriter(){if(!writer)throw new Error('This conversation manager is open in another tab. Close that tab and reload here.');}
 function track(p,retry){pendingWrites.add(p);$('cl-save-state').textContent='Saving…';p.then(function(){pendingWrites.delete(p);if(!pendingWrites.size&&!failures.length)$('cl-save-state').textContent='Saved';},function(e){pendingWrites.delete(p);if(retry)failures.push(retry);showError(e)});return p}
 function openDB(){return new Promise(function(resolve,reject){var q=indexedDB.open('chatlink-turn01',1);q.onupgradeneeded=function(){var d=q.result;d.createObjectStore('rooms',{keyPath:'id'});d.createObjectStore('state',{keyPath:'key'});};q.onerror=function(){reject(q.error)};q.onblocked=function(){reject(new Error('Close another Chatlink tab to finish opening storage.'))};q.onsuccess=function(){db=q.result;db.onversionchange=function(){teardown('storage changed');db.close();writer=false;freeze();showError(new Error('Storage changed in another tab. Reload this page.'))};resolve()};});}
 function read(store,key){return new Promise(function(resolve,reject){var t=db.transaction(store),q=key===undefined?t.objectStore(store).getAll():t.objectStore(store).get(key);q.onsuccess=function(){resolve(q.result)};q.onerror=function(){reject(q.error)}})}
 // Read/modify/write within one transaction preserves a pending result and a draft save.
 function change(store,key,fn){requireWriter();return new Promise(function(resolve,reject){var result,t=db.transaction(store,'readwrite'),s=t.objectStore(store),q=s.get(key);q.onsuccess=function(){try{result=fn(q.result);if(result===null)s.delete(key);else if(result!==undefined)s.put(result)}catch(e){reject(e);t.abort()}};t.oncomplete=function(){resolve(result)};t.onabort=function(){reject(t.error||new Error('Storage transaction was interrupted'))};t.onerror=function(){};});}
 function state(key,value){return change('state',key,function(){return {key:key,value:value}})}
 function defaults(){return {southLang:'en',northLang:'th',southBg:'#eff6ff',northBg:'#f0fdf4',fontColor:'#0f172a',fontSize:15}}
 function title(r){return r.label||(LANG_NAMES[r.southLang]||r.southLang)+' ↔ '+(LANG_NAMES[r.northLang]||r.northLang)}
 function pair(r){return 'South: '+(LANG_NAMES[r.southLang]||r.southLang)+' · North: '+(LANG_NAMES[r.northLang]||r.northLang)}
 function fresh(fields){return Object.assign(defaults(),fields,{id:crypto.randomUUID(),createdAt:Date.now(),updatedAt:Date.now(),messages:[],drafts:{},scroll:{},revision:1})}
 function setActive(r){active=r;ROOM=r||Object.assign(defaults(),{id:'',label:'Chatlink'});HIST=r?r.messages:[];window.ROOM=ROOM;document.body.classList.toggle('cl-empty-room',!r);$('cl-welcome').hidden=!!r;$('cl-room-title').textContent=r?title(r):'Chatlink';$('cl-room-pair').textContent=r?pair(r):'Device owner · South';applyRoomStyle();sessionTts={south:false,north:false};['south','north'].forEach(function(s){paintTts(s);resetComposition(s);shifted[s]=false;numMode[s]=false;var d=r&&r.drafts&&r.drafts[s];var i=inputEl(s);i.value=d?d.text:'';var a=Math.min(d?d.start:0,i.value.length),b=Math.min(d?d.end:0,i.value.length);i.setSelectionRange(a,b);updateClear(s);});pages={south:100,north:100};renderAll();if(r){['south','north'].forEach(function(s){if(r.scroll&&r.scroll[s]!=null)$('tx-'+s).scrollTop=r.scroll[s]});loadAssets(r);}freeze();}
 function freeze(){document.querySelectorAll('.half').forEach(function(e){e.inert=opened||!active||!writer});$('cl-rail').inert=!opened;$('cl-rail').setAttribute('aria-hidden',String(!opened));}
 function snapshotDraft(){var d={},scroll={};['south','north'].forEach(function(s){var i=inputEl(s);d[s]={text:i.value,start:i.selectionStart,end:i.selectionEnd};scroll[s]=$('tx-'+s).scrollTop;});return {drafts:d,scroll:scroll}}
 function saveDraft(){clearTimeout(draftTimer);if(!active||!writer)return Promise.resolve();var id=active.id,snap=snapshotDraft(),ver=++draftVersion;var write=function(){return change('rooms',id,function(r){if(!r||r.trashedAt)return;r.drafts=snap.drafts;r.scroll=snap.scroll;r.draftVersion=ver;return r})};return track(write(),write)}
 function scheduleDraft(){if(!active||!writer)return;clearTimeout(draftTimer);draftTimer=setTimeout(function(){saveDraft().catch(function(){})},120)}
 async function flush(){await saveDraft();await Promise.all(Array.from(pendingWrites));if(failures.length)throw new Error('A save failed. Open Device settings and Retry saving before switching.');}
 async function open(){if(busy)return;opened=true;document.body.classList.add('cl-open');$('cl-menu').setAttribute('aria-expanded','true');teardown('owner portal');freeze();clearError();await action(flush);await list();$('cl-close').focus();}
 function close(){if(busy)return;opened=false;document.body.classList.remove('cl-open');$('cl-menu').setAttribute('aria-expanded','false');freeze();$('cl-menu').focus();}
 async function select(id,historyMode){requireWriter();if(busy)return;busy=true;try{await flush();teardown('room switch');var r=id?await read('rooms',id):null;if(id&&(!r||r.trashedAt))throw new Error('This conversation is not available. Select another conversation.');await state('activeRoomId',id||null);generation++;setActive(r);if(historyMode!=='none'){var u=new URL(location.href);u.search='';if(id)u.searchParams.set('room',id);history[historyMode==='replace'?'replaceState':'pushState']({},'',u);}clearError();}finally{busy=false;}close();}
 async function refresh(id){var r=await read('rooms',id);if(r&&active&&active.id===id&&!r.trashedAt){active=r;ROOM=r;HIST=r.messages;renderAll();}if(opened&&view==='list')await list();}
 async function list(trash){view=trash?'trash':'list';$('cl-heading').textContent=trash?'Trash':'Conversations';$('cl-body').replaceChildren();rooms=await read('rooms');var visible=rooms.filter(function(r){return !!r.trashedAt===!!trash}).sort(function(a,b){return (b.updatedAt||b.createdAt)-(a.updatedAt||a.createdAt)});var host=$('cl-body');if(!writer)host.appendChild(node('p','This page is read-only while another Chatlink tab is open. Close the other tab and reload.','cl-banner'));
  if(!visible.length){var empty=node('div',null,'cl-empty');empty.append(node('h2',trash?'Nothing in Trash':'A place for every conversation'),node('p',trash?'Removed conversations can be restored here.':'Tap + to start. Choose a language for each side.'));host.appendChild(empty);}
  visible.forEach(function(r){var row=node('div',null,'cl-room'+(active&&r.id===active.id?' active':''));var go=button('',function(){return trash?restore(r):select(r.id)},'cl-room-open');go.dataset.roomId=r.id;go.disabled=!writer;go.append(node('span',title(r),'cl-room-name'),node('span',pair(r)+'\n'+(r.messages||[]).length+' messages','cl-room-sub'));if(active&&r.id===active.id)go.setAttribute('aria-current','true');row.appendChild(go);var edit=button(trash?'Restore':'⋯',function(){return trash?restore(r):editRoom(r)},'cl-icon');edit.setAttribute('aria-label',(trash?'Restore ':'Edit ')+title(r));edit.disabled=!writer;row.appendChild(edit);if(trash){var purge=button('Delete',function(){return purgeRoom(r)},'cl-danger');purge.disabled=!writer;row.appendChild(purge)}host.appendChild(row);});
  if(trash)host.appendChild(button('Back to conversations',function(){return list()}));
 }
 function field(form,label,value,type){var l=node('label',label,'cl-field'),i=node('input');i.type=type||'text';i.value=value||'';l.appendChild(i);form.appendChild(l);return i}
 function language(form,label,value){var l=node('label',label,'cl-field'),s=node('select');Object.keys(LANG_NAMES).forEach(function(k){var o=node('option',LANG_NAMES[k]);o.value=k;s.appendChild(o)});s.value=value;s.setAttribute('aria-label',label);l.appendChild(s);form.appendChild(l);return s}
 async function editRoom(r){view='edit';requireWriter();clearError();$('cl-heading').textContent=r?'Conversation settings':'New conversation';var f=node('form');$('cl-body').replaceChildren(f);var prefs=await read('state','defaults'),seed=r||Object.assign(defaults(),prefs&&prefs.value);var name=field(f,'Conversation name',seed.label||'');name.maxLength=100;name.placeholder='Optional name';var south=language(f,'Device owner · South',seed.southLang),north=language(f,'Partner · North',seed.northLang);if(r&&r.messages.length){south.disabled=north.disabled=true;f.appendChild(node('p','To use another language pair, create a new conversation. This keeps the history in its original languages.','cl-note'));}
  var appearance=node('details');appearance.appendChild(node('summary','Appearance'));f.appendChild(appearance);var sb=field(appearance,'South bubble colour',seed.southBg,'color'),nb=field(appearance,'North bubble colour',seed.northBg,'color'),fc=field(appearance,'Text colour',seed.fontColor,'color'),size=field(appearance,'Text size',seed.fontSize,'number');size.min=12;size.max=24;
  var actions=node('div',null,'cl-actions'),save=node('button',r?'Save changes':'Create conversation','cl-primary');save.type='submit';actions.append(save,button('Cancel',function(){return list()}));if(r)actions.appendChild(button('Move to Trash',function(){return trashRoom(r)},'cl-danger'));f.appendChild(actions);
  f.onsubmit=function(e){e.preventDefault();action(async function(){if(save.disabled)return;save.disabled=true;try{var fields={label:name.value.trim(),southLang:south.value,northLang:north.value,southBg:sb.value,northBg:nb.value,fontColor:fc.value,fontSize:Math.max(12,Math.min(24,Number(size.value)||15))};await flush();var saved=await change('rooms',r?r.id:'',function(old){if(r&&!old)throw new Error('Conversation no longer exists.');if(r){Object.assign(old,fields);old.updatedAt=Date.now();old.revision++;return old;}return fresh(fields)});await state('defaults',{southLang:fields.southLang,northLang:fields.northLang});await select(saved.id); }finally{save.disabled=false;}})};
 }
 async function trashRoom(r){if(!confirm('Move “'+title(r)+'” to Trash? Its history will be retained.'))return;await flush();if(active&&active.id===r.id){teardown('trash room');generation++;setActive(null);await state('activeRoomId',null);history.replaceState({},'',location.pathname);}await change('rooms',r.id,function(x){if(!x)return;x.trashedAt=Date.now();return x});await list();}
 async function restore(r){await change('rooms',r.id,function(x){if(!x)return;delete x.trashedAt;return x});await list()}
 async function purgeRoom(r){if(!confirm('Permanently delete “'+title(r)+'” and all of its messages? This cannot be undone.'))return;await change('rooms',r.id,function(x){return x&&x.trashedAt?null:undefined});await list(true)}
 function validLegacy(r){return r&&typeof r.id==='string'&&r.id.length<200&&LANG_NAMES[r.southLang]&&LANG_NAMES[r.northLang]}
 async function importLegacy(){view='import';requireWriter();var index;try{index=JSON.parse(localStorage.getItem('duck_rooms_index')||'[]')}catch(e){throw new Error('Legacy room list is unreadable. It has been left untouched.')}if(!Array.isArray(index))throw new Error('Legacy room list is not a list.');var orphan=localStorage.getItem('duck_room_lab');if(orphan&&!index.some(function(r){return r.id==='lab'}))index.push({id:'lab',label:'Imported lab',southLang:'en',northLang:'th'});
  var candidates=[],issues=0;index.forEach(function(r){if(!validLegacy(r)){issues++;return;}try{var messages=JSON.parse(localStorage.getItem('duck_room_'+r.id)||'[]');if(!Array.isArray(messages))throw new Error();var clean=messages.map(function(m){if(!m||typeof m.text!=='string'||!['north','south'].includes(m.side)||!LANG_NAMES[m.src]||!LANG_NAMES[m.tgt])throw new Error();return {id:String(m.id||crypto.randomUUID()),side:m.side,text:m.text,src:m.src,tgt:m.tgt,ts:Number(m.ts)||Date.now(),tr:typeof m.tr==='string'?m.tr:null}});var room=Object.assign(defaults(),{id:'legacy:'+r.id,label:String(r.label||''),southLang:r.southLang,northLang:r.northLang,createdAt:Number(r.createdAt)||Date.now(),updatedAt:Number(r.createdAt)||Date.now(),trashedAt:r.trashedAt||null,messages:clean,drafts:{},scroll:{},revision:1});['southBg','northBg','fontColor'].forEach(function(k){if(/^#[0-9a-f]{6}$/i.test(r[k]))room[k]=r[k]});room.fontSize=Math.max(12,Math.min(24,Number(r.fontSize)||15));candidates.push(room)}catch(e){issues++;}});
  $('cl-heading').textContent='Import existing conversations';var host=$('cl-body');host.replaceChildren(node('p',candidates.length+' readable conversations. '+issues+' unreadable records will be skipped and left untouched.','cl-banner'));host.appendChild(node('p','This copies chat-admin/lab histories. Existing imported IDs are skipped. The old applications and their data remain unchanged. An unindexed Lab room is offered as English/Thai; review the language pair before importing.','cl-note'));
  candidates.forEach(function(r){host.appendChild(node('p',title(r)+' · '+pair(r)+' · '+r.messages.length+' messages','cl-note'))});var importButton=button('Import '+candidates.length+' conversations',async function(){requireWriter();importButton.disabled=true;try{await new Promise(function(resolve,reject){var tx=db.transaction('rooms','readwrite'),s=tx.objectStore('rooms');candidates.forEach(function(r){var q=s.get(r.id);q.onsuccess=function(){if(!q.result)s.put(r)}});tx.oncomplete=resolve;tx.onabort=function(){reject(tx.error)};});await list();toastMsg('Conversations imported');}finally{importButton.disabled=false;}},'cl-primary');host.append(importButton,button('Cancel',function(){return settings()}));
 }
 async function settings(){view='settings';clearError();$('cl-heading').textContent='Device settings';var f=node('div');$('cl-body').replaceChildren(f);f.appendChild(node('p','Speech settings stay on this browser. No key is included in conversation data.','cl-note'));var key=field(f,'Deepgram key',dgKey(),'password');key.autocomplete='off';f.appendChild(node('p',dgKey()?'Speech key is configured.':'Add a Deepgram key to enable speech input.','cl-note'));var h=node('label','Keyboard vibration','cl-field'),sel=node('select');['off','light','medium','strong'].forEach(function(v){var o=node('option',v);o.value=v;sel.appendChild(o)});try{sel.value=localStorage.getItem('duck_haptic')||'medium'}catch(e){}h.appendChild(sel);f.appendChild(h);
  f.appendChild(button('Save device settings',function(){requireWriter();if(key.value.trim())localStorage.setItem('tb_dg_key',key.value.trim());localStorage.setItem('duck_haptic',sel.value);toastMsg('Device settings saved');return list()},'cl-primary'));
  f.appendChild(node('p','Conversations are stored in this browser on this device. Clearing browser data removes them.','cl-note'));
  f.appendChild(button('Import from chat-admin / lab',importLegacy));
  f.appendChild(button('Export conversations',async function(){var all=await read('rooms');var data=JSON.stringify({format:'chatlink-turn01',version:1,exportedAt:new Date().toISOString(),rooms:all},null,2);var a=node('a');a.href=URL.createObjectURL(new Blob([data],{type:'application/json'}));a.download='chatlink-conversations.json';a.click();setTimeout(function(){URL.revokeObjectURL(a.href)},1000)}));
  if(failures.length)f.appendChild(button('Retry saving',async function(){var retry=failures.splice(0);for(var write of retry){try{await write()}catch(e){failures.push(write);throw e}}clearError();$('cl-save-state').textContent='Saved';await refresh(active&&active.id)},'cl-primary'));
  f.appendChild(node('p','Build '+CHAT_BUILD+' · Backup restore and multi-tab takeover are deferred from this first candidate.','cl-note'));f.appendChild(button('Back to conversations',function(){return list()}));
 }
 // Capture side/languages/room before normalization; no asynchronous global ROOM use.
 function submit(side,textOverride,keepMic){if(!active||!writer||opened)return;var text=norm(textOverride!=null?textOverride:inputEl(side).value);if(!text)return;var ctx={roomId:active.id,side:side,src:langOf(side),tgt:langOf(otherSide(side)),gen:generation},id=crypto.randomUUID(),ts=Date.now();clearDraft(side);if(!keepMic)teardown('sent');scheduleDraft();
  // Persist the original before any remote work; a reload cannot lose submitted text.
  var entry={id:id,side:side,original:text,ownerLang:ctx.src,text:text,src:ctx.src,tgt:ctx.tgt,ts:ts,tr:null,status:'pending'};
  var write=function(){return change('rooms',ctx.roomId,function(r){if(!r||r.trashedAt)return;if(!r.messages.some(function(m){return m.id===id})){r.messages.push(entry);r.messages.sort(function(a,b){return a.ts-b.ts});r.updatedAt=ts;r.revision++;}return r})};
  var task=track(write(),write).then(function(r){if(r)return processMessage(ctx,id)});task.catch(showError);return task;
 }
 async function processMessage(ctx,id){var job=ctx.roomId+'|'+id;if(jobs.has(job))return;jobs.add(job);
  try{var room=await read('rooms',ctx.roomId),entry=room&&room.messages.find(function(m){return m.id===id});if(!entry||room.trashedAt)return;await refresh(ctx.roomId);
   var normalized=await normalizeOutgoing({myLang:ctx.src,theirLang:ctx.tgt,myLangMode:'fixed'},entry.original||entry.text);
   var saveNormalized=function(){return change('rooms',ctx.roomId,function(r){if(!r||r.trashedAt)return;var m=r.messages.find(function(m){return m.id===id});if(!m)return;m.text=normalized.text;m.src=normalized.lang;m.status='pending';return r})};
   if(!await track(saveNormalized(),saveNormalized))return;await refresh(ctx.roomId);
   var tr=normalized.lang===ctx.tgt?{ok:true,text:normalized.text}:await translateWithRetry(normalized.text,normalized.lang,ctx.tgt,2);
   var update=function(){return change('rooms',ctx.roomId,function(r){if(!r||r.trashedAt)return;var m=r.messages.find(function(m){return m.id===id});if(!m)return;m.tr=tr&&tr.ok?norm(tr.text):null;m.status=m.tr?'complete':'failed';return r})};
   if(!await track(update(),update))return;await refresh(ctx.roomId);if(active&&active.id===ctx.roomId&&generation===ctx.gen&&!opened&&tr.ok)speakIfOn(ctx.side,norm(tr.text),ctx.tgt);
  }finally{jobs.delete(job);if(active&&active.id===ctx.roomId)renderAll();}
 }
 function retryMessage(id){if(!visible())return;var m=HIST.find(function(x){return x.id===id});if(!m)return;return action(function(){return processMessage({roomId:active.id,side:m.side,src:m.ownerLang||m.src,tgt:m.tgt,gen:generation},id)})}
 function decorateMessage(e,hdr){if(!e.status||e.status==='complete')return;var busy=jobs.has((active&&active.id)+'|'+e.id);var b=button(busy?'Translating…':'Retry translation',function(){return retryMessage(e.id)},'cl-message-retry');b.disabled=busy;hdr.appendChild(b)}
 function deleteMessage(id){if(!active||!writer||opened)return;var rid=active.id;action(async function(){await track(change('rooms',rid,function(r){if(!r)return;r.messages=r.messages.filter(function(m){return m.id!==id});return r}));await refresh(rid)});}
 function loadAssets(r){Array.from(new Set([r.southLang,r.northLang])).forEach(function(lang){if(getDict(lang)&&getBigram(lang))return;var base='https://raw.githubusercontent.com/acmeproducts/stuff/main/dict/';fetch(base+lang+'.json').then(function(x){if(!x.ok)throw new Error();return x.json()}).then(function(words){if(!Array.isArray(words))return;dictCache[lang]=words;lmMemo={};try{localStorage.setItem('duck_dict_'+lang,JSON.stringify(words))}catch(e){}if(INPUT.mode==='kb')updateAutocomplete(INPUT.owner)}).catch(function(){});fetch(base+'bigram-'+lang+'.json').then(function(x){if(!x.ok)throw new Error();return x.json()}).then(function(bg){bgCache[lang]=bg;lmMemo={};if(INPUT.mode==='kb')updatePredictions(INPUT.owner)}).catch(function(){});});}
 function older(side){pages[side]+=100;renderPanel(side)}
 function visible(){return !!active&&writer&&!opened}
 function guardMicrophoneStarts(){['south','north'].forEach(function(side){var p=mic[side],start=p.start,stop=p.hardStop,serial=Promise.resolve(),epoch=0;
  p.hardStop=function(){epoch++;stop();};
  p.start=function(){var request=++epoch,room=active&&active.id,gen=generation;var current=function(){return epoch===request&&active&&active.id===room&&generation===gen&&visible()&&INPUT.owner===side&&INPUT.mode==='mic'};
   var task=serial.then(function(){if(!current())return;return start().then(function(){if(!current())stop();},function(e){if(current())throw e;stop();});});serial=task.catch(function(){});return task;
  };
 });}
 async function start(){document.body.classList.add('cl-empty-room');$('cl-menu').onclick=function(){action(opened?close:open)};$('cl-close').onclick=close;$('cl-cover').onclick=close;$('cl-new').onclick=function(){action(function(){return editRoom(null)})};$('cl-settings').onclick=function(){action(settings)};$('cl-trash').onclick=function(){action(function(){return list(true)})};
  guardMicrophoneStarts();
  document.addEventListener('keydown',function(e){if(!opened)return;if(e.key==='Escape'){e.preventDefault();close()}if(e.key==='Tab'){var list=Array.from($('cl-rail').querySelectorAll('button,input,select')).filter(function(e){return !e.disabled&&e.getClientRects().length});if(!list.length)return;var i=list.indexOf(document.activeElement),next=e.shiftKey?i-1:i+1;if(next<0)next=list.length-1;if(next>=list.length)next=0;e.preventDefault();list[next].focus();}});
  ['south','north'].forEach(function(s){inputEl(s).addEventListener('input',scheduleDraft);inputEl(s).addEventListener('select',scheduleDraft);$('tx-'+s).addEventListener('scroll',scheduleDraft,{passive:true});});
  window.addEventListener('popstate',function(){action(function(){return select(new URL(location.href).searchParams.get('room'),'none')})});document.addEventListener('visibilitychange',function(){if(document.hidden){saveDraft().catch(showError);teardown('hidden')}});window.addEventListener('pagehide',function(){saveDraft().catch(function(){});teardown('pagehide')});
  if(!navigator.locks){showError(new Error('This browser needs Web Locks support for safe conversation storage. Please use a current browser.'));freeze();return;}
  await new Promise(function(resolve){navigator.locks.request('chatlink-turn01-writer',{ifAvailable:true},async function(lock){writer=!!lock;resolve();if(lock)await new Promise(function(r){releaseLock=r})}).catch(function(e){showError(e);resolve()});});
  await openDB();rooms=await read('rooms');var last=await read('state','activeRoomId'),id=new URL(location.href).searchParams.get('room')||(last&&last.value),r=id?await read('rooms',id):null;setActive(r&&!r.trashedAt?r:null);if(id&&!active)showError(new Error('That conversation is unavailable. Choose one from the menu.'));if(!active||!writer)await open();document.documentElement.dataset.chatlinkReady='true';
 }
 return {start:start,open:open,select:select,submit:submit,scheduleDraft:scheduleDraft,deleteMessage:deleteMessage,decorateMessage:decorateMessage,older:older,pageSize:function(s){return pages[s]},visible:visible,flush:flush};
})();
