const fs=require('fs'),path=require('path'),assert=require('assert/strict'),http=require('http'),{chromium}=require('playwright');
const html=()=>fs.readFileSync(path.join(__dirname,'../../chat-test.html'),'utf8');
function wav(){const n=16000*3,b=Buffer.alloc(44+n*2);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(16000,24);b.writeUInt32LE(32000,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(n*2,40);for(let i=0;i<n;i++)b.writeInt16LE(Math.round(5000*Math.sin(2*Math.PI*320*i/16000)),44+i*2);return b;}
(async()=>{const server=http.createServer((req,res)=>{if(req.url==='/'){res.setHeader('Content-Type','text/html');res.end(html());}else{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream','--autoplay-policy=no-user-gesture-required']});
try{for(const side of ['north','south']){const context=await browser.newContext({permissions:['microphone'],viewport:{width:390,height:844}}),page=await context.newPage(),errors=[],sockets=[];let pcm=0,requests=0;page.on('pageerror',e=>errors.push(e.message));await page.routeWebSocket('wss://api.deepgram.com/**',ws=>{sockets.push(ws);ws.onMessage(m=>{if(typeof m!=='string')pcm+=m.byteLength;});});await page.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin===url)return r.continue();if(u.pathname==='/v1/speak'){requests++;return r.fulfill({contentType:'audio/wav',body:wav()});}if(u.hostname==='api.mymemory.translated.net')return r.fulfill({json:{responseStatus:200,responseData:{translatedText:'hello friend'}}});if(u.pathname.includes('/dict/'))return r.fulfill({json:[]});return r.abort();});
await page.addInitScript(()=>{localStorage.setItem('tb_dg_key','test-key');window.addEventListener('DOMContentLoaded',()=>window.setFtForTest({detect:()=> 'en'}));window.speechSynthesis.speak=()=>{throw new Error('Native TTS must not be used')};});
await page.goto(url);await page.waitForFunction(()=>document.documentElement.dataset.chatlinkReady==='true');await page.locator('#cl-new').click();await page.getByLabel('Conversation name',{exact:true}).fill('Reference test');await page.getByLabel('Partner · North',{exact:true}).selectOption('en');await page.getByRole('button',{name:'Create conversation',exact:true}).click();await page.waitForFunction(()=>!document.body.classList.contains('cl-open'));
await page.locator('#strip-'+side+' .micbtn').click();await page.waitForFunction(s=>mic[s].active,side);await page.waitForFunction(()=>audioReference.state().micSides.length===1);const listener=side==='north'?'south':'north';await page.locator('#strip-'+listener+' .tts').click();sockets[0].send(JSON.stringify({is_final:true,channel:{alternatives:[{transcript:'hello friend'}]}}));
await page.waitForFunction(()=>audioReference.state().playing);const before=pcm;await page.waitForTimeout(1200);assert.ok(pcm>before,'Microphone PCM continues during TTS');assert.equal(await page.evaluate(s=>mic[s].on,side),true);assert.ok(requests>0);const state=await page.evaluate(()=>audioReference.state());assert.ok(state.metrics.referenceRms>0,'Playback reference reaches worklet');assert.ok(state.metrics.micRms>0,'Mic reaches worklet');assert.equal(state.bypass,false);
await page.locator('#aec-config-toggle').click();assert.ok((await page.locator('#aec-log').textContent()).includes('STT final'));await page.screenshot({path:path.join(__dirname,'reference-'+side+'.png')});await page.locator('#aec-mode').selectOption('bypass');assert.equal(await page.evaluate(()=>audioReference.state().bypass),true);await page.locator('#aec-mode').selectOption('on');await page.locator('#aec-config-toggle').click();await page.locator('#cl-menu').click();assert.equal(await page.evaluate(()=>audioReference.state().playing),false);assert.equal(await page.evaluate(()=>audioReference.state().queued),0);assert.deepEqual(errors,[]);console.log('PASS '+side+': STT final → TTS reference playback, uninterrupted PCM, metrics, diagnostics, bypass and teardown');await context.close();}}
finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1});
