/* All conversation processing stays in the accepted Chatlink engine. This adapter
   replaces only the TTS source and the microphone-to-STT audio node. */
(function(){
 let ctx,reference,module,ready,epoch=0,queue=[],running=false,source,abort,bypass=false,error='';
 const graphs=new Map(),lines=[],sentFrames={};let metrics={};
 function log(event,data={}){lines.push(JSON.stringify({time:new Date().toISOString(),event,...data}));if(lines.length>400)lines.shift();const el=document.getElementById('aec-log');if(el){el.textContent=lines.join('\n');el.scrollTop=el.scrollHeight;}paint();}
 function paint(){const el=document.getElementById('aec-status');if(el)el.textContent=error||((source?'Speaking + listening':running?'Preparing speech':'Ready')+' · '+queue.length+' queued');}
 function context(){if(!ctx){ctx=new(window.AudioContext||window.webkitAudioContext)({sampleRate:16000});reference=ctx.createGain();reference.gain.value=1;}return ctx;}
 async function prepare(){const c=context();await c.resume();if(c.sampleRate!==16000)throw new Error('This browser did not provide 16 kHz audio. Reference test unavailable.');if(!ready)ready=(async()=>{const bytes=Uint8Array.from(atob(AEC_WASM_BASE64),x=>x.charCodeAt(0));module=await WebAssembly.compile(bytes);const url=URL.createObjectURL(new Blob([AEC_WORKLET_SOURCE],{type:'application/javascript'}));try{await c.audioWorklet.addModule(url);}finally{URL.revokeObjectURL(url);}log('AEC ready',{engine:'SpeexDSP 1.2.1',sampleRate:c.sampleRate,tailMs:256});})();await ready;return c;}
 function detach(side){const g=graphs.get(side);if(!g)return;g.raw.disconnect();g.node.disconnect();reference.disconnect(g.node);g.node.port.onmessage=null;graphs.delete(side);log('STT audio detached',{side});}
 function attach(c,stream,side){if(!module||c!==ctx)throw new Error('AEC is not initialized');detach(side);const raw=c.createMediaStreamSource(stream),node=new AudioWorkletNode(c,'chat-reference-aec',{numberOfInputs:2,numberOfOutputs:1,outputChannelCount:[1],channelCount:1,channelCountMode:'explicit',processorOptions:{module}});raw.connect(node,0,0);reference.connect(node,0,1);node.port.postMessage({type:'bypass',value:bypass});node.port.onmessage=e=>{metrics=e.data;log('AEC levels',{side,...e.data});};node.onprocessorerror=()=>{cancel('AEC processor failure');error='AEC failed. Restart microphone before using speech playback.';log('AEC error',{side});};graphs.set(side,{raw,node});log('STT reference route connected',{side,settings:stream.getAudioTracks()[0].getSettings()});return node;}
 function cancel(reason){epoch++;queue=[];abort?.abort();abort=null;if(source){source.onended=null;try{source.stop();}catch(_){}source.disconnect();source=null;}running=false;log('TTS cancelled',{reason});}
 async function drain(){if(running||!queue.length||document.hidden)return;running=true;const token=epoch,item=queue.shift();paint();try{
  if(item.lang!=='en')throw new Error('Reference TTS currently supports English output only. Translation text remains available.');
  const key=dgKey();if(!key)throw new Error('Add your Deepgram key in Device settings for reference TTS.');
  const c=await prepare();if(token!==epoch)return;
  const request=new AbortController();abort=request;const timeout=setTimeout(()=>request.abort(),20000);
  log('TTS request',{lang:item.lang,text:item.text});let response;
  try{response=await fetch('https://api.deepgram.com/v1/speak?model=aura-2-thalia-en&encoding=linear16&container=wav&sample_rate=16000',{method:'POST',headers:{'Authorization':'Token '+key,'Content-Type':'application/json'},body:JSON.stringify({text:item.text}),signal:request.signal});if(!response.ok)throw new Error('TTS request failed: HTTP '+response.status);var bytes=await response.arrayBuffer();}finally{clearTimeout(timeout);if(abort===request)abort=null;}
  if(token!==epoch)return;const buffer=await c.decodeAudioData(bytes);if(token!==epoch)return;
  const player=c.createBufferSource();player.buffer=buffer;player.connect(reference);player.connect(c.destination);source=player;
  log('TTS playback started',{lang:item.lang,text:item.text,duration:buffer.duration,micSides:[...graphs.keys()]});
  player.onended=()=>{if(token!==epoch)return;player.disconnect();source=null;running=false;log('TTS playback ended');drain();};player.start();
 }catch(e){if(token!==epoch)return;running=false;error=e.name==='AbortError'?'TTS request timed out':e.message;log('TTS error',{message:error});drain();}}
 function enqueue(text,lang){text=norm(text);if(!text)return;if(queue.length>=8){error='Speech queue full. Replay the message when ready.';log('TTS queue full');return;}error='';queue.push({text,lang});log('TTS queued',{lang,text});drain();}
 function setBypass(value){bypass=!!value;graphs.forEach(g=>g.node.port.postMessage({type:'bypass',value:bypass}));log('AEC mode',{bypass});}
 window.audioReference={prepare,context,attach,detach,enqueue,cancel,log,setBypass,sent(side,n){sentFrames[side]=(sentFrames[side]||0)+n;if(sentFrames[side]>=16000){log('STT PCM sent',{side,samples:sentFrames[side],duringTts:!!source});sentFrames[side]=0;}},state:()=>({queued:queue.length,running,playing:!!source,micSides:[...graphs.keys()],bypass,error,metrics}),logs:()=>lines.join('\n')};
 // Initialize/resume inside a user gesture, before asynchronous translation completes.
 document.addEventListener('pointerdown',()=>{try{context().resume().catch(()=>{});}catch(_){}},{capture:true});
 document.addEventListener('visibilitychange',()=>{if(document.hidden)cancel('hidden');});
 window.addEventListener('pagehide',()=>{cancel('pagehide');ctx?.close();});
 document.addEventListener('DOMContentLoaded',()=>{
  const toggle=document.createElement('button');toggle.id='aec-config-toggle';toggle.type='button';toggle.textContent='Audio test · r3';toggle.style.cssText='position:fixed;bottom:12px;right:8px;z-index:1000';toggle.setAttribute('aria-expanded','false');
  const panel=document.createElement('section');panel.id='aec-config';panel.hidden=true;panel.style.cssText='position:fixed;bottom:56px;left:8px;right:8px;max-height:40vh;overflow:auto;z-index:1001;background:#fff;color:#163c3c;border:1px solid #2e8b8b;border-radius:10px;padding:12px;font:13px system-ui';
  panel.innerHTML='<strong>Reference-audio echo cancellation · experimental</strong><p>Mic stays live during playback. English spoken output uses your Deepgram key; other languages retain text translation. No browser-voice fallback.</p><label>Processing <select id="aec-mode"><option value="on">Reference AEC on</option><option value="bypass">Bypass AEC (comparison)</option></select></label><p id="aec-status" role="status"></p><details open><summary>STT / TTS debug log</summary><p>Local log includes conversation text. No audio recordings.</p><button id="aec-copy" type="button">Copy log</button> <button id="aec-download" type="button">Download log</button> <button id="aec-clear" type="button">Clear log</button><pre id="aec-log" style="max-height:130px;overflow:auto;white-space:pre-wrap;font-size:11px"></pre></details>';
  document.body.append(toggle,panel);toggle.onclick=()=>{panel.hidden=!panel.hidden;toggle.setAttribute('aria-expanded',String(!panel.hidden));};panel.querySelector('#aec-mode').onchange=e=>setBypass(e.target.value==='bypass');panel.querySelector('#aec-copy').onclick=()=>navigator.clipboard.writeText(lines.join('\n')).catch(()=>{error='Copy unavailable; use Download log.';paint();});panel.querySelector('#aec-download').onclick=()=>{const a=document.createElement('a'),url=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/plain'}));a.href=url;a.download='chat-test-aec-log.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};panel.querySelector('#aec-clear').onclick=()=>{lines.length=0;log('Log cleared');};log('Test loaded',{build:'chat-test-reference-r3'});
 });
})();
