const fs=require('fs'),assert=require('assert/strict');const bytes=Buffer.from(fs.readFileSync(__dirname+'/aec3.wasm.b64','utf8').trim(),'base64');const moduleAEC=new WebAssembly.Module(bytes);console.log('Imports',WebAssembly.Module.imports(moduleAEC));
function create(){const e=new WebAssembly.Instance(moduleAEC,{wasi_snapshot_preview1:{fd_write:()=>0,fd_close:()=>0,fd_seek:()=>0,proc_exit:()=>{throw Error('exit')}},env:{emscripten_notify_memory_growth(){}}}).exports;e._initialize?.();e.aec_init();e.aec_process();return {e,m:new Int16Array(e.memory.buffer,e.aec_mic(),160),r:new Int16Array(e.memory.buffer,e.aec_reference(),160),o:new Int16Array(e.memory.buffer,e.aec_output(),160)};}
function dump(samples,name){const b=Buffer.alloc(44+samples.length*2);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(16000,24);b.writeUInt32LE(32000,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(samples.length*2,40);samples.forEach((x,i)=>b.writeInt16LE(Math.max(-32768,Math.min(32767,Math.round(x*32768))),44+i*2));fs.writeFileSync(require('path').join(process.env.AEC_DUMP,name+'.wav'),b);}
let seed=7;const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296*2-1};
const N=16000*20,ref=new Float32Array(N),near=new Float32Array(N);let lp=0;
for(let i=0;i<N;i++){const t=i/16000;lp=.7*lp+.3*random();ref[i]=.23*lp*(.4+.6*Math.sin(t*5)**2)+.08*Math.sin(t*2*Math.PI*(170+20*Math.sin(t*3)));near[i]=i>=16000*10&&i<16000*18?.1*Math.sin(t*2*Math.PI*313)+.07*Math.sin(t*2*Math.PI*697)+.03*random():0;}
if(process.argv[2]&&process.argv[3]){function readWav(file){const b=fs.readFileSync(file);for(let p=12;p+8<=b.length;){const n=b.readUInt32LE(p+4);if(b.toString('ascii',p,p+4)==='data'){const out=new Float32Array(n/2);for(let i=0;i<out.length;i++)out[i]=b.readInt16LE(p+8+i*2)/32768;return out;}p+=8+n+(n%2);}throw Error('Missing WAV data');}const r=readWav(process.argv[2]),v=readWav(process.argv[3]);for(let i=0;i<N;i++){ref[i]=(r[i%r.length]||0)*.6;near[i]=i>=160000&&i<288000?(v[i-160000]||0)*.6:0;}}
if(process.env.AEC_REFERENCE_GAIN){for(let i=0;i<N;i++)ref[i]*=Number(process.env.AEC_REFERENCE_GAIN);}
const baseline=new Float32Array(N),b=create();for(let off=0;off<N;off+=160){for(let j=0;j<160;j++)b.m[j]=Math.round((near[off+j]||0)*32768);assert.equal(b.e.aec_process(),1);for(let j=0;j<160;j++)baseline[off+j]=b.o[j]/32768;}
const failures=[];const check=(ok,msg)=>{if(!ok)failures.push(msg)};const results=[];
for(const delayMs of [20,80,160]){const {e,m,r,o}=create(),delay=delayMs*16;let echoIn=0,echoOut=0,nearEnergy=0,error=0,cross=0,outEnergy=0,baselineError=0,baselineEnergy=0;const capture=new Float32Array(N);e.aec_delay(delayMs);const start=performance.now();
for(let off=0;off<N;off+=160){for(let j=0;j<160;j++){const i=off+j;const echo=(ref[i-delay]||0)*.55+(ref[i-delay-190]||0)*.2;r[j]=Math.round((ref[i]||0)*32768);m[j]=Math.round((echo+(near[i]||0))*32768);}e.aec_process();for(let j=0;j<160;j++){const i=off+j,x=o[j]/32768;capture[i]=x;if(i>16000*7&&i<16000*10){echoIn+=(m[j]/32768)**2;echoOut+=x*x;}if(i>16000*11&&i<16000*17){baselineEnergy+=baseline[i]**2;baselineError+=(x-baseline[i])**2;nearEnergy+=near[i-160]**2;error+=(x-near[i-160])**2;cross+=x*near[i-160];outEnergy+=x*x;}}}
const erle=10*Math.log10(echoIn/echoOut),snr=10*Math.log10(nearEnergy/error),corr=cross/Math.sqrt(nearEnergy*outEnergy),elapsed=performance.now()-start;results.push({delayMs,echoReductionDb:+erle.toFixed(2),overlapSnrDb:+snr.toFixed(2),overlapVsVoiceOnlySnrDb:+(10*Math.log10(baselineEnergy/baselineError)).toFixed(2),voiceCorrelation:+corr.toFixed(4),processingMs:+elapsed.toFixed(1)});console.log(results.at(-1));check(erle>20,'Echo reduction >20 dB at '+delayMs);check(10*Math.log10(baselineEnergy/baselineError)>20,'Voice-only SNR >20 dB at '+delayMs);/* Raw correlation is reported, not gated: the canceller has a high-pass response. */if(process.env.AEC_DUMP){dump(capture,'clean-'+delayMs);dump(baseline,'baseline');}}
console.log(JSON.stringify(results,null,2));fs.writeFileSync(__dirname+(process.argv[2]?'/voice-results.json':'/dsp-results.json'),JSON.stringify({fixture:process.argv[2]?'Generated speech with simulated room echo; not a physical-room or STT accuracy measurement':'Deterministic synthetic signal; not a physical-room or STT accuracy measurement',results},null,2));

assert.deepEqual(failures,[]);
