#!/usr/bin/env python3
from pathlib import Path
import re

p=Path('market-view-ui-v2.html')
s=p.read_text(encoding='utf-8')
MARK='UI semantics v2.2'
if MARK in s:
    print('Market Navigator UI v2.2 already current')
    raise SystemExit(0)
if 'UI semantics v2.1' not in s:
    raise SystemExit('Expected canonical UI semantics v2.1 baseline')

def rep(old,new,label,count=1):
    global s
    if old not in s:
        raise SystemExit(f'UI v2.2 migration anchor missing: {label}')
    s=s.replace(old,new,count)

def rx(pattern,repl,label):
    global s
    s2,n=re.subn(pattern,repl,s,count=1,flags=re.S)
    if n!=1: raise SystemExit(f'UI v2.2 regex anchor failed: {label} ({n})')
    s=s2

# More vertical chart geometry; keep one coherent viewport rather than ultra-wide compressed strips.
rep('.now{height:100%;display:grid;grid-template-rows:minmax(0,1.18fr) minmax(0,.82fr);gap:8px}',
    '.now{height:100%;max-width:1380px;margin:0 auto;display:grid;grid-template-rows:minmax(0,1.05fr) minmax(0,.95fr);gap:10px}', 'now geometry')
rep('.detail{height:100%;display:grid;grid-template-rows:auto minmax(0,1fr);gap:8px}',
    '.detail{height:100%;max-width:1380px;margin:0 auto;display:grid;grid-template-rows:auto minmax(0,1fr);gap:10px}', 'detail geometry')
rep('.macro{height:100%;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}',
    '.macro{height:100%;max-width:1380px;margin:0 auto;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}', 'macro geometry')

# Expanded macro labels.
rep("thirtyYear:'U.S. 30-Year Yield'", "thirtyYear:'U.S. 30-Year Yield',coreCpi:'Core CPI Inflation',pce:'PCE Inflation',corePce:'Core PCE Inflation',curve10y2y:'10Y–2Y Treasury Curve',realTenYear:'10Y Real Yield',breakeven10y:'10Y Breakeven Inflation',hySpread:'High-Yield Credit Spread',nfci:'Financial Conditions (NFCI)',initialClaims:'Initial Claims',payrolls:'Nonfarm Payrolls',industrialProduction:'Industrial Production',retailSales:'Retail Sales',realGdp:'Real GDP'", 'expanded labels')

# State now includes the persisted model.
rep("const S={manifest:null,indexes:{},series:{},news:[],range:'m3'", "const S={manifest:null,model:null,indexes:{},series:{},news:[],range:'m3'", 'model state')

# T0-relative weighted physics. UI reads persisted raw series + model.json; it does not invent data.
anchor="function tooltipFor(c)"
insert="""function valueAt(obs,t){if(!obs?.length)return null;let lo=0,hi=obs.length-1,b=-1;while(lo<=hi){const m=(lo+hi)>>1;if(obs[m].t<=t){b=m;lo=m+1}else hi=m-1}return b>=0?obs[b].v:null}function clamp1(v){return Math.max(-1,Math.min(1,v))}function modelIndex(id){return S.model?.indexes?.[id]||null}function indexChildren(id){return id==='regime'?['risk','growth','macro']:(modelIndex(id)?.components||[]).map(x=>x.id)}function componentCfg(parent,id){return (modelIndex(parent)?.components||[]).find(x=>x.id===id)||null}function t0ForRange(k){const a=S.series.spy?.observations||[];if(!a.length)return null;const end=a.at(-1).t,start=rangeStart(k,end);if(start==null)return a[0].t;const hit=a.find(x=>x.t>=start);return hit?.t??a[0].t}function componentEffect(cfg,t,t0){const obs=S.series[cfg.id]?.observations||[],a=valueAt(obs,t0),b=valueAt(obs,t);if(a==null||b==null)return null;const raw=cfg.mode==='pct'&&a?(b/a-1)*100:b-a;return{id:cfg.id,weight:cfg.weight,raw,effect:clamp1(cfg.direction*raw/cfg.scale),valueT0:a,value:b,role:cfg.role}}function indexPoint(id,t,t0){if(id==='regime'){const vals=['risk','growth','macro'].map(k=>indexPoint(k,t,t0)).filter(Boolean);if(vals.length!==3)return null;return{t,v:vals.reduce((a,b)=>a+b.v,0)/3,children:vals.map(x=>x.v),coverage:1}}const m=modelIndex(id);if(!m)return null;const parts=m.components.map(c=>componentEffect(c,t,t0)).filter(Boolean),coverage=parts.reduce((a,b)=>a+b.weight,0);if(coverage<.60)return null;const weighted=parts.reduce((a,b)=>a+b.effect*b.weight,0)/coverage;return{t,v:Math.max(0,Math.min(100,50+40*weighted)),coverage,components:parts}}function dynamicIndexSeries(id,k=S.range){const anchor=S.series.spy?.observations||[];if(!anchor.length)return[];const t0=t0ForRange(k);if(t0==null)return[];return anchor.filter(p=>p.t>=t0).map(p=>indexPoint(id,p.t,t0)).filter(Boolean)}function relativeContribution(parent,id,k=S.range){const cfg=componentCfg(parent,id);if(!cfg)return null;const a=S.series.spy?.observations||[],t0=t0ForRange(k),t=a.at(-1)?.t;if(t0==null||t==null)return null;const e=componentEffect(cfg,t,t0);if(!e)return null;return{...e,weighted:e.effect*cfg.weight,label:e.effect>.15?'Favorable':e.effect<-.15?'Unfavorable':'Neutral'}}"""
rep(anchor,insert+anchor,'T0 physics')

# Strong visible neutral band + fixed full 0–100 grid.
rx(r"function drawIndex\(c,a,color='#69b4ff'\)\{.*?\nfunction drawComponent", """function drawIndex(c,a,color='#69b4ff'){const draw=()=>{const{x,w,h}=canvasCtx(c),p={l:42,r:14,t:22,b:32};x.clearRect(0,0,w,h);const host=c.parentElement;host.querySelectorAll('.endpoint').forEach(e=>e.remove());const tip=tooltipFor(c);if(a.length<2){x.fillStyle='#91a2b9';x.fillText('Insufficient history',8,20);return}const t0=a[0].t,t1=a.at(-1).t,yv=v=>p.t+(100-v)/100*(h-p.t-p.b);x.fillStyle='rgba(240,182,78,.16)';x.fillRect(p.l,yv(58),w-p.l-p.r,yv(42)-yv(58));x.fillStyle='#d9b868';x.font='bold 9px system-ui';x.fillText('NEUTRAL 42–58',p.l+6,yv(58)+12);x.font='9px system-ui';[0,25,42,50,58,75,100].forEach(v=>{const y=yv(v);x.strokeStyle=(v===42||v===58)?'#8a7440':v===50?'#65758a':'#263752';x.beginPath();x.moveTo(p.l,y);x.lineTo(w-p.r,y);x.stroke();x.fillStyle='#91a2b9';x.fillText(v,5,y+3)});x.strokeStyle=color;x.lineWidth=2.4;x.beginPath();a.forEach((q,i)=>{const xx=p.l+(q.t-t0)/Math.max(1,t1-t0)*(w-p.l-p.r),yy=yv(q.v);i?x.lineTo(xx,yy):x.moveTo(xx,yy)});x.stroke();drawXAxis(x,w,h,p,a);const coord=q=>({x:p.l+(q.t-t0)/Math.max(1,t1-t0)*(w-p.l-p.r),y:yv(q.v)}),st=coord(a[0]),en=coord(a.at(-1));x.fillStyle=color;[st,en].forEach(q=>{x.beginPath();x.arc(q.x,q.y,3.5,0,Math.PI*2);x.fill()});endpointLabel(host,'start',a[0].v.toFixed(0),st.x,st.y);endpointLabel(host,'end',a.at(-1).v.toFixed(0),en.x,en.y);const hi=c._mn?.hover;if(Number.isInteger(hi)){const q=a[hi],z=coord(q);x.strokeStyle='#dce8f7aa';x.lineWidth=1;x.beginPath();x.moveTo(z.x,p.t);x.lineTo(z.x,h-p.b);x.stroke();x.fillStyle='#edf4ff';x.beginPath();x.arc(z.x,z.y,4,0,Math.PI*2);x.fill();tip.textContent=`${dateLabel(q.t)} · ${q.v.toFixed(1)}/100`;tip.style.display='block';tip.style.left=Math.min(w-tip.offsetWidth-4,Math.max(4,z.x+8))+'px';tip.style.top=Math.max(4,z.y-28)+'px'}else tip.style.display='none';c._mn={...(c._mn||{}),data:a,pad:p,draw}};c._mn={data:a,pad:{l:42,r:14,t:22,b:32},hover:null,draw};bindChart(c);draw()}
function drawComponent""", 'index renderer')

# Component charts use delta for yields/rates/spreads and percent for return-like series.
rx(r"function drawComponent\(c,id,a\)\{.*?\nfunction sigHTML", """function drawComponent(c,id,a,cfg=null){const draw=()=>{const{x,w,h}=canvasCtx(c),p={l:48,r:14,t:22,b:32};x.clearRect(0,0,w,h);const host=c.parentElement;host.querySelectorAll('.endpoint').forEach(e=>e.remove());const tip=tooltipFor(c);if(a.length<2){x.fillStyle='#91a2b9';x.fillText('Insufficient history',8,24);return}const base=a[0].v,isDelta=cfg?.mode==='delta',series=a.map(q=>({t:q.t,v:isDelta?q.v-base:(q.v/base-1)*100,raw:q.v})),mx=Math.max(isDelta?.1:1,...series.map(q=>Math.abs(q.v)))*1.15,t0=series[0].t,t1=series.at(-1).t,unit=isDelta?(S.series[id]?.unit==='percent'?' pp':' Δ'):'%';x.font='9px system-ui';[-mx,0,mx].forEach(v=>{const y=p.t+(mx-v)/(mx*2)*(h-p.t-p.b);x.strokeStyle=v===0?'#65758a':'#263752';x.beginPath();x.moveTo(p.l,y);x.lineTo(w-p.r,y);x.stroke();x.fillStyle='#91a2b9';x.fillText((v>0?'+':'')+v.toFixed(isDelta?2:1)+unit,3,y+3)});x.strokeStyle='#69b4ff';x.lineWidth=2.4;x.beginPath();series.forEach((q,i)=>{const xx=p.l+(q.t-t0)/Math.max(1,t1-t0)*(w-p.l-p.r),yy=p.t+(mx-q.v)/(mx*2)*(h-p.t-p.b);i?x.lineTo(xx,yy):x.moveTo(xx,yy)});x.stroke();drawXAxis(x,w,h,p,series);const coord=q=>({x:p.l+(q.t-t0)/Math.max(1,t1-t0)*(w-p.l-p.r),y:p.t+(mx-q.v)/(mx*2)*(h-p.t-p.b)}),st=coord(series[0]),en=coord(series.at(-1));x.fillStyle='#69b4ff';[st,en].forEach(q=>{x.beginPath();x.arc(q.x,q.y,3.5,0,Math.PI*2);x.fill()});endpointLabel(host,'start',fmt(id,a[0].v),st.x,st.y);endpointLabel(host,'end',fmt(id,a.at(-1).v),en.x,en.y);const hi=c._mn?.hover;if(Number.isInteger(hi)){const q=series[hi],z=coord(q);x.strokeStyle='#dce8f7aa';x.beginPath();x.moveTo(z.x,p.t);x.lineTo(z.x,h-p.b);x.stroke();x.fillStyle='#edf4ff';x.beginPath();x.arc(z.x,z.y,4,0,Math.PI*2);x.fill();tip.textContent=`${dateLabel(q.t)} · ${fmt(id,q.raw)} · ${q.v>=0?'+':''}${q.v.toFixed(2)}${unit}`;tip.style.display='block';tip.style.left=Math.min(w-tip.offsetWidth-4,Math.max(4,z.x+8))+'px';tip.style.top=Math.max(4,z.y-28)+'px'}else tip.style.display='none';c._mn={...(c._mn||{}),data:series,pad:p,draw}};c._mn={data:a,pad:{l:48,r:14,t:22,b:32},hover:null,draw};bindChart(c);draw()}
function sigHTML""", 'component renderer')

# Basis and index cards now use selected-window T0-relative paths, not persisted 90-day reference scores.
rx(r"function basis\(\)\{.*?\}function renderRanges", "function basis(){if(S.detail?.level==='component')return S.series[S.detail.id]?.observations;if(S.detail?.level==='index')return dynamicIndexSeries(S.detail.id);return dynamicIndexSeries('regime')}function renderRanges", 'range basis')
rx(r"function indexCard\(id\)\{.*?\}\nfunction integrityText", """function indexCard(id){const d=dynamicIndexSeries(id),end=d.at(-1),chg=points(d);return `<article class="card indexCard" data-index="${id}"><div><div class="kicker">${LABEL[id].toUpperCase()} INDEX</div><div class="headline"><strong>${end?end.v.toFixed(0):'—'}</strong><span>/100</span><span class="descriptor">State</span>${end?sigHTML(end.v):''}<span class="descriptor">Direction</span>${directionHTML(chg)}<span class="move ${moveClass(chg)}">${ptxt(chg)}</span></div><div class="meta">T0 50 → current ${end?end.v.toFixed(0):'—'} · ${RANGES[S.range][0]} · weighted relative movement</div></div><div class="chartbox"><canvas id="index-${id}" class="chart"></canvas></div></article>`}
function integrityText""", 'index card')

# Parent integrity and overview use the exact same dynamic child paths.
rx(r"function integrityText\(\)\{.*?\}\nfunction overview", """function integrityText(){const vals=['risk','growth','macro'].map(id=>dynamicIndexSeries(id).at(-1)?.v).filter(Number.isFinite),end=dynamicIndexSeries('regime').at(-1)?.v;if(vals.length!==3||!Number.isFinite(end))return'Parent/child integrity unavailable';const mean=vals.reduce((a,b)=>a+b,0)/3;return `Current ${end.toFixed(1)} = mean(${vals.map(v=>v.toFixed(1)).join(', ')}) ${Math.abs(mean-end)<.11?'✓':'⚠'}`}
function overview""", 'integrity')
rx(r"function overview\(\)\{.*?\}\nfunction componentPanel", """function overview(){const d=dynamicIndexSeries('regime'),end=d.at(-1),chg=points(d);$('#nowBody').className='now';$('#nowBody').innerHTML=`<article class="card parent" data-index="regime"><div class="parentHead"><div><div class="kicker">REGIME SENTIMENT INDEX · 0–100 · T0-RELATIVE</div><div class="headline"><strong>${end?end.v.toFixed(0):'—'}</strong><span>/100</span><span class="descriptor">State</span>${end?sigHTML(end.v):''}<span class="descriptor">Direction</span>${directionHTML(chg)}<span class="move ${moveClass(chg)}">${ptxt(chg)}</span></div><div class="meta">T0 = 50 · current ${end?end.v.toFixed(0):'—'} · ${RANGES[S.range][0]} · weighted child movement from selected T0</div></div><div class="integrity">${integrityText()}</div></div><div class="chartbox"><canvas id="regimeChart" class="chart"></canvas></div></article><div class="children">${['risk','growth','macro'].map(indexCard).join('')}</div>`;requestAnimationFrame(()=>{drawIndex($('#regimeChart'),d,'#f0b64e');['risk','growth','macro'].forEach(id=>drawIndex($('#index-'+id),dynamicIndexSeries(id)))});$$('[data-index]').forEach(e=>e.onclick=()=>{S.detail={level:'index',id:e.dataset.index};render()})}
function componentPanel""", 'overview')

# Contribution exposes weight, role and movement from T0.
rx(r"function componentPanel\(id\)\{.*?\}\nfunction cycleComponent", """function componentPanel(id,parent){const d=cut(S.series[id]?.observations||[],S.range),cfg=componentCfg(parent,id),e=relativeContribution(parent,id),chg=cfg?.mode==='delta'?(d.length?d.at(-1).v-d[0].v:null):percent(d),c=e?.label||'Neutral',cc=c.toLowerCase();return `<article class="componentPanel" data-component="${id}"><div class="componentHead"><div><div class="kicker">COMPONENT · WEIGHT ${(cfg?.weight*100||0).toFixed(0)}%</div><b>${LABEL[id]||S.series[id]?.name||id}</b><div class="meta">${cfg?.role||''}</div></div><div class="stateRow"><span class="descriptor">Contribution</span><span class="contribution ${cc}">${c}</span><span class="descriptor">Direction</span>${directionHTML(cfg?.direction===-1&&Number.isFinite(chg)?-chg:chg)}</div></div><div class="meta">T0 ${e?fmt(id,e.valueT0):'—'} → ${e?fmt(id,e.value):'—'} · movement ${Number.isFinite(e?.raw)?(e.raw>=0?'+':'')+e.raw.toFixed(2)+(cfg?.mode==='delta'?'':'%'):'—'} · weighted effect ${Number.isFinite(e?.weighted)?e.weighted.toFixed(3):'—'}</div><div class="chartbox"><canvas id="activeComponent" class="chart"></canvas></div></article>`}
function cycleComponent""", 'component panel')

# Index detail uses declared model children and weight tabs.
rx(r"function indexDetail\(id\)\{.*?\}\nfunction componentDetail", """function indexDetail(id){const d=dynamicIndexSeries(id),end=d.at(-1),chg=points(d),kids=indexChildren(id);if(id==='regime'){S.detail=null;overview();return}const selected=Math.max(0,Math.min(kids.length-1,S.componentTab[id]??0));S.componentTab[id]=selected;const active=kids[selected];$('#nowBody').className='detail';$('#nowBody').innerHTML=`<article class="card detailTop"><div><div class="kicker">INDEX · 0–100 · T0-RELATIVE WEIGHTED ROLLUP</div><div class="headline"><strong>${LABEL[id]}</strong><span>${end?end.v.toFixed(0)+'/100':'—'}</span><span class="descriptor">State</span>${end?sigHTML(end.v):''}<span class="descriptor">Direction</span>${directionHTML(chg)}<span class="move ${moveClass(chg)}">${ptxt(chg)}</span></div><div class="meta">T0 = 50 → current ${end?end.v.toFixed(0):'—'} · children below are weighted relative movements from the same T0</div></div><button class="btn primary" data-analyze-scope="${id}">Analyze ${LABEL[id]}</button></article><div class="componentStage"><div class="componentTabs">${kids.map((k,i)=>{const cfg=componentCfg(id,k);return `<button data-comp-tab="${i}" class="${i===selected?'active':''}">${LABEL[k]||S.series[k]?.short||k} · ${(cfg?.weight*100||0).toFixed(0)}%</button>`}).join('')}</div><div class="componentViewport"><button class="componentNav prev" type="button" aria-label="Previous component">‹</button>${componentPanel(active,id)}<button class="componentNav next" type="button" aria-label="Next component">›</button></div></div>`;requestAnimationFrame(()=>drawComponent($('#activeComponent'),active,cut(S.series[active]?.observations||[],S.range),componentCfg(id,active)));$$('[data-comp-tab]').forEach(b=>b.onclick=()=>{S.componentTab[id]=Number(b.dataset.compTab);render()});$('.componentNav.prev').onclick=()=>cycleComponent(id,-1);$('.componentNav.next').onclick=()=>cycleComponent(id,1);let sx=null;const vp=$('.componentViewport');vp.addEventListener('pointerdown',e=>{sx=e.clientX});vp.addEventListener('pointerup',e=>{if(sx==null)return;const dx=e.clientX-sx;sx=null;if(Math.abs(dx)>50)cycleComponent(id,dx<0?1:-1)});$('.componentPanel').onclick=e=>{if(e.target.closest('.componentNav'))return;S.detail={level:'component',id:active,parent:id};render()};$('[data-analyze-scope]').onclick=()=>openAnalysisFor(id)}
function componentDetail""", 'index detail')

# Component detail remains a child of its model parent and uses the component's correct movement unit.
rx(r"function componentDetail\(id\)\{.*?\}function renderNow", """function componentDetail(id){const parent=S.detail?.parent,cfg=componentCfg(parent,id),d=cut(S.series[id]?.observations||[],S.range),e=relativeContribution(parent,id),chg=cfg?.mode==='delta'?(d.length?d.at(-1).v-d[0].v:null):percent(d);$('#nowBody').className='detail';$('#nowBody').innerHTML=`<article class="card detailTop"><div><div class="kicker">COMPONENT · T0-RELATIVE · WEIGHT ${(cfg?.weight*100||0).toFixed(0)}%</div><div class="headline"><strong>${LABEL[id]||S.series[id]?.name||id}</strong><span class="descriptor">Contribution</span><span class="contribution ${(e?.label||'Neutral').toLowerCase()}">${e?.label||'Neutral'}</span><span class="descriptor">Direction</span>${directionHTML(cfg?.direction===-1&&Number.isFinite(chg)?-chg:chg)}</div><div class="meta">${cfg?.role||''} · T0 ${e?fmt(id,e.valueT0):'—'} → ${e?fmt(id,e.value):'—'} · raw movement ${Number.isFinite(e?.raw)?(e.raw>=0?'+':'')+e.raw.toFixed(2)+(cfg?.mode==='delta'?'':'%'):'—'}</div></div><button class="btn primary" data-analyze-scope="${id}">Analyze component</button></article><article class="card componentPanel"><div class="chartbox"><canvas id="componentSolo" class="chart"></canvas></div></article>`;requestAnimationFrame(()=>drawComponent($('#componentSolo'),id,d,cfg));$('[data-analyze-scope]').onclick=()=>openAnalysisFor(id)}function renderNow""", 'component detail')

# Macro surface shows every populated FRED series; same standardized renderer.
rx(r"function renderMacro\(\)\{.*?\}function renderNews", """function renderMacro(){const ids=Object.keys(S.series).filter(id=>S.series[id]?.kind==='macro'&&S.series[id]?.observations?.length);$('#macroBody').className='macro';$('#macroBody').innerHTML=ids.map(id=>{const d=cut(S.series[id].observations,S.range),cfg=[...Object.values(S.model?.indexes||{}).flatMap(x=>x.components||[])].find(x=>x.id===id)||null,chg=cfg?.mode==='delta'?(d.length?d.at(-1).v-d[0].v:null):percent(d);return `<article class="componentPanel"><div class="componentHead"><div><div class="kicker">MACRO SERIES · ${S.series[id].cadence||''}</div><b>${LABEL[id]||S.series[id].name||id}</b></div><div>${moveHTML(chg,cfg?.mode==='delta'?'delta':'percent')}</div></div><div class="meta">${d.length?fmt(id,d[0].v)+' → '+fmt(id,d.at(-1).v):'Unavailable'} · ${RANGES[S.range][0]}</div><div class="chartbox"><canvas id="macro-${id}" class="chart"></canvas></div></article>`}).join('');requestAnimationFrame(()=>ids.forEach(id=>{const cfg=[...Object.values(S.model?.indexes||{}).flatMap(x=>x.components||[])].find(x=>x.id===id)||null;drawComponent($('#macro-'+id),id,cut(S.series[id].observations,S.range),cfg)}))}function renderNews""", 'macro surface')

# moveHTML supports rate/spread deltas without false percentage-return semantics.
rep("function moveHTML(v,unit){return `<span class=\"move ${moveClass(v)}\">${unit==='points'?ptxt(v):pctxt(v)}</span>`}", "function moveHTML(v,unit){const txt=unit==='points'?ptxt(v):unit==='delta'?(Number.isFinite(v)?`${v>=0?'+':''}${v.toFixed(2)}`:'Unavailable'):pctxt(v);return `<span class=\"move ${moveClass(v)}\">${txt}</span>`}", 'delta move')

# Evidence for AI is the same T0-relative model shown on screen.
rx(r"function evidence\(scope,range\)\{.*?\}function getKey", """function evidence(scope,range){const isIndex=scope==='regime'||!!modelIndex(scope);if(isIndex){const d=dynamicIndexSeries(scope,range),start=d[0],end=d.at(-1),out={scope,label:LABEL[scope]||scope,type:'index',horizon:RANGES[range][0],from:start?new Date(start.t).toISOString():null,to:end?new Date(end.t).toISOString():null,start:start?.v??null,current:end?.v??null,change:points(d),changeUnit:'points',thresholds:{pessimisticBelow:42,neutral:[42,58],optimisticAtOrAbove:58},baseline:'T0=50'};out.children=indexChildren(scope).map(id=>{if(scope==='regime'){const x=dynamicIndexSeries(id,range);return{id,label:LABEL[id]||id,weight:1/3,start:x[0]?.v??null,current:x.at(-1)?.v??null,change:points(x),changeUnit:'points'}}const cfg=componentCfg(scope,id),e=relativeContribution(scope,id,range);return{id,label:LABEL[id]||S.series[id]?.name||id,weight:cfg?.weight??null,role:cfg?.role??null,mode:cfg?.mode??null,valueT0:e?.valueT0??null,current:e?.value??null,rawChange:e?.raw??null,effect:e?.effect??null,weightedEffect:e?.weighted??null,contribution:e?.label??null}});out.news=S.news.slice(0,20).map(n=>({title:n.title,source:n.source,publishedAt:n.publishedAt,topics:n.topics||[],outlook:!!n.outlook,url:n.url||n.link||''}));return out}const obj=S.series[scope],d=cut(obj?.observations||[],range),start=d[0],end=d.at(-1),parent=S.detail?.parent||null,cfg=parent?componentCfg(parent,scope):null;return{scope,label:LABEL[scope]||obj?.name||scope,type:'component',horizon:RANGES[range][0],from:start?new Date(start.t).toISOString():null,to:end?new Date(end.t).toISOString():null,start:start?.v??null,current:end?.v??null,change:cfg?.mode==='delta'?(start&&end?end.v-start.v:null):percent(d),changeUnit:cfg?.mode==='delta'?'level delta':'percent',parent,weight:cfg?.weight??null,role:cfg?.role??null,news:S.news.slice(0,20).map(n=>({title:n.title,source:n.source,publishedAt:n.publishedAt,topics:n.topics||[],outlook:!!n.outlook,url:n.url||n.link||''}))}}function getKey""", 'analysis evidence')

# Strengthen the AI contract around T0, weights and arithmetic integrity.
rx(r"const prompt='Analyze this persisted Market Navigator snapshot for an investor\..*?Evidence: '\+JSON\.stringify\(ev\);", """const prompt='Analyze this persisted Market Navigator snapshot for an investor. FIRST validate parent arithmetic and weights. T0 is the selected-horizon baseline and every index starts at 50. State, direction, and contribution are separate concepts. Index movement is points from T0, never a percentage return. Displayed child values are scores, not weights; never divide child scores by their weights. Numeric data is primary evidence; news is contextual only and must never be asserted as causal without numerical evidence. Explain observed direction, weighted parent/child relationships, contradictions, macro context, event overlay, and what would change the view. Never invent missing data or causality. '+(q?'User question: '+q+' ':'')+'Evidence: '+JSON.stringify(ev);""", 'analysis prompt')

# Load model.json and all expanded series from the canonical manifest.
rx(r"async function load\(\)\{.*?\}function toggleNav", """async function load(){try{await openDb();S.analyses=await dbAll();S.manifest=await fetch(ROOT+'manifest.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('manifest '+r.status);return r.json()});S.model=await fetch(ROOT+(S.manifest.modelFile||'model.json'),{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('model '+r.status);return r.json()});const indexIds=Object.keys(S.manifest.indexes||{}),seriesIds=Object.keys(S.manifest.series||{});await Promise.all(indexIds.map(async id=>S.indexes[id]=await fetch(ROOT+'indexes/'+id+'.json').then(r=>r.json())),seriesIds.map(async id=>S.series[id]=await fetch(ROOT+'series/'+id+'.json').then(r=>r.json())));try{const n=await fetch(NEWSURL).then(r=>r.json());S.news=n.data||[]}catch{}$('#dot').classList.add('ok');$('#status').textContent='Database current · '+new Date(S.manifest.generatedAt).toLocaleString();setupAnalysis();render()}catch(e){$('#dot').classList.add('bad');$('#status').textContent='Database unavailable';$('#nowBody').textContent=e.message}}function toggleNav""", 'model load')

rep('UI v2.1 · Regime → Index → Component · UI semantics v2.1', 'UI v2.2 · T0-relative weighted Regime → Index → Component · UI semantics v2.2', 'version')
rep('<p>Index charts are 0–100 with a visible <b>neutral band from 42–58</b>.', '<p>Every selected horizon establishes <b>T0 = 50</b>. Index paths are weighted from each child\'s relative movement from that same T0. Index charts are 0–100 with a visible <b>neutral band from 42–58</b>.', 'about T0')

p.write_text(s,encoding='utf-8')
print('Migrated Market Navigator to UI semantics v2.2')
