from pathlib import Path

p=Path('market-view.html')
s=p.read_text()
if "const VERSION='3.9.0'" not in s:
    raise SystemExit('Expected Market Navigator 3.9.0 baseline')

s=s.replace('<!DOCTYPE html>', '''<!DOCTYPE html>\n<!--\nMarket Navigator 3.9.1\nUsage: open market-view.html on GitHub Pages. The app fetches live/historical Yahoo market data, cleans it in a blob WebWorker, persists canonical observations locally, and routes between #home and #detail/<ticker>.\nVersion: 3.9.1\nVerification checklist:\n1. Data loads from fetch() and the status reports the market-data connection rather than a stored-data placeholder.\n2. #home and #detail/<ticker> navigation work; browser Back returns to the prior view without re-fetching already-loaded series.\n3. Worker-cleaned observations contain finite positive numeric values, use dot-decimal JavaScript numbers, and duplicate timestamps/dates are removed.\n4. CSV export downloads the cleaned selected-horizon data client-side.\n5. Keyboard: ticker rows accept ArrowUp/ArrowDown focus movement and Enter opens detail.\n6. Accessibility: focus rings, contrast, semantic table/buttons and readable chart legends/tooltips meet the intended WCAG AA presentation.\n7. Responsive: home/detail charts remain within the viewport on mobile and desktop without page scrolling.\n8. Charts: every chart shows a legend; hover/touch inspection shows series name, value and timestamp; index charts never show a dollar-sign Y axis.\n-->''',1)
s=s.replace('<title>Market Navigator 3.9</title>','<title>Market Navigator 3.9.1</title>')
s=s.replace('Version 3.9</small>','Version 3.9.1</small>')
s=s.replace("const VERSION='3.9.0'","const VERSION='3.9.1'")
s=s.replace('Loading stored data…','Connecting to market data…')

anchor='</script></body></html>'
if anchor not in s:
    raise SystemExit('closing script anchor missing')

override=r'''
/* 3.9.1: worker-cleaned fetch pipeline, hash router, accessible summary table, standard chart contract */
const UI391={
  colors:{bg:'#08111f',panel:'#101b2d',line:'#526984',text:'#ffffff',muted:'#c2cfdd',accent:'#74c0ff',focus:'#ffd166',good:'#51e38a',bad:'#ff7b86',neutral:'#ffd166'},
  td:{padding:'9px 10px',background:'#101b2d',borderTop:'1px solid #526984',borderBottom:'1px solid #526984'},
  focus:{outline:'3px solid #ffd166',outlineOffset:'2px'},
  chip:{display:'inline-flex',alignItems:'center',justifyContent:'center',padding:'4px 9px',borderRadius:'999px',fontSize:'11px',fontWeight:'850',border:'1px solid currentColor'}
};
function styleObj(el,obj){if(!el||!obj)return el;Object.assign(el.style,obj);return el}
function numeric391(v){if(typeof v==='number')return Number.isFinite(v)?v:null;if(v==null)return null;const x=Number(String(v).trim().replace(/\s/g,'').replace(',','.'));return Number.isFinite(x)?x:null}
function marketWorker391(){const src=`self.onmessage=e=>{try{const {text,id}=e.data,j=JSON.parse(text),r=j?.chart?.result?.[0],ts=r?.timestamp||[],close=r?.indicators?.quote?.[0]?.close||[],map=new Map();for(let i=0;i<ts.length;i++){let raw=close[i];if(raw===null||raw===undefined)continue;if(typeof raw==='string')raw=raw.trim().replace(/\\s/g,'').replace(',','.');const v=Number(raw),t=Number(ts[i])*1000;if(!Number.isFinite(t)||!Number.isFinite(v)||v<=0)continue;map.set(t,{t,v})}const data=[...map.values()].sort((a,b)=>a.t-b.t);self.postMessage({ok:true,id,data})}catch(error){self.postMessage({ok:false,error:String(error?.message||error)})}}`;const blob=new Blob([src],{type:'text/javascript'}),url=URL.createObjectURL(blob),w=new Worker(url);w.__url=url;return w}
function parseMarketJSON391(text,id){return new Promise((resolve,reject)=>{const w=marketWorker391(),done=()=>{w.terminate();URL.revokeObjectURL(w.__url)};w.onmessage=e=>{const m=e.data;done();m?.ok?resolve(m.data):reject(new Error(m?.error||'Worker parse failed'))};w.onerror=e=>{done();reject(new Error(e.message||'Worker parse failed'))};w.postMessage({text,id})})}
async function fetchMarketText391(url,label){let last;for(const u of [url,`https://api.allorigins.win/raw?url=${encodeURIComponent(url)}`,`https://corsproxy.io/?url=${encodeURIComponent(url)}`]){try{const r=await fetch(u,{cache:'no-store'}),t=await r.text();if(!r.ok)throw new Error(`${r.status}`);if(!t.trim())throw new Error('empty response');return t}catch(e){last=e}}throw new Error(`${label}: ${last?.message||'unavailable'}`)}
async function yahoo(id,range='5d',interval='1d'){const m=META[id];if(!m?.symbol)throw new Error(`${id}: no market symbol`);const url=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(m.symbol)}?range=${range}&interval=${interval}&includePrePost=false&events=div%2Csplits`;const text=await fetchMarketText391(url,`Yahoo ${m.short}`),data=await parseMarketJSON391(text,id);if(data.length<2)throw new Error(`${m.short}: insufficient market observations`);return data}
function canonical391(data){const map=new Map();for(const p of data||[]){const t=numeric391(p?.t),v=numeric391(p?.v);if(!Number.isFinite(t)||!Number.isFinite(v)||v<=0)continue;const d=new Date(t),key=`${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}-${String(d.getUTCDate()).padStart(2,'0')}`;map.set(key,{t,v})}return[...map.values()].sort((a,b)=>a.t-b.t)}
const _saveSeries391=saveSeries;saveSeries=async function(id,data){return _saveSeries391(id,canonical391(data))};
function seriesUnit391(id){if(id==='tenYear'||['cpi','fedFunds','twoYear','thirtyYear'].includes(id))return'percent';return'currency'}
function yLabel391(id,v,{normalized=false,index=false}={}){if(normalized||index)return Number(v).toFixed(1);if(seriesUnit391(id)==='percent')return `${Number(v).toFixed(2)}%`;return `$${Number(v).toFixed(2)}`}
function hoverValue391(s,v,{normalized=false,index=false}={}){if(normalized||index)return `${s.name}: ${Number(v).toFixed(1)}`;if(seriesUnit391(s.id)==='percent')return `${s.name}: ${Number(v).toFixed(2)}%`;return `${s.name}: $${Number(v).toFixed(2)}`}
function axisDate391(t,r){const d=new Date(t);if(r==='1d')return d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});if(r==='5d')return d.toLocaleDateString([],{weekday:'short',month:'short',day:'numeric'});if(['1mo','3mo'].includes(r))return d.toLocaleDateString([],{month:'short',day:'numeric'});if(['6mo','ytd','1y'].includes(r))return d.toLocaleDateString([],{month:'short',year:'2-digit'});return d.toLocaleDateString([],{month:'short',year:'2-digit'})}
function chart(canvas,list,{range=state.range,axes=true,normalized=false,index=false}={}){const {x,w,h}=setupCanvas(canvas),legendH=axes?28:20,pad=axes?{l:62,r:12,t:legendH+8,b:32}:{l:3,r:3,t:legendH,b:3},pts=list.flatMap(s=>s.data||[]);x.clearRect(0,0,w,h);x.font='11px system-ui';x.textBaseline='middle';let lx=pad.l;for(const s of list){x.fillStyle=s.color;x.fillRect(lx,7,10,10);x.fillStyle='#eef5ff';const label=s.name||s.id;x.fillText(label,lx+15,12);lx+=Math.min(150,25+x.measureText(label).width)}if(!pts.length){x.fillStyle='#c2cfdd';x.fillText('Data unavailable',pad.l,pad.t+16);return}let t0=Math.min(...pts.map(p=>p.t)),t1=Math.max(...pts.map(p=>p.t));if(t0===t1)t1+=864e5;let lo=Math.min(...pts.map(p=>p.v)),hi=Math.max(...pts.map(p=>p.v)),margin=(hi-lo||1)*.08;lo-=margin;hi+=margin;if(axes){x.strokeStyle='#526984';x.fillStyle='#d7e4f1';x.font='10px system-ui';for(let i=0;i<5;i++){const y=pad.t+(h-pad.t-pad.b)*i/4,val=hi-(hi-lo)*i/4;x.beginPath();x.moveTo(pad.l,y);x.lineTo(w-pad.r,y);x.stroke();x.fillText(yLabel391(list[0]?.id,val,{normalized,index}),4,y)}for(let i=0;i<5;i++){const t=t0+(t1-t0)*i/4,px=pad.l+(w-pad.l-pad.r)*i/4;x.fillText(axisDate391(t,range),Math.max(2,Math.min(w-58,px-19)),h-10)}}for(const s of list){x.strokeStyle=s.color;x.lineWidth=axes?2:1.8;x.beginPath();s.data.forEach((pt,i)=>{const px=pad.l+(pt.t-t0)/(t1-t0)*(w-pad.l-pad.r),py=pad.t+(hi-pt.v)/(hi-lo)*(h-pad.t-pad.b);i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke()}const inspect=e=>{e.stopPropagation();document.getElementById('tip')?.remove();const r=canvas.getBoundingClientRect(),ratio=Math.max(0,Math.min(1,(e.clientX-r.left-pad.l)/(r.width-pad.l-pad.r))),target=t0+ratio*(t1-t0),tip=document.createElement('div');tip.id='tip';styleObj(tip,{position:'fixed',zIndex:'160',background:'#ffffff',color:'#07111e',padding:'8px 10px',borderRadius:'8px',fontSize:'12px',boxShadow:'0 8px 24px #0008',left:`${Math.min(innerWidth-245,e.clientX+10)}px`,top:`${Math.max(8,e.clientY-82)}px`,pointerEvents:'none'});tip.innerHTML=list.map(s=>{const p=(s.data||[]).reduce((a,b)=>Math.abs(b.t-target)<Math.abs(a.t-target)?b:a,s.data?.[0]);return p?`<div><b>${hoverValue391(s,p.v,{normalized,index})}</b><div>${new Date(p.t).toLocaleString()}</div></div>`:''}).join('');document.body.appendChild(tip)};canvas.onpointerdown=inspect;canvas.onpointermove=e=>{if(e.pointerType==='mouse'||e.buttons===1)inspect(e)};canvas.onpointerleave=()=>document.getElementById('tip')?.remove()}
function chip391(label,cls='neutral'){const c=cls==='good'?UI391.colors.good:cls==='bad'?UI391.colors.bad:UI391.colors.neutral;return `<span style="display:inline-flex;align-items:center;justify-content:center;padding:4px 9px;border-radius:999px;font-size:11px;font-weight:850;border:1px solid ${c};color:${c}">${label}</span>`}
function homeRow391(id){const z=q(id,state.range),m=META[id],s=signal(id,state.range);return `<tr data-ticker="${id}" tabindex="0" role="link" aria-label="Open ${m.name} detail"><td>${m.short}</td><td>${m.name}</td><td>${z?fmt(id,z.value):'Unavailable'}</td><td>${z?pct(z.p):'Unavailable'}</td><td>${chip391(s.label,s.cls)}</td></tr>`}
function bindRows391(){const rows=$$('[data-ticker]');rows.forEach((row,i)=>{styleObj(row,{cursor:'pointer',outline:'none'});[...row.children].forEach((td,j)=>styleObj(td,{...UI391.td,borderLeft:j===0?'1px solid #526984':'',borderRight:j===row.children.length-1?'1px solid #526984':''}));row.onmouseenter=()=>row.style.filter='brightness(1.18)';row.onmouseleave=()=>row.style.filter='none';row.onfocus=()=>Object.assign(row.style,UI391.focus);row.onblur=()=>{row.style.outline='none';row.style.outlineOffset='0'};row.onclick=()=>navigateDetail391(row.dataset.ticker);row.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();navigateDetail391(row.dataset.ticker)}else if(e.key==='ArrowDown'){e.preventDefault();rows[(i+1)%rows.length]?.focus()}else if(e.key==='ArrowUp'){e.preventDefault();rows[(i-1+rows.length)%rows.length]?.focus()}}})}
function renderNow(){const r=regimeSummary(state.range),cats=['risk','growth','macro'].map(k=>({k,z:categoryIndex(k,state.range),c:CATEGORY[k]}));$('#nowSnapshot').innerHTML=`<div class="snapshot" style="grid-template-rows:auto auto minmax(0,1fr);overflow:hidden"><div class="hero"><article class="card regime" data-regime-open><div class="gauge"><strong>${r?r.score:'—'}</strong></div><div><div class="kicker">REGIME SENTIMENT INDEX · 0–100</div><h2>${r?r.label:'Unavailable'}</h2><div class="muted">${H[state.range].label} · baseline 50 · ${r&&Number.isFinite(r.periodPct)?pct(r.periodPct):'Unavailable'} over selected horizon</div></div></article><article class="card"><div class="row"><div><div class="kicker">MARKET DATA</div><h2>${H[state.range].label} snapshot</h2></div><button id="csvHome" class="btn">Export CSV</button></div><div class="muted">Real Yahoo observations cleaned in a WebWorker. Select a row for detail.</div></article></div><div class="row" style="justify-content:flex-start;gap:8px">${cats.map(({k,z,c})=>`<button data-category="${k}" class="btn" style="min-width:120px">${c.name} ${chip391(z?.label||'Unavailable',z?.cls||'neutral')} <b style="margin-left:6px">${z?.score??'—'}</b></button>`).join('')}</div><div style="min-height:0;overflow:hidden"><table id="homeTable" aria-label="Market summary" style="width:100%;border-collapse:separate;border-spacing:0 6px;font-size:13px"><thead><tr>${['Ticker','Series','Latest',`${H[state.range].label} change`,'Signal'].map(h=>`<th style="text-align:left;color:#c2cfdd;font-size:11px;letter-spacing:.06em;text-transform:uppercase;padding:4px 10px">${h}</th>`).join('')}</tr></thead><tbody>${['spy','tenYear','wti'].map(homeRow391).join('')}</tbody></table></div></div>`;setTimeout(()=>{$$('[data-category]').forEach(e=>e.onclick=()=>openCategory(e.dataset.category));$('[data-regime-open]')?.addEventListener('click',()=>setSection('now','nowTrend'));$('#csvHome').onclick=()=>exportCSV391();bindRows391();renderGlobalRange()},0);renderRegimeTrend()}
function exportCSV391(id=null){const ids=id?[id]:['spy','tenYear','wti'],rows=[['ticker','series','timestamp','date','value','horizon']];for(const sid of ids){for(const p of rangeData(sid,state.range)){rows.push([META[sid].short,META[sid].name,new Date(p.t).toISOString(),new Date(p.t).toISOString().slice(0,10),String(p.v),H[state.range].label])}}const enc=new TextEncoder(),parts=[];for(const r of rows)parts.push(enc.encode(r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')+'\n'));const blob=new Blob(parts,{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`market-navigator-${id||'summary'}-${state.range}-${new Date().toISOString().slice(0,10)}.csv`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function navigateDetail391(id){const target=`#detail/${encodeURIComponent(id)}`;if(location.hash!==target)location.hash=target;else route391()}
async function openDetail(id){state.detail={id,range:state.range};if(location.hash!==`#detail/${encodeURIComponent(id)}`){navigateDetail391(id);return}$('#saveDetail').style.display='';$('#detailModal').classList.add('open');await drawDetail391()}
async function drawDetail391(){const id=state.detail?.id,range=state.range,m=META[id];if(!m)return;state.detail.range=range;$('#detailKicker').textContent=m.role;$('#detailTitle').textContent=m.name;$('#detailRanges').innerHTML=`<button id="detailBack391" class="btn">← Back</button>`+Object.entries(H).map(([k,v])=>`<button data-dr="${k}" class="${k===range?'active':''}">${v.label}</button>`).join('');let data;if(H[range].intraday&&m.symbol){const key=`${id}:${range}`;if(!state.intraday[key]){progress(true,'Loading market data',`${m.name} · ${H[range].label}`,35);try{state.intraday[key]=await yahoo(id,H[range].range,H[range].interval)}catch(e){toast('Market data unavailable')}progress(false)}data=state.intraday[key]||[]}else{if(m.symbol&&!coverage(id,range)){progress(true,'Extending market history',`${m.name} · ${H[range].label}`,35);try{await saveSeries(id,await yahoo(id,range==='5y'||range==='max'?'5y':'1y','1d'))}catch(e){toast('Historical data unavailable')}progress(false)}data=rangeData(id,range)}chart($('#detailChart'),[{id,name:m.short,color:m.color,data}],{range,axes:true,index:false});const z=quoteAny(data),start=data[0],end=data.at(-1);$('#detailStats').innerHTML=`<div class="stat"><span class="kicker">LATEST</span><b>${end?fmt(id,end.v):'Unavailable'}</b></div><div class="stat"><span class="kicker">${H[range].label} CHANGE</span><b>${z?pct(z.p):'Unavailable'}</b></div><div class="stat"><span class="kicker">OBS</span><b>${data.length}</b></div><div class="stat"><span class="kicker">FROM</span><b>${start?new Date(start.t).toLocaleDateString():'—'}</b></div><div class="stat"><span class="kicker">TO</span><b>${end?new Date(end.t).toLocaleDateString():'—'}</b></div><button id="csvDetail391" class="stat" style="color:#fff;cursor:pointer"><span class="kicker">EXPORT</span><b>CSV</b></button>`;$('#detailBack391').onclick=()=>history.back();$('#csvDetail391').onclick=()=>exportCSV391(id);$$('[data-dr]').forEach(b=>b.onclick=async()=>{state.range=b.dataset.dr;state.detail.range=state.range;renderGlobalRange();renderAll();await drawDetail391()});$('#saveDetail').onclick=()=>saveAnalysis(`${m.short} ${H[range].label} detail`,{type:'series',id,range,data:data.slice(-500)})}
async function route391(){const h=location.hash||'#home';if(h==='#home'||h==='#'){state.detail=null;$('#detailModal').classList.remove('open');setSection('now','nowSnapshot');renderNow();return}const m=h.match(/^#detail\/([^/?#]+)/);if(m){const id=decodeURIComponent(m[1]);if(META[id]){state.detail={id,range:state.range};$('#detailModal').classList.add('open');await drawDetail391();return}}location.replace('#home')}
function renderRegimeTrend(){const d=regimeHistorySlice(state.range),z=regimeSummary(state.range);$('#nowTrend').innerHTML=`<div class="snapshot"><article class="card" style="height:100%;display:grid;grid-template-rows:auto minmax(0,1fr) auto;overflow:hidden"><div class="row"><div><div class="kicker">REGIME SENTIMENT INDEX · ${H[state.range].label}</div><h2>${z?`${z.score}/100 · ${z.label}`:'Unavailable'}</h2><div class="muted tiny">Baseline 50 · selected-horizon change ${z&&Number.isFinite(z.periodPct)?pct(z.periodPct):'Unavailable'}</div></div>${chip391(z?.score>=58?'Positive':z?.score<=42?'Negative':'Neutral',z?.score>=58?'good':z?.score<=42?'bad':'neutral')}</div><div class="chartBox"><canvas id="regimeChart" class="chart"></canvas></div><div class="actions"><button class="btn primary" id="saveRegime">Save to Analysis</button><button class="btn" id="csvRegime391">Export CSV</button></div></article></div>`;setTimeout(()=>{chart($('#regimeChart'),[{id:'regime',name:'Regime sentiment index',color:'#74c0ff',data:d}],{range:state.range,axes:true,index:true});$('#saveRegime').onclick=()=>saveAnalysis(`Regime ${H[state.range].label}`,{type:'regime',range:state.range,data:d});$('#csvRegime391').onclick=()=>{const rows=[['series','timestamp','score'],...d.map(p=>['Regime sentiment index',new Date(p.t).toISOString(),p.v])],blob=new Blob([rows.map(r=>r.join(',')).join('\n')],{type:'text/csv'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`regime-${state.range}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}} ,0);renderGlobalRange()}
const _drawCategory391=drawCategory;drawCategory=async function(){await _drawCategory391();const c=$('#detailChart');if(state.detail?.category&&c){const key=state.detail.category,list=normalize(CATEGORY[key].components.filter(id=>META[id]?.symbol),state.range);chart(c,list,{range:state.range,axes:true,normalized:true,index:true})}}
window.addEventListener('hashchange',route391);
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#detailModal').classList.contains('open'))history.back()});
$('#detailClose').onclick=()=>history.back();
setTimeout(()=>{if(!location.hash)history.replaceState(null,'','#home');route391();$('#status').textContent='Connecting to market data…'},0);
'''
s=s.replace(anchor,override+'\n</script></body></html>')
p.write_text(s)
print('Patched Market Navigator to 3.9.1')
