from pathlib import Path
p=Path('market-view.html')
s=p.read_text()
if "const VERSION='3.9.2'" not in s:
    raise SystemExit('Expected Market Navigator 3.9.2 baseline')

s=s.replace('<title>Market Navigator 3.9.2</title>','<title>Market Navigator 3.9.3</title>')
s=s.replace('Version 3.9.2</small>','Version 3.9.3</small>')
s=s.replace("const VERSION='3.9.2'","const VERSION='3.9.3'")
s=s.replace('Market Navigator 3.9.2\nUsage:','Market Navigator 3.9.3\nUsage:')
s=s.replace('Version: 3.9.2','Version: 3.9.3')

# Remove the manual refresh button: collection is automatic/stale-aware.
s=s.replace('<button id="refreshBtn" class="btn">Refresh due data</button>','')
s=s.replace("$('#refreshBtn').onclick=()=>refreshStale392(true);","")

# Presentation helpers for the new linear Now -> Category -> Component drilldown.
s=s.replace('</style></head>', '''
.now393{height:100%;display:grid;grid-template-rows:minmax(0,1.15fr) minmax(0,.85fr);gap:10px}.regime393{display:grid;grid-template-rows:auto minmax(0,1fr);gap:8px;cursor:pointer}.regime393:hover,.category393:hover{border-color:var(--accent)}.regimeHead393{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.regimeMetric393{display:flex;align-items:baseline;gap:9px}.regimeMetric393 strong{font-size:30px}.categoryGrid393{height:100%;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.category393{display:grid;grid-template-rows:auto auto minmax(0,1fr);gap:5px;cursor:pointer;min-height:0}.category393 .spark{min-height:54px}.microGrid393{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;height:100%;align-content:stretch}.micro393{border:1px solid var(--line);background:#0b1728;border-radius:12px;padding:10px;display:grid;grid-template-rows:auto minmax(0,1fr) auto;gap:7px;cursor:pointer;min-height:0;color:var(--text);text-align:left}.micro393:hover,.micro393:focus-visible{border-color:var(--accent);outline:2px solid #9ed1ff;outline-offset:2px}.microChart393{display:grid;grid-template-columns:1fr 1fr;gap:10px;align-items:end;min-height:90px;padding:6px 10px 0}.microCol393{display:grid;grid-template-rows:minmax(0,1fr) auto;gap:5px;align-items:end;height:100%}.microBar393{width:100%;border-radius:6px 6px 2px 2px;background:linear-gradient(180deg,#6db7ff,#2a6fb4);min-height:3px}.microBar393.end{background:linear-gradient(180deg,#48d88a,#258f60)}.microLabel393{font-size:10px;color:var(--muted);text-align:center}.microValues393{display:flex;justify-content:space-between;gap:8px;font-size:11px}.modalSub393{font-size:11px;color:var(--muted);margin-top:3px}.flow393{display:flex;align-items:center;gap:6px;flex-wrap:wrap;font-size:11px;color:var(--muted)}.flow393 b{color:var(--text)}@media(max-width:760px){.now393{grid-template-rows:minmax(0,1fr) minmax(0,1fr)}.categoryGrid393{grid-template-columns:repeat(3,minmax(0,1fr))}.category393{padding:10px}.category393 .value{font-size:20px}.microGrid393{grid-template-columns:1fr}.micro393{grid-template-columns:1fr 150px 1fr;grid-template-rows:auto;align-items:center}.microChart393{min-height:74px}}@media(max-width:520px){.now393{grid-template-rows:minmax(0,1.05fr) minmax(0,.95fr)}.categoryGrid393{grid-template-columns:repeat(3,minmax(0,1fr));gap:6px}.category393{padding:8px}.category393 h3{font-size:13px}.category393 .chip{font-size:9px;padding:3px 5px}.category393 .value{font-size:18px}.category393 .muted{font-size:9px}.regimeMetric393 strong{font-size:25px}.micro393{grid-template-columns:1fr;grid-template-rows:auto minmax(0,1fr) auto}.microChart393{min-height:92px}}
</style></head>''')

anchor='''function categoryIndex(key,r=state.range){const c=CATEGORY[key];let parts=[];for(const id of c.components){const z=q(id,r);if(!z||!coverage(id,r))continue;let effect=0;if(id==='spy')effect=clamp(z.p/8);if(id==='tenYear')effect=-clamp(z.p/6);if(id==='wti')effect=-clamp(z.p/12);parts.push({id,effect,p:z.p})}if(!parts.length)return null;const score=Math.round(50+35*(parts.reduce((a,b)=>a+b.effect,0)/parts.length));const s=Math.max(0,Math.min(100,score));return{score:s,label:s>=58?'Positive':s<=42?'Negative':'Neutral',cls:s>=58?'good':s<=42?'bad':'neutral',parts}}'''
if anchor not in s: raise SystemExit('categoryIndex anchor missing')
extra=r'''
function categoryIndexAt393(key,t){const c=CATEGORY[key];let parts=[];for(const id of c.components){const a=state.series[id]||[],now=nearest(a,t),prev=nearest(a,t-30*864e5);if(!now||!prev||!prev.v)continue;let p=(now.v/prev.v-1)*100,effect=0;if(id==='spy')effect=clamp(p/8);if(id==='tenYear')effect=-clamp(p/6);if(id==='wti')effect=-clamp(p/12);parts.push(effect)}if(!parts.length)return null;return Math.max(0,Math.min(100,Math.round(50+35*(parts.reduce((a,b)=>a+b,0)/parts.length))))}
function categoryHistory393(key,range=state.range){const base=rangeData('spy',range);return base.map(p=>({t:p.t,v:categoryIndexAt393(key,p.t)})).filter(p=>Number.isFinite(p.v))}
function regimeSeries393(range=state.range){const d=regimeHistorySlice(range);return d.map(x=>({t:x.t,v:x.v}))}
function periodChange393(data){if(!data?.length||!data[0].v)return null;return(data.at(-1).v/data[0].v-1)*100}
function directionCopy393(key,z){if(!z)return'Insufficient data';const sign=z.score>52?'supportive':z.score<48?'adverse':'balanced';const drivers=z.parts.map(p=>{const m=META[p.id];if(p.id==='wti')return `${m.short} ${p.p<0?'lower':'higher'} ${Math.abs(p.p).toFixed(1)}%`;if(p.id==='tenYear')return `${m.short} ${p.p<0?'lower':'higher'} ${Math.abs(p.p).toFixed(1)}%`;return `${m.short} ${p.p>=0?'higher':'lower'} ${Math.abs(p.p).toFixed(1)}%`});return `${sign[0].toUpperCase()+sign.slice(1)}: ${drivers.join(' · ')}`}
function microComponent393(id){const d=rangeData(id,state.range),z=q(id,state.range),m=META[id];if(!d.length)return`<button class="micro393" data-component393="${id}"><div><div class="kicker">${m.short}</div><b>Unavailable</b></div></button>`;const start=d[0].v,end=d.at(-1).v,min=Math.min(...d.map(x=>x.v)),max=Math.max(...d.map(x=>x.v)),span=max-min||1,a=Math.max(3,Math.round((start-min)/span*100)),b=Math.max(3,Math.round((end-min)/span*100));return`<button class="micro393" data-component393="${id}"><div><div class="kicker">${m.role}</div><b>${m.short}</b></div><div class="microChart393" aria-label="${m.short} start and end values"><div class="microCol393"><div class="microBar393" style="height:${a}%"></div><div class="microLabel393">Start</div></div><div class="microCol393"><div class="microBar393 end" style="height:${b}%"></div><div class="microLabel393">End</div></div></div><div><div class="microValues393"><span>${fmt(id,start)}</span><span>${fmt(id,end)}</span></div><div class="${z?.p>=0?'goodText':'badText'}" style="font-weight:850;margin-top:3px">${z?pct(z.p):'Unavailable'}</div></div></button>`}
'''
s=s.replace(anchor,anchor+extra)

# Replace Now page with only Regime trend + Risk/Growth/Macro cards.
start=s.find('function renderNow(){')
end=s.find('function renderRegimeTrend(){',start)
if start<0 or end<0: raise SystemExit('renderNow block missing')
new_render=r'''function renderNow(){const r=regimeSummary(state.range),rd=regimeSeries393(state.range),pc=periodChange393(rd);$('#nowSnapshot').innerHTML=`<div class="now393"><article class="card regime393" data-regime393 tabindex="0" role="button" aria-label="Open regime detail"><div class="regimeHead393"><div><div class="kicker">REGIME SENTIMENT INDEX · 0–100</div><div class="regimeMetric393"><strong>${r?r.score:'—'}</strong><span>/ 100</span><span class="chip ${r?.score>=58?'good':r?.score<=42?'bad':'neutral'}">${r?.label||'Unavailable'}</span></div><div class="muted">${H[state.range].label} · ${rd.length?dateRangeLabel392(rd,state.range):'insufficient history'} · change ${Number.isFinite(pc)?pct(pc):'Unavailable'}</div></div><div class="flow393"><b>Regime</b><span>→</span><span>Risk / Growth / Macro</span><span>→</span><span>Drivers</span></div></div><div class="chartBox"><canvas id="regimeMini393" class="chart"></canvas></div></article><div class="categoryGrid393">${['risk','growth','macro'].map(key=>{const c=CATEGORY[key],z=categoryIndex(key,state.range),d=categoryHistory393(key,state.range),chg=periodChange393(d);return`<article class="card category393" data-category393="${key}" tabindex="0" role="button" aria-label="Open ${c.name} index detail"><div class="row"><h3>${c.name}</h3><span class="chip ${z?.cls||'neutral'}">${z?.label||'Unavailable'}</span></div><div><div class="value">${z?z.score:'—'}<span class="muted" style="font-size:12px"> /100</span></div><div class="muted">${H[state.range].label} ${Number.isFinite(chg)?pct(chg):'Unavailable'}</div></div><canvas class="spark" data-cat-spark393="${key}"></canvas></article>`}).join('')}</div></div>`;setTimeout(()=>{chart($('#regimeMini393'),[{id:'regime',name:'Regime index',color:'#f3b347',data:rd}],{range:state.range,axes:true,index:true});$$('[data-cat-spark393]').forEach(c=>{const key=c.dataset.catSpark393,d=categoryHistory393(key,state.range);chart(c,[{id:key,name:`${CATEGORY[key].name} index`,color:'#6db7ff',data:d}],{range:state.range,axes:false,index:true})});const openReg=()=>openRegime393();$('[data-regime393]')?.addEventListener('click',openReg);$('[data-regime393]')?.addEventListener('keydown',e=>{if(e.key==='Enter')openReg()});$$('[data-category393]').forEach(e=>{const fn=()=>openCategory(e.dataset.category393);e.onclick=fn;e.onkeydown=ev=>{if(ev.key==='Enter')fn()}})},0);renderRegimeTrend();renderGlobalRange()}
'''
s=s[:start]+new_render+s[end:]

# Regime modal: standard full chart, horizon changes write back to global state, save to library.
insert_before='async function openCategory(key){'
regime_modal=r'''async function openRegime393(){state.detail={regime:true,range:state.range};$('#detailModal').classList.add('open');await drawRegime393()}
async function drawRegime393(){const d=regimeSeries393(state.range),r=regimeSummary(state.range),chg=periodChange393(d);$('#detailKicker').textContent='REGIME SENTIMENT INDEX';$('#detailTitle').innerHTML=`Regime · ${r?r.score:'—'}/100<div class="dateRange">${dateRangeLabel392(d,state.range)}</div>`;$('#detailRanges').innerHTML=Object.entries(H).map(([k,v])=>`<button data-regime-range393="${k}" class="${k===state.range?'active':''}">${v.label}</button>`).join('');chart($('#detailChart'),[{id:'regime',name:'Regime index',color:'#f3b347',data:d}],{range:state.range,axes:true,index:true});$('#detailStats').innerHTML=`<div class="stat"><span class="kicker">CURRENT</span><b>${r?r.score:'—'} / 100</b></div><div class="stat"><span class="kicker">SIGNAL</span><b>${r?.label||'Unavailable'}</b></div><div class="stat"><span class="kicker">${H[state.range].label} CHANGE</span><b>${Number.isFinite(chg)?pct(chg):'Unavailable'}</b></div><div class="stat"><span class="kicker">BASELINE</span><b>50 / 100</b></div>`;$('#saveDetail').textContent='Add to Library';$('#saveDetail').onclick=()=>saveAnalysis(`Regime ${H[state.range].label}`,{type:'regime',range:state.range,data:d});$$('[data-regime-range393]').forEach(b=>b.onclick=async()=>{state.range=b.dataset.regimeRange393;state.detail.range=state.range;renderGlobalRange();renderNow();await drawRegime393()})}
'''
if insert_before not in s: raise SystemExit('openCategory anchor missing')
s=s.replace(insert_before,regime_modal+insert_before,1)

# Replace category modal body with category index chart + small-multiple driver cards.
start=s.find('async function drawCategory(){')
end=s.find('async function openDetail(id){',start)
if start<0 or end<0: raise SystemExit('drawCategory block missing')
new_cat=r'''async function drawCategory(){const key=state.detail.category,c=CATEGORY[key],z=categoryIndex(key,state.range),d=categoryHistory393(key,state.range),chg=periodChange393(d);$('#detailKicker').textContent='CATEGORY INDEX';$('#detailTitle').innerHTML=`${c.name} · ${z?z.score:'—'}/100<div class="dateRange">${dateRangeLabel392(d,state.range)}</div><div class="modalSub393">${directionCopy393(key,z)}</div>`;$('#detailRanges').innerHTML=Object.entries(H).map(([k,v])=>`<button data-cr="${k}" class="${k===state.range?'active':''}">${v.label}</button>`).join('');$('#detailChart').style.display='';chart($('#detailChart'),[{id:key,name:`${c.name} index`,color:'#6db7ff',data:d}],{range:state.range,axes:true,index:true});$('#detailStats').innerHTML=`<div class="stat"><span class="kicker">INDEX</span><b>${z?z.score:'—'} / 100</b></div><div class="stat"><span class="kicker">SIGNAL</span><b><span class="chip ${z?.cls||'neutral'}">${z?.label||'Unavailable'}</span></b></div><div class="stat"><span class="kicker">${H[state.range].label} CHANGE</span><b>${Number.isFinite(chg)?pct(chg):'Unavailable'}</b></div><div style="grid-column:1/-1;min-height:180px"><div class="kicker" style="margin-bottom:6px">DRIVERS · CLICK FOR DETAIL</div><div class="microGrid393">${c.components.map(microComponent393).join('')}</div></div>`;$('#saveDetail').textContent='Add to Analysis';$('#saveDetail').onclick=()=>saveAnalysis(`${c.name} ${H[state.range].label} index`,{type:'category',category:key,range:state.range,index:z,data:d});$$('[data-cr]').forEach(b=>b.onclick=async()=>{state.range=b.dataset.cr;state.detail.range=state.range;renderGlobalRange();renderNow();await drawCategory()});$$('[data-component393]').forEach(b=>b.onclick=()=>openDetail(b.dataset.component393))}
'''
s=s[:start]+new_cat+s[end:]

# Component detail keeps standard modal/add-to-analysis and same global horizon.
s=s.replace("$('#saveDetail').onclick=()=>saveAnalysis(`${m.short} ${H[range].label} detail`,{type:'series',id,range,data:data.slice(-500)})","$('#saveDetail').textContent='Add to Analysis';$('#saveDetail').onclick=()=>saveAnalysis(`${m.short} ${H[range].label} detail`,{type:'series',id,range,data:data.slice(-500)})")

# Closing any modal preserves changed horizon and returns to the updated Now view.
s=s.replace("$('#detailClose').onclick=()=>history.back();","$('#detailClose').onclick=()=>{$('#detailModal').classList.remove('open');state.detail=null;renderGlobalRange();renderNow();if(location.hash.startsWith('#detail/'))history.replaceState(null,'','#home')};")

# Foundation should never block every launch. Attempt missing-history repair at most once per 7 days and never show a modal on ordinary startup.
old="""async function ensureFoundation392(){const need=['spy','tenYear','wti'].filter(id=>!coverage(id,'5y'));if(!need.length)return false;progress(true,'Building historical foundation','One-time five-year history repair…',0);let i=0;for(const id of need){progress(true,'Building historical foundation',`Fetching ${META[id].name}`,Math.round(i/need.length*100));try{await saveSeries(id,await yahoo(id,'5y','1d'))}catch(e){providerMark('Yahoo Finance',false,e.message);log(`${META[id].short} foundation unavailable: ${e.message}`,'error')}i++}progress(false);return true}"""
new="""async function ensureFoundation392(){const need=['spy','tenYear','wti'].filter(id=>!coverage(id,'5y'));if(!need.length){localStorage.setItem('mn393-foundation-complete','1');return false}const last=Number(localStorage.getItem('mn393-foundation-attempt')||0);if(Date.now()-last<7*864e5)return false;localStorage.setItem('mn393-foundation-attempt',String(Date.now()));for(const id of need){try{await saveSeries(id,await yahoo(id,'5y','1d'))}catch(e){providerMark('Yahoo Finance',false,e.message);log(`${META[id].short} foundation unavailable: ${e.message}`,'error')}}if(['spy','tenYear','wti'].every(id=>coverage(id,'5y')))localStorage.setItem('mn393-foundation-complete','1');return true}"""
if old not in s: raise SystemExit('foundation function anchor missing')
s=s.replace(old,new,1)

# Startup renders immediately and background repair/update does not take over the viewport.
oldboot="""(async()=>{configLoad();await openDB();await loadStored();renderAll();setSection('now');$('#status').textContent='Ready · local history';$('#dot').className='dot good';const built=await ensureFoundation392();if(built)await buildRegimeHistory();const updated=await refreshStale392(false);if(!updated&&!built){$('#status').textContent=`Current through ${expectedMarketDate392()}`}})().catch(e=>{log(e.message,'error');$('#status').textContent='Using saved market history';$('#dot').className='dot bad'});"""
newboot="""(async()=>{configLoad();await openDB();await loadStored();renderAll();setSection('now');$('#status').textContent='Ready';$('#dot').className='dot good';setTimeout(async()=>{try{const built=await ensureFoundation392();if(built)await buildRegimeHistory();await refreshStale392(false);$('#status').textContent=`Current through ${expectedMarketDate392()}`;renderAll()}catch(e){log(e.message,'error');$('#status').textContent='Using saved market history'}},250)})().catch(e=>{log(e.message,'error');$('#status').textContent='Using saved market history';$('#dot').className='dot bad'});"""
if oldboot not in s: raise SystemExit('startup boot anchor missing')
s=s.replace(oldboot,newboot,1)

p.write_text(s)
print('Patched Market Navigator to 3.9.3')
