from pathlib import Path

p=Path('market-view.html')
s=p.read_text()
if "const VERSION='3.8.2'" not in s:
    raise SystemExit('Expected Market Navigator 3.8.2 baseline')

s=s.replace('<title>Market Navigator 3.8.2</title>','<title>Market Navigator 3.9</title>')
s=s.replace('Version 3.8.2</small>','Version 3.9</small>')
s=s.replace("const VERSION='3.8.2'","const VERSION='3.9.0'")

# Make room for one authoritative global horizon control; charts/modals remain fixed-height.
s=s.replace(".viewport{height:calc(100vh - var(--head) - 106px);padding-top:10px;overflow:hidden}",
            ".globalRange{height:42px;display:grid;grid-template-columns:repeat(9,minmax(0,1fr));gap:5px;align-items:center;padding:5px 0}.globalRange button{min-width:0;border:1px solid var(--line);background:#111d31;color:var(--muted);border-radius:999px;padding:6px 4px;font-size:11px;font-weight:800}.globalRange button.active{background:#203b61;border-color:var(--accent);color:var(--text)}.viewport{height:calc(100vh - var(--head) - 148px);padding-top:8px;overflow:hidden}")
s=s.replace(".badge{font-size:10px;font-weight:850;padding:3px 7px;border-radius:999px;white-space:nowrap}",
            ".chip,.badge{display:inline-flex;align-items:center;justify-content:center;gap:4px;font-size:10px;font-weight:850;padding:4px 8px;border-radius:999px;white-space:nowrap;border:1px solid transparent}.chip.good,.badge.good{color:#9af0bd;background:#12352b;border-color:#205943}.chip.bad,.badge.bad{color:#ffb7bc;background:#3b2229;border-color:#63313b}.chip.neutral,.badge.neutral{color:#f7d782;background:#342f23;border-color:#5b4e2c}")
s=s.replace(".badge.good{color:#8ff0b9;background:#143d30}.badge.bad{color:#ffb1b5;background:#46252d}.badge.neutral{color:#ffd97c;background:#3d3626}","")
s=s.replace("@media(max-width:520px){.hero{grid-template-columns:1fr}.storyGrid,.macroGrid,.providerGrid{grid-template-columns:1fr 1fr}.stats{grid-template-columns:repeat(2,1fr)}.modal{padding:0}.modalPanel{width:100%;height:100%;border-radius:0}.analysisGrid{grid-template-columns:1fr;grid-template-rows:auto minmax(0,1fr)}}",
            "@media(max-width:520px){.globalRange{height:70px;grid-template-columns:repeat(5,minmax(0,1fr));grid-auto-rows:30px}.viewport{height:calc(100vh - var(--head) - 176px)}.hero{grid-template-columns:1fr}.storyGrid,.macroGrid,.providerGrid{grid-template-columns:1fr 1fr}.stats{grid-template-columns:repeat(2,1fr)}.modal{padding:0}.modalPanel{width:100%;height:100%;max-height:none;border-radius:0;overflow:hidden}.analysisGrid{grid-template-columns:1fr;grid-template-rows:auto minmax(0,1fr)}}")

# Insert the one horizon controller between tabs and viewport.
s=s.replace('<div id="tabs" class="tabs"></div><div class="viewport">','<div id="tabs" class="tabs"></div><div id="globalRange" class="globalRange"></div><div class="viewport">')

anchor='</script></body></html>'
if anchor not in s:
    raise SystemExit('closing script anchor missing')

override=r'''
/* 3.9: one global horizon, explicit regime semantics, category indexes, linear modal drill-down */
const CATEGORY={
  risk:{name:'Risk',desc:'Risk appetite and market stress proxy',components:['spy','wti']},
  growth:{name:'Growth',desc:'Equity direction versus cost of capital',components:['spy','tenYear']},
  macro:{name:'Macro',desc:'Rates and energy pressure',components:['tenYear','wti']}
};
function rangeStartTs(r,end=Date.now()){const h=H[r];if(!h)return null;if(h.max)return null;if(h.ytd)return new Date(new Date(end).getFullYear(),0,1).getTime();return end-(h.days||0)*864e5}
function regimeHistorySlice(r){const d=(state.regimeHistory||[]).map(x=>({t:x.t||x.ts,v:x.score})).filter(x=>Number.isFinite(x.t)&&Number.isFinite(x.v));if(!d.length)return[];if(H[r]?.intraday)return d.slice(-2);const start=rangeStartTs(r,d.at(-1).t);return start?d.filter(x=>x.t>=start):d}
function categoryIndex(key,r=state.range){const c=CATEGORY[key];let parts=[];for(const id of c.components){const z=q(id,r);if(!z||!coverage(id,r))continue;let effect=0;if(id==='spy')effect=clamp(z.p/8);if(id==='tenYear')effect=-clamp(z.p/6);if(id==='wti')effect=-clamp(z.p/12);parts.push({id,effect,p:z.p})}if(!parts.length)return null;const score=Math.round(50+35*(parts.reduce((a,b)=>a+b.effect,0)/parts.length));const s=Math.max(0,Math.min(100,score));return{score:s,label:s>=58?'Positive':s<=42?'Negative':'Neutral',cls:s>=58?'good':s<=42?'bad':'neutral',parts}}
function regimeSummary(r=state.range){const current=regimeAt(Date.now());if(!current)return null;const hist=regimeHistorySlice(r),start=hist[0]?.v,end=hist.at(-1)?.v??current.score;const periodPct=Number.isFinite(start)&&start!==0?(end/start-1)*100:null;const basePct=(current.score/50-1)*100;return{...current,periodPct,basePct,start,end}}
function renderGlobalRange(){const e=$('#globalRange');if(!e)return;e.innerHTML=Object.entries(H).map(([k,v])=>`<button data-global-range="${k}" class="${k===state.range?'active':''}">${v.label}</button>`).join('');$$('[data-global-range]').forEach(b=>b.onclick=async()=>{state.range=b.dataset.globalRange;if(!H[state.range].intraday&&['spy','tenYear','wti'].some(id=>!coverage(id,state.range)))await foundation();if(state.detail){state.detail.range=state.range;await drawDetail()}renderAll();renderGlobalRange()})}
function categoryCard(key){const c=CATEGORY[key],z=categoryIndex(key,state.range);return`<article class="card storyCard" data-category="${key}"><div class="row"><div><div class="kicker">CATEGORY INDEX</div><h3>${c.name}</h3></div><span class="chip ${z?.cls||'neutral'}">${z?.label||'Unavailable'}</span></div><div><div class="value">${z?z.score:'—'}<span class="muted" style="font-size:13px"> / 100</span></div><div class="muted tiny">${H[state.range].label} · baseline 50 · ${z?`${z.score>=50?'+':''}${((z.score/50-1)*100).toFixed(1)}% vs baseline`:'insufficient data'}</div></div><div class="muted" style="align-self:center">${c.desc}</div><div class="meta">Open to inspect ${c.components.map(id=>META[id].short).join(' + ')}</div></article>`}
function renderNow(){const r=regimeSummary(state.range);$('#nowSnapshot').innerHTML=`<div class="snapshot"><div class="hero"><article class="card regime" data-regime-open><div class="gauge"><strong>${r?r.score:'—'}</strong></div><div><div class="kicker">REGIME SENTIMENT INDEX · 0–100</div><h2>${r?r.label:'Unavailable'}</h2><div class="muted">Neutral baseline 50 · ${r?`${r.basePct>=0?'+':''}${r.basePct.toFixed(1)}% vs baseline`:'insufficient history'} · ${H[state.range].label} change ${r&&Number.isFinite(r.periodPct)?pct(r.periodPct):'Unavailable'}</div></div></article><article class="card"><div class="kicker">HOW TO READ IT</div><h2>One horizon controls the entire view</h2><p class="muted">Regime is a sentiment index, not a portfolio value. Risk, Growth and Macro are component indexes on the same 0–100 / baseline-50 convention.</p></article></div><div class="storyGrid">${['risk','growth','macro'].map(categoryCard).join('')}</div></div>`;setTimeout(()=>{$$('[data-category]').forEach(e=>e.onclick=()=>openCategory(e.dataset.category));$('[data-regime-open]')?.addEventListener('click',()=>setSection('now','nowTrend'))},0);renderRegimeTrend();renderGlobalRange()}
function renderRegimeTrend(){const d=regimeHistorySlice(state.range),z=regimeSummary(state.range);$('#nowTrend').innerHTML=`<div class="snapshot"><article class="card" style="height:100%;display:grid;grid-template-rows:auto minmax(0,1fr) auto;overflow:hidden"><div class="row"><div><div class="kicker">REGIME SENTIMENT INDEX · ${H[state.range].label}</div><h2>${z?`${z.score}/100 · ${z.label}`:'Unavailable'}</h2><div class="muted tiny">Baseline 50 · ${z?`${z.basePct>=0?'+':''}${z.basePct.toFixed(1)}% vs baseline`:''} · period ${z&&Number.isFinite(z.periodPct)?pct(z.periodPct):'Unavailable'}</div></div><span class="chip ${z?.score>=58?'good':z?.score<=42?'bad':'neutral'}">${z?.score>=58?'Positive':z?.score<=42?'Negative':'Neutral'}</span></div><div class="chartBox"><canvas id="regimeChart" class="chart"></canvas></div><div class="actions"><button class="btn primary" id="saveRegime">Save to Analysis</button></div></article></div>`;setTimeout(()=>{chart($('#regimeChart'),[{id:'spy',name:'Regime index',color:'#6db7ff',data:d}],{range:state.range,axes:true,normalized:false});$('#saveRegime').onclick=()=>saveAnalysis(`Regime ${H[state.range].label}`,{type:'regime',range:state.range,data:d})},0);renderGlobalRange()}
async function openCategory(key){state.detail={category:key,range:state.range};$('#saveDetail').style.display='';$('#detailModal').classList.add('open');await drawCategory()}
async function drawCategory(){const key=state.detail.category,c=CATEGORY[key],z=categoryIndex(key,state.range);$('#detailKicker').textContent='CATEGORY INDEX';$('#detailTitle').textContent=`${c.name} · ${z?z.score:'—'}/100`;$('#detailRanges').innerHTML=Object.entries(H).map(([k,v])=>`<button data-cr="${k}" class="${k===state.range?'active':''}">${v.label}</button>`).join('');const list=normalize(c.components.filter(id=>META[id]?.symbol),state.range);chart($('#detailChart'),list,{range:state.range,axes:true,normalized:true});$('#detailStats').innerHTML=`<div class="stat"><span class="kicker">INDEX</span><b>${z?z.score:'—'} / 100</b></div><div class="stat"><span class="kicker">SIGNAL</span><b><span class="chip ${z?.cls||'neutral'}">${z?.label||'Unavailable'}</span></b></div>${c.components.map(id=>{const qv=q(id,state.range);return`<button class="stat" data-component="${id}" style="color:inherit;text-align:left;cursor:pointer"><span class="kicker">${META[id].short} · ${H[state.range].label}</span><b>${qv?pct(qv.p):'Unavailable'}</b></button>`}).join('')}`;$$('[data-cr]').forEach(b=>b.onclick=async()=>{state.range=b.dataset.cr;state.detail.range=state.range;renderGlobalRange();await drawCategory();renderAll()});$$('[data-component]').forEach(b=>b.onclick=()=>openDetail(b.dataset.component));$('#saveDetail').onclick=()=>saveAnalysis(`${c.name} ${H[state.range].label} category`,{type:'category',category:key,range:state.range,index:z,components:c.components})}
async function openDetail(id){state.detail={id,range:state.range};$('#saveDetail').style.display='';$('#detailModal').classList.add('open');await drawDetail()}
async function drawDetail(){const {id}=state.detail,range=state.range,m=META[id];state.detail.range=range;$('#detailKicker').textContent=m.role;$('#detailTitle').textContent=m.name;$('#detailRanges').innerHTML=Object.entries(H).map(([k,v])=>`<button data-dr="${k}" class="${k===range?'active':''}">${v.label}</button>`).join('');let data;if(H[range].intraday&&m.symbol){if(!state.intraday[`${id}:${range}`]){progress(true,'Loading intraday data',`${m.name} · ${H[range].label}`,30);try{state.intraday[`${id}:${range}`]=await yahoo(id,H[range].range,H[range].interval)}catch(e){toast('Intraday data unavailable')}progress(false)}data=state.intraday[`${id}:${range}`]||[]}else{if(m.symbol&&!coverage(id,range)){progress(true,'Extending history',`${m.name} · ${H[range].label}`,30);try{await saveSeries(id,await yahoo(id,range==='5y'||range==='max'?'5y':'1y','1d'))}catch(e){toast('Historical data unavailable')}progress(false)}data=rangeData(id,range)}chart($('#detailChart'),[{id,name:m.short,color:m.color,data}],{range,axes:true});const z=quoteAny(data),start=data[0],end=data.at(-1);$('#detailStats').innerHTML=`<div class="stat"><span class="kicker">LATEST</span><b>${end?fmt(id,end.v):'Unavailable'}</b></div><div class="stat"><span class="kicker">${H[range].label} CHANGE</span><b>${z?pct(z.p):'Unavailable'}</b></div><div class="stat"><span class="kicker">OBS</span><b>${data.length}</b></div><div class="stat"><span class="kicker">FROM</span><b>${start?new Date(start.t).toLocaleDateString():'—'}</b></div><div class="stat"><span class="kicker">TO</span><b>${end?new Date(end.t).toLocaleDateString():'—'}</b></div>`;$$('[data-dr]').forEach(b=>b.onclick=async()=>{state.range=b.dataset.dr;state.detail.range=state.range;renderGlobalRange();renderAll();await drawDetail()});$('#saveDetail').onclick=()=>saveAnalysis(`${m.short} ${H[range].label} detail`,{type:'series',id,range,data:data.slice(-500)})}
const _renderAll390=renderAll;renderAll=function(){_renderAll390();renderGlobalRange()};
setTimeout(()=>{renderGlobalRange();renderAll()},0);
'''
s=s.replace(anchor,override+'\n</script></body></html>')
p.write_text(s)
print('Patched Market Navigator to 3.9.0')
