from pathlib import Path

p=Path('project.html')
s=p.read_text()
assert 'Build: 2026.08.11.4.5' in s
s=s.replace('Build: 2026.08.11.4.5','Build: 2026.08.11.4.10',1)
s=s.replace("BUILD_ID='2026.08.11.4.5'","BUILD_ID='2026.08.11.4.10'",1)

api="const FS_API='/report/api/sot/fs',PROJECT_API='/report/api/sot/projects',REPORT_API='/report/api/sot/reports';"
assert api in s
s=s.replace(api,api+"\nconst STATIC_PREVIEW=location.hostname.endsWith('.github.io');",1)
s=s.replace('async function checkServices(){try{',"async function checkServices(){if(STATIC_PREVIEW){state.api={live:false,version:'',build:'',engineReady:false,engineReason:'Static preview'};state.fsLive=false;state.roots=[];updateChrome();return}try{",1)
s=s.replace('function serviceBanner(){if(!state.api.live)',"function serviceBanner(){if(STATIC_PREVIEW)return`<div class=\"callout\"><strong>Static preview.</strong> WSL storage is hidden here. Use This device, or test WSL storage on the OpenClaw /report URL.</div>`;if(!state.api.live)",1)

css='''
/* owner mobile rebuild .4.10 */
@media(max-width:900px){
.app{grid-template-columns:1fr!important}
.sidebar{position:fixed!important;left:0!important;right:0!important;bottom:0!important;top:auto!important;height:66px!important;z-index:80!important;padding:6px!important;display:block!important}
.brand,.sidefoot{display:none!important}
.nav{display:grid!important;grid-template-columns:repeat(3,1fr)!important;gap:5px!important}
.nav button{display:block!important;text-align:center!important;padding:8px 4px!important;font-size:12px!important;color:#d7deea!important}
.nav .txt{display:block!important;color:inherit!important;font-size:12px!important;opacity:1!important}
.main{padding-bottom:68px!important}}
.s410{width:min(1320px,97vw);height:min(800px,91vh);max-height:94vh;min-height:580px;overflow:hidden;border-radius:15px}
.s410-grid{display:grid;grid-template-columns:230px minmax(430px,1fr) 330px;height:calc(100% - 76px);min-height:0}
.s410-left,.s410-center,.s410-right{min-width:0;min-height:0;background:#fff}.s410-left{border-right:1px solid var(--line);display:grid;grid-template-rows:auto minmax(0,1fr);background:#fafbfc}.s410-center{display:grid;grid-template-rows:auto minmax(0,1fr) auto}.s410-right{border-left:1px solid var(--line);display:grid;grid-template-rows:auto minmax(0,1fr) auto;background:#fbfcfd}
.s410-title{padding:15px 14px 9px;font-size:11px;font-weight:850;letter-spacing:.055em;text-transform:uppercase;color:#667085}.s410-places{overflow:auto;padding:4px 9px 12px}.s410-place{width:100%;border:0;background:transparent;text-align:left;border-radius:9px;padding:11px 9px;margin:2px 0;color:#273345;font-weight:750}.s410-place:hover,.s410-place.active{background:#edf1f5}.s410-place small{display:block;color:#7b8798;font-weight:500;margin-top:3px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.s410-tools{display:grid;grid-template-columns:auto auto minmax(130px,1fr) auto;gap:8px;align-items:center;padding:10px;border-bottom:1px solid var(--line);background:#fbfcfd}.s410-path{height:38px;display:flex;align-items:center;border:1px solid #d6dbe3;border-radius:8px;padding:0 10px;background:#fff;font:12px ui-monospace,SFMono-Regular,Consolas,monospace;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.s410-add{white-space:nowrap;background:#526174!important;border-color:#526174!important;color:#fff!important}.s410-add:disabled{opacity:.42}
.s410-head,.s410-row{display:grid;grid-template-columns:34px minmax(150px,1fr) 72px;gap:8px;align-items:center}.s410-head{position:sticky;top:0;z-index:3;padding:8px 12px;background:#f8fafc;border-bottom:1px solid var(--line);font-size:11px;font-weight:800;color:#667085}.s410-browser{overflow:auto;min-height:0}.s410-row{min-height:47px;padding:8px 12px;border-bottom:1px solid #edf0f4}.s410-row:hover{background:#fafbfd}.s410-check{width:16px;height:16px;margin:auto;accent-color:#59677a}.s410-open{border:0;background:transparent;text-align:left;padding:0;color:#273345;font-weight:620;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.s410-open.volume{font-weight:800}.s410-kind{font-size:11px;color:#98a2b3;text-align:right}.s410-status{display:flex;justify-content:space-between;gap:10px;padding:8px 12px;border-top:1px solid var(--line);background:#fafbfc;color:#667085;font-size:11px}
.s410-right-head{padding:16px 14px;border-bottom:1px solid var(--line)}.s410-selected{overflow:auto;min-height:0;padding:9px 11px}.s410-card{display:grid;grid-template-columns:minmax(0,1fr) 26px;gap:8px;align-items:start;border:1px solid #dfe4eb;background:#fff;border-radius:10px;padding:10px;margin-bottom:8px;cursor:pointer}.s410-card:hover{background:#f8fafc}.s410-pathtext{font:11px ui-monospace,SFMono-Regular,Consolas,monospace;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.s410-note{font-size:11px;color:#667085;margin-top:4px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.s410-x{border:0;background:transparent;color:#667085;font-size:18px}.s410-actions{border-top:1px solid var(--line);padding:11px;display:grid;gap:8px;background:#fff}.s410-empty{padding:34px 16px;text-align:center;color:#667085;font-size:12px}.s410-empty strong{display:block;color:#273345;font-size:14px;margin-bottom:5px}
@media(max-width:1050px){.s410-grid{grid-template-columns:22% 45% 33%}.s410-tools{grid-template-columns:auto auto minmax(0,1fr)}.s410-path{grid-column:1/-1}.s410-add{grid-column:1/-1;width:100%}.s410{width:98vw}}
@media(max-width:760px){.s410{height:92vh;min-height:0}.s410-grid{grid-template-columns:24% 43% 33%}.s410-title{padding:10px 7px 6px;font-size:10px}.s410-places{padding:2px 5px}.s410-place{padding:8px 5px;font-size:12px}.s410-place small{font-size:10px}.s410-head,.s410-row{grid-template-columns:26px minmax(90px,1fr) 50px;padding-left:6px;padding-right:6px;gap:4px}.s410-open{font-size:11px}.s410-kind{font-size:9px}.s410-right-head{padding:10px 7px}.s410-selected{padding:6px}.s410-card{padding:8px 6px}.s410-pathtext,.s410-note{font-size:9px}.s410-actions{padding:7px}.s410-actions .btn{padding:8px 5px;font-size:11px}.s410-tools{padding:6px;gap:5px}.s410-tools .btn{font-size:10px;padding:6px}.s410-path{font-size:10px;height:34px}}
'''
s=s.replace('</style>',css+'\n</style>',1)

fn='''
function openSourceExplorer410(){
 const root=$('#modalRoot');let active=null,current=null,folders=[],files=[],history=[];let staged=[...state.intake.sources];const checked=new Set();const original=state.intake.sources.map(sourceKey).sort().join('\\n');
 root.innerHTML=`<div class="modalback"><div class="modal s410"><div class="modalhead"><div><h3>Add locations</h3><div class="subtle">Select a location, choose the whole volume or browse folders, then add checked sources.</div></div><button class="close" id="x">×</button></div><div class="s410-grid"><aside class="s410-left"><div class="s410-title">Locations</div><div class="s410-places" id="places"></div></aside><section class="s410-center"><div class="s410-tools"><button class="btn small" id="up" disabled>↑ Up</button><button class="btn small" id="rescan">↻ Rescan</button><div class="s410-path" id="path">Select a location</div><button class="btn s410-add" id="add" disabled>＋ Add to project</button></div><div class="s410-browser" id="browser"><div class="s410-empty"><strong>Select a location</strong>The location will appear here as a selectable row.</div></div><div class="s410-status"><strong id="status">Nothing selected</strong><span id="count">0 items</span></div></section><aside class="s410-right"><div class="s410-right-head"><strong>Added to project <span class="badge" id="addedCount">0</span></strong><div class="subtle">Tap a source tile to add an optional note.</div></div><div class="s410-selected" id="selected"></div><div class="s410-actions"><button class="btn primary" id="save">Save selections</button><button class="btn" id="cancel">Cancel</button></div></aside></div></div></div>`;
 const srcPath=x=>typeof x==='string'?x:(x.path||x.locator||sourceDisplay(x));const srcNote=x=>typeof x==='object'&&x?String(x.note||''):'';const mk=path=>({source_type:'wsl_path',path,operator_label:path.split('/').filter(Boolean).pop()||path,note:''});const dirty=()=>staged.map(sourceKey).sort().join('\\n')!==original;const close=force=>{if(!force&&dirty()&&!confirm('Discard the source selections you have not saved?'))return;root.innerHTML=''};$('#x').onclick=()=>close(false);$('#cancel').onclick=()=>close(false);
 function renderPlaces(){let html='';if(!STATIC_PREVIEW&&state.fsLive)html+=state.roots.map(r=>`<button class="s410-place ${active?.path===r.path?'active':''}" data-root="${esc(r.path)}">▣ ${esc(r.label)}<small>${esc(r.path)}</small></button>`).join('');if(HAS_DIRECTORY_PICKER||HAS_DIRECTORY_INPUT)html+=`<button class="s410-place" id="device">▯ This device<small>Browser-authorized folder</small></button>`;if(!html)html='<div class="s410-empty"><strong>No accessible locations</strong>No server-backed storage is available on this host.</div>';$('#places').innerHTML=html;document.querySelectorAll('[data-root]').forEach(b=>b.onclick=()=>selectRoot(state.roots.find(r=>r.path===b.dataset.root)));$('#device')?.addEventListener('click',showDevice)}
 function selectRoot(r){active=r;current=r.path;history=[r.path];folders=[];files=[];checked.clear();renderPlaces();renderRootRow();updateAdd()}
 function renderRootRow(){if(!active)return;$('#path').textContent=active.path;$('#up').disabled=true;$('#status').textContent=active.label;$('#count').textContent='1 volume';$('#browser').innerHTML=`<div class="s410-head"><span></span><span>Name</span><span>Type</span></div><div class="s410-row"><input class="s410-check" id="rootCheck" type="checkbox"><button class="s410-open volume" id="openRoot">▣ ${esc(active.label)}</button><span class="s410-kind">Volume</span></div>`;$('#rootCheck').onchange=e=>toggle(active.path,e.target.checked);$('#openRoot').onclick=()=>load(active.path)}
 async function load(path){$('#browser').innerHTML='<div class="s410-empty">Loading…</div>';try{const d=await apiFs(path);current=d.path||path;folders=d.folders||[];files=d.files||[];$('#path').textContent=current;$('#up').disabled=history.length<=1;renderDir()}catch(e){$('#browser').innerHTML=`<div class="s410-empty"><strong>Unable to browse</strong>${esc(e.message)}</div>`;toast(e.message,'error')}}
 function renderDir(){const fr=folders.map(n=>{const pp=joinPath(current,n);return`<div class="s410-row"><input class="s410-check" type="checkbox" data-check="${esc(pp)}" ${checked.has(pp)?'checked':''}><button class="s410-open" data-drill="${esc(n)}">▱ ${esc(n)}</button><span class="s410-kind">Folder</span></div>`}).join('');const fi=files.map(n=>`<div class="s410-row"><span></span><span class="s410-open" style="font-weight:500">▧ ${esc(n)}</span><span class="s410-kind">File</span></div>`).join('');$('#browser').innerHTML='<div class="s410-head"><span></span><span>Name</span><span>Type</span></div>'+(fr+fi||'<div class="s410-empty">This folder is empty.</div>');$('#status').textContent=current;$('#count').textContent=`${folders.length+files.length} items`;document.querySelectorAll('[data-check]').forEach(c=>c.onchange=e=>toggle(c.dataset.check,e.target.checked));document.querySelectorAll('[data-drill]').forEach(b=>b.onclick=()=>{const next=joinPath(current,b.dataset.drill);history.push(next);load(next)})}
 function toggle(path,on){on?checked.add(path):checked.delete(path);updateAdd()}function updateAdd(){const b=$('#add');b.disabled=!checked.size;b.textContent=checked.size?`＋ Add to project (${checked.size})`:'＋ Add to project'}
 function renderSelected(){$('#addedCount').textContent=staged.length;$('#selected').innerHTML=staged.length?staged.map((x,i)=>{const full=srcPath(x),note=srcNote(x);return`<div class="s410-card" data-note="${i}" title="${esc(full)}"><div><div class="s410-pathtext">${esc(full)}</div><div class="s410-note">${note?esc(note):'Add optional note…'}</div></div><button class="s410-x" data-rm="${i}">×</button></div>`}).join(''):'<div class="s410-empty"><strong>Nothing added yet</strong>Selected sources will appear here.</div>';document.querySelectorAll('[data-note]').forEach(c=>c.onclick=e=>{if(e.target.closest('[data-rm]'))return;editNote(Number(c.dataset.note))});document.querySelectorAll('[data-rm]').forEach(b=>b.onclick=e=>{e.stopPropagation();staged.splice(Number(b.dataset.rm),1);renderSelected()})}
 function editNote(i){const full=srcPath(staged[i]),old=srcNote(staged[i]);const note=prompt(`Optional note for:\n${full}`,old);if(note===null)return;staged[i]=typeof staged[i]==='string'?{...mk(staged[i]),note:note.trim()}:{...staged[i],note:note.trim()};renderSelected()}
 $('#add').onclick=()=>{for(const pp of checked)if(!staged.some(x=>srcPath(x)===pp))staged.push(mk(pp));checked.clear();updateAdd();if(active&&history.length===1)renderRootRow();else if(active)renderDir();renderSelected()};$('#up').onclick=()=>{if(history.length<=1){renderRootRow();return}history.pop();if(history.length===1){renderRootRow();return}load(history[history.length-1])};$('#rescan').onclick=()=>STATIC_PREVIEW?renderPlaces():(active&&history.length>1?load(current):checkServices().then(renderPlaces));$('#save').onclick=()=>{state.intake.sources=staged;close(true);renderIntake();toast(`${staged.length} location${staged.length===1?'':'s'} saved to draft.`)};
 function showDevice(){active=null;checked.clear();updateAdd();$('#path').textContent='This device';$('#status').textContent='Browser-local storage';$('#count').textContent='';$('#browser').innerHTML='<div class="s410-empty"><strong>This device</strong><button class="btn" id="choose">Choose folder…</button><div style="margin-top:8px">Your browser must authorize a folder before it can be added.</div></div>';$('#choose').onclick=pickDevice}async function pickDevice(){const src=await pickLocalDeviceSource();if(src&&!staged.some(x=>sourceKey(x)===sourceKey(src))){staged.push({...src,note:''});renderSelected()}}
 renderPlaces();renderSelected();updateAdd();}
'''
marker='function parentPath(path,root)'
assert marker in s
s=s.replace(marker,fn+'\n'+marker,1)
old="function openExplorer(mode){const root=$('#modalRoot');"
assert old in s
s=s.replace(old,"function openExplorer(mode){if(mode==='source')return openSourceExplorer410();const root=$('#modalRoot');",1)
p.write_text(s)

g=Path('project-backlog.md')
text=g.read_text()
gate='''\n## Owner gate — build 2026.08.11.4.9 FAILED\n\nOwner mobile screenshot rejected `.4.9`: the left navigation rail was unreadable and the three-panel Add Locations layout overlapped controls and headings. `.4.9` is not an implementation baseline. `.4.10` is rebuilt from exact `.4.5` UI bytes. At phone/tablet widths the portal navigation becomes a readable bottom bar; the modal retains three simultaneous panels with proportional widths and no cross-panel toolbar overlap.\n\n'''
if 'Owner gate — build 2026.08.11.4.9 FAILED' not in text:text=text.replace('# 2. RELEASE CHAIN',gate+'# 2. RELEASE CHAIN',1)
g.write_text(text)
