from pathlib import Path

p=Path('project.html')
s=p.read_text()
if 'Build: 2026.08.11.4.5' not in s:
    raise SystemExit('FAIL: exact .4.5 baseline required')
s=s.replace('Build: 2026.08.11.4.5','Build: 2026.08.11.4.8',1)
s=s.replace("BUILD_ID='2026.08.11.4.5'","BUILD_ID='2026.08.11.4.8'",1)

css=r'''
/* APPROVED SOURCE PICKER · screenshot layout · build 2026.08.11.4.8 */
.sshot-modal{width:min(1380px,97vw);height:min(860px,92vh);max-width:97vw;max-height:92vh;min-height:620px;overflow:hidden;border-radius:14px;background:#fff;display:grid;grid-template-rows:auto auto minmax(0,1fr);box-shadow:0 28px 90px rgba(16,24,40,.28)}
.sshot-modal .modalhead{padding:20px 28px 18px;border-bottom:1px solid #e3e7ed;background:#fff}.sshot-modal .modalhead h3{font-size:24px;letter-spacing:-.02em;margin:0 0 2px}.sshot-modal .modalhead .subtle{font-size:14px;color:#475467}
.sshot-toolbar{display:grid;grid-template-columns:auto auto minmax(250px,1fr) auto auto 42px;gap:12px;align-items:center;padding:15px 18px;border-bottom:1px solid #e3e7ed;background:#fff}.sshot-toolbar .btn{height:46px;padding:0 18px;border-radius:9px;font-size:14px}.sshot-path{height:46px;display:flex;align-items:center;padding:0 16px;border:1px solid #d7dde5;border-radius:9px;background:#fff;font:14px ui-monospace,SFMono-Regular,Consolas,monospace;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.sshot-add{min-width:210px}.sshot-help{width:42px;height:42px;border:0;background:transparent;border-radius:50%;font-size:20px;color:#344054}.sshot-help:hover{background:#f2f4f7}
.sshot-grid{display:grid;grid-template-columns:290px minmax(560px,1fr) 320px;min-height:0;height:100%}.sshot-locations{border-right:1px solid #e3e7ed;display:grid;grid-template-rows:auto minmax(0,1fr) auto;background:#fff;min-height:0}.sshot-pane-title{padding:20px 28px 12px;font-size:12px;font-weight:800;letter-spacing:.04em;color:#344054}.sshot-location-list{overflow:auto;padding:0 18px 10px}.sshot-location{display:grid;grid-template-columns:26px 26px minmax(0,1fr);gap:8px;align-items:center;min-height:62px;padding:6px 10px;border-radius:8px;margin:2px 0}.sshot-location.active{background:#f0f2f5;box-shadow:inset 3px 0 0 #667085}.sshot-location:hover{background:#f7f8fa}.sshot-location input{width:16px;height:16px;accent-color:#475467}.sshot-location button{border:0;background:transparent;text-align:left;padding:0;color:#1d2939;min-width:0}.sshot-location strong{display:block;font-size:14px}.sshot-location small{display:block;font-size:11px;color:#667085;margin-top:3px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.sshot-locicon{font-size:18px;text-align:center;color:#344054}.sshot-how{margin:12px 18px 18px;border:1px solid #e3e7ed;border-radius:10px;padding:18px;font-size:12px;color:#475467;line-height:1.55;background:#fff}.sshot-how strong{display:block;color:#1d2939;margin-bottom:10px;font-size:13px}.sshot-how .learn{display:flex;justify-content:space-between;margin-top:18px;color:#344054;font-weight:650}
.sshot-center{display:grid;grid-template-rows:auto minmax(0,1fr) auto;min-width:0;min-height:0;background:#fff}.sshot-table-head,.sshot-row{display:grid;grid-template-columns:minmax(220px,1fr) 110px 95px 170px 38px;gap:8px;align-items:center}.sshot-table-head{padding:14px 18px;border-bottom:1px solid #e3e7ed;color:#344054;font-size:12px;font-weight:700;background:#fff}.sshot-sort{border:0;background:transparent;padding:0;text-align:left;font-weight:700;color:#344054}.sshot-list{overflow:auto;min-height:0;scrollbar-gutter:stable}.sshot-row{min-height:49px;padding:0 18px;border-bottom:1px solid #edf0f3;font-size:13px}.sshot-row:hover{background:#fafbfc}.sshot-name{border:0;background:transparent;text-align:left;padding:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;color:#1d2939}.sshot-name.folder{font-weight:560;cursor:pointer}.sshot-meta{color:#475467}.sshot-plus{border:0;background:transparent;font-size:24px;line-height:1;color:#344054;width:34px;height:34px;border-radius:7px}.sshot-plus:hover{background:#f0f2f5}.sshot-footer{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:14px 18px;border-top:1px solid #e3e7ed;background:#fff;font-size:12px;color:#475467}.sshot-footer strong{font:13px ui-monospace,SFMono-Regular,Consolas,monospace;color:#344054}.sshot-items{display:flex;align-items:center;gap:8px}
.sshot-selected{border-left:1px solid #e3e7ed;display:grid;grid-template-rows:auto minmax(0,1fr) auto;background:#fff;min-height:0}.sshot-selected-head{padding:22px 22px 14px}.sshot-selected-head strong{font-size:17px}.sshot-selected-head .subtle{font-size:12px;margin-top:3px}.sshot-selected-list{overflow:auto;padding:8px 18px}.sshot-selected-item{display:grid;grid-template-columns:28px minmax(0,1fr) 26px;gap:9px;align-items:center;border:1px solid #dde2e8;border-radius:10px;padding:14px 12px;margin-bottom:9px;background:#fff}.sshot-selected-item .loc{font:12px ui-monospace,SFMono-Regular,Consolas,monospace;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.sshot-selected-item button{border:0;background:transparent;font-size:20px;color:#344054}.sshot-actions{border-top:1px solid #e3e7ed;padding:14px 18px 18px;display:grid;gap:10px}.sshot-actions .btn{height:48px;background:#fff}.sshot-actions .btn.primary{background:#fff;color:#1d2939;border-color:#cfd5dd}.sshot-empty{padding:38px 18px;color:#667085;text-align:center;font-size:12px}
@media(max-width:1050px){.sshot-grid{grid-template-columns:230px minmax(480px,1fr) 280px}.sshot-table-head,.sshot-row{grid-template-columns:minmax(190px,1fr) 90px 80px 135px 34px}.sshot-toolbar{grid-template-columns:auto auto minmax(180px,1fr) auto}.sshot-toolbar #newFolder,.sshot-toolbar .sshot-help{display:none}}
@media(max-width:760px){.sshot-modal{width:98vw;height:94vh;max-height:94vh;min-height:0}.sshot-toolbar{grid-template-columns:auto auto minmax(130px,1fr);padding:10px;gap:7px}.sshot-toolbar #addSelected{grid-column:1/-1}.sshot-grid{grid-template-columns:1fr;grid-template-rows:170px minmax(330px,1fr) 230px}.sshot-locations{border-right:0;border-bottom:1px solid #e3e7ed}.sshot-location-list{display:flex;overflow:auto}.sshot-location{min-width:160px}.sshot-how{display:none}.sshot-selected{border-left:0;border-top:1px solid #e3e7ed}.sshot-table-head,.sshot-row{grid-template-columns:minmax(180px,1fr) 80px 34px}.sshot-table-head>:nth-child(3),.sshot-table-head>:nth-child(4),.sshot-row>:nth-child(3),.sshot-row>:nth-child(4){display:none}}
'''
s=s.replace('</style>',css+'\n</style>',1)

fn=r'''
function openApprovedSourcePicker(){
  const root=$('#modalRoot');
  let selectedRoot=null,current=null,folders=[],files=[],history=[],sortDir=1;
  let staged=[...state.intake.sources];
  const checkedVolumes=new Set();
  const initialKeys=state.intake.sources.map(sourceKey).sort().join('\n');
  root.innerHTML=`<div class="modalback"><div class="sshot-modal"><div class="modalhead"><div><h3>Add locations</h3><div class="subtle">Browse and choose what to add to your project. Locations stay visible on the right until you save.</div></div><button class="close" id="x">×</button></div><div class="sshot-toolbar"><button class="btn" id="up">↑&nbsp; Up</button><button class="btn" id="rescan">↻&nbsp; Rescan</button><div class="sshot-path" id="path">Select a location</div><button class="btn sshot-add" id="addSelected">＋&nbsp; Add to project</button><button class="btn" id="newFolder">＋&nbsp; New folder</button><button class="sshot-help" id="helpBtn" title="How it works">?</button></div><div class="sshot-grid"><aside class="sshot-locations"><div class="sshot-pane-title">LOCATIONS</div><div class="sshot-location-list" id="placesList"></div><div class="sshot-how" id="howCard"><strong>ⓘ&nbsp; How it works</strong>Add entire volumes or individual folders to your project. Click a location or folder name to browse it; use its checkbox or + control to select it.<div class="learn"><span>Learn more</span><span>→</span></div></div></aside><section class="sshot-center"><div class="sshot-table-head"><button class="sshot-sort" id="sortName">Name ↑</button><span>Type</span><span>Size</span><span>Modified</span><span></span></div><div class="sshot-list" id="browserList"><div class="sshot-empty">Choose a location on the left.</div></div><div class="sshot-footer"><strong id="footerPath">—</strong><span class="sshot-items">▱ <span id="itemCount">0 items</span></span></div></section><aside class="sshot-selected"><div class="sshot-selected-head"><strong>Added to project <span class="badge" id="selectedCount">0</span></strong><div class="subtle">Review before saving</div></div><div class="sshot-selected-list" id="selectedList"></div><div class="sshot-actions"><button class="btn primary" id="saveLocations">▣&nbsp; Save selections</button><button class="btn" id="cancelLocations">Cancel</button></div></aside></div></div></div>`;
  const hasUnsaved=()=>staged.map(sourceKey).sort().join('\n')!==initialKeys;
  const close=(force=false)=>{if(!force&&hasUnsaved()&&!confirm('Discard the source selections you have not saved?'))return false;root.innerHTML='';return true};
  $('#x').onclick=()=>close(false);
  function stagedHas(path){const key=sourceKey(path);return staged.some(x=>sourceKey(x)===key)}
  function stage(path){if(path&&!stagedHas(path)){staged.push(path);renderSelected();return true}return false}
  function renderPlaces(){
    $('#placesList').innerHTML=state.roots.map(r=>`<div class="sshot-location ${selectedRoot?.path===r.path?'active':''}"><input type="checkbox" data-volume-check="${esc(r.path)}" ${checkedVolumes.has(r.path)?'checked':''} aria-label="Select ${esc(r.label)} volume"><span class="sshot-locicon">▣</span><button data-place="${esc(r.path)}"><strong>${esc(r.label)}</strong><small>${esc(r.path)}</small></button></div>`).join('')+((HAS_DIRECTORY_PICKER||HAS_DIRECTORY_INPUT)?`<div class="sshot-location"><span></span><span class="sshot-locicon">▯</span><button id="devicePlace"><strong>This device</strong><small>Local browser storage</small></button></div>`:'');
    document.querySelectorAll('[data-volume-check]').forEach(c=>c.onchange=e=>{if(e.target.checked)checkedVolumes.add(c.dataset.volumeCheck);else checkedVolumes.delete(c.dataset.volumeCheck)});
    document.querySelectorAll('[data-place]').forEach(b=>b.onclick=()=>selectRoot(state.roots.find(r=>r.path===b.dataset.place)));
    $('#devicePlace')?.addEventListener('click',pickLocalSourceAndStage);
  }
  function renderSelected(){
    $('#selectedCount').textContent=String(staged.length);
    $('#selectedList').innerHTML=staged.length?staged.map((src,i)=>`<div class="sshot-selected-item"><span>▱</span><div class="loc">${esc(sourceDisplay(src))}</div><button data-unselect="${i}" title="Remove">×</button></div>`).join(''):'<div class="sshot-empty">Nothing added yet.</div>';
    document.querySelectorAll('[data-unselect]').forEach(b=>b.onclick=()=>{staged.splice(Number(b.dataset.unselect),1);renderSelected()});
  }
  async function selectRoot(r){if(!r)return;selectedRoot=r;current=r.path;history=[current];renderPlaces();await load(current)}
  async function load(path){if(!selectedRoot)return;$('#browserList').innerHTML='<div class="sshot-empty">Loading…</div>';try{const d=await apiFs(path);current=d.path||path;folders=d.folders||[];files=d.files||[];$('#path').textContent=current;$('#footerPath').textContent=current;$('#up').disabled=history.length<=1;renderRows()}catch(e){$('#browserList').innerHTML=`<div class="sshot-empty"><strong>Unable to browse</strong><br>${esc(e.message)}</div>`;toast(e.message,'error')}}
  function renderRows(){const fs=[...folders].sort((a,b)=>a.localeCompare(b)*sortDir),ff=[...files].sort((a,b)=>a.localeCompare(b)*sortDir);const fr=fs.map(n=>{const path=joinPath(current,n);return`<div class="sshot-row"><button class="sshot-name folder" data-drill="${esc(n)}">▱&nbsp; ${esc(n)}</button><span class="sshot-meta">Folder</span><span class="sshot-meta">—</span><span class="sshot-meta">—</span><button class="sshot-plus" data-add-folder="${esc(path)}" title="Add this folder">＋</button></div>`}).join('');const fi=ff.map(n=>`<div class="sshot-row"><span class="sshot-name">▧&nbsp; ${esc(n)}</span><span class="sshot-meta">File</span><span class="sshot-meta">—</span><span class="sshot-meta">—</span><span></span></div>`).join('');$('#browserList').innerHTML=fr+fi||'<div class="sshot-empty">This folder is empty.</div>';$('#itemCount').textContent=`${fs.length+ff.length} item${fs.length+ff.length===1?'':'s'}`;document.querySelectorAll('[data-drill]').forEach(b=>b.onclick=async()=>{const next=joinPath(current,b.dataset.drill);history.push(next);await load(next)});document.querySelectorAll('[data-add-folder]').forEach(b=>b.onclick=()=>{if(stage(b.dataset.addFolder))toast('Folder added to project draft.')})}
  $('#sortName').onclick=()=>{sortDir*=-1;$('#sortName').textContent=`Name ${sortDir===1?'↑':'↓'}`;renderRows()};
  $('#addSelected').onclick=()=>{let added=0;for(const path of checkedVolumes)if(stage(path))added++;if(!checkedVolumes.size&&current&&stage(current))added++;checkedVolumes.clear();renderPlaces();if(added)toast(`${added} location${added===1?'':'s'} added to project draft.`)};
  $('#up').onclick=async()=>{if(history.length<=1)return;history.pop();await load(history[history.length-1])};
  $('#rescan').onclick=()=>current?load(current):checkServices().then(renderPlaces);
  $('#newFolder').onclick=async()=>{if(!current){toast('Choose a location first.','warn');return}const name=(prompt('New folder name:')||'').trim();if(!name)return;try{await apiMkdir(current,name);await load(current);toast('Folder created.')}catch(e){toast(`New folder failed: ${e.message}`,'error')}};
  $('#helpBtn').onclick=()=>$('#howCard')?.scrollIntoView({behavior:'smooth',block:'nearest'});
  $('#saveLocations').onclick=()=>{state.intake.sources=staged;close(true);renderIntake();toast(`${staged.length} location${staged.length===1?'':'s'} saved to draft.`)};
  $('#cancelLocations').onclick=()=>close(false);
  async function pickLocalSourceAndStage(){const src=await pickLocalDeviceSource();if(src&&!staged.some(s=>sourceKey(s)===sourceKey(src))){staged.push(src);renderSelected();toast('Device location staged.')}}
  renderPlaces();renderSelected();
}
'''
marker='function parentPath(path,root)'
if marker not in s: raise SystemExit('FAIL insertion marker')
s=s.replace(marker,fn+'\n'+marker,1)
old='function openExplorer(mode){const root=$(\'#modalRoot\');'
new="function openExplorer(mode){if(mode==='source')return openApprovedSourcePicker();const root=$('#modalRoot');"
if old not in s: raise SystemExit('FAIL exact .4.5 explorer marker missing')
s=s.replace(old,new,1)
p.write_text(s)

g=Path('project-backlog.md')
text=g.read_text()
note='''\n## Owner gate — .4.7 rejected; .4.8 screenshot-layout rebuild\n\nBuild `.4.7` is rejected as an implementation direction because it retained the stale browser presentation and effectively bolted the third pane onto it. Do not patch `.4.7` forward. `.4.8` is rebuilt from exact working `.4.5` browser behavior and applies the owner-approved screenshot layout.\n\nLocked source-picker presentation for `.4.8`:\n\n- Fixed/stable modal geometry; selecting or browsing a drive/folder must not change modal dimensions or cause layout jumps.\n- Three full-height panes: **Locations**, **folder/file browser**, **Added to project**.\n- Toolbar across the top: Up, Rescan, current path, Add to project, New folder, help.\n- Left pane shows all available volumes/locations. Each volume has a checkbox for whole-volume selection; clicking the volume name browses it without selecting it.\n- Center pane is an independently scrolling table with Name / Type / Size / Modified and per-folder `+` staging action. Folder name drills into the folder.\n- Right pane persistently shows staged sources with remove controls plus Save selections / Cancel.\n- The screenshot supplied by the owner is the visual authority for this picker.\n- Preserve `.4.5` filesystem enumeration/API behavior; no new server, port, route, or backend architecture.\n\n'''
if '## Owner gate — .4.7 rejected; .4.8 screenshot-layout rebuild' not in text:
    text=text.replace('# 2. RELEASE CHAIN',note+'# 2. RELEASE CHAIN')
g.write_text(text)
